import { createContext, useContext, useEffect, useMemo, useState } from "react";
import { useAuth } from "./AuthContext.jsx";
import { updateCurrentPatient } from "../api/auth.js";

const LanguageContext = createContext(null);

export const SUPPORTED_LANGUAGES = [
  { code: "en", name: "English", nativeName: "English" },
  { code: "hi", name: "Hindi", nativeName: "हिन्दी" },
  { code: "bn", name: "Bengali", nativeName: "বাংলা" },
  { code: "ta", name: "Tamil", nativeName: "தமிழ்" },
  { code: "te", name: "Telugu", nativeName: "తెలుగు" },
  { code: "mr", name: "Marathi", nativeName: "मराठी" },
  { code: "gu", name: "Gujarati", nativeName: "ગુજરાતી" },
  { code: "kn", name: "Kannada", nativeName: "ಕನ್ನಡ" },
  { code: "ml", name: "Malayalam", nativeName: "മലയാളം" },
  { code: "pa", name: "Punjabi", nativeName: "ਪੰਜਾਬੀ" },
];

export const TRANSLATIONS = {
  en: {
    // Nav & Shell
    care: "Care",
    dashboard: "Dashboard",
    medical_records: "Medical Records",
    ai_health_assistant: "AI Health Assistant",
    upload_documents: "Upload Documents",
    book_appointment: "Book Appointment",
    daily_routine: "Daily routine",
    health_tracker: "Health Tracker",
    exercise_yoga: "Exercise & Yoga",
    ayurvedic_care: "Ayurvedic Care",
    reminders: "Reminders",
    account: "Account",
    profile: "Profile",
    patient_workspace: "Patient workspace",
    signed_in: "Signed in",
    logout: "Logout",
    menu: "Menu",
    high_contrast: "High contrast",
    standard_view: "Standard view",
    language: "Language",
    select_language: "Select Language",

    // Dashboard
    welcome_back: "Welcome back",
    hello: "Hello",
    health_overview: "Your complete health history — sessions, reports, and uploads.",
    quick_actions: "Quick Actions",
    talk_to_ai: "Talk to AI Assistant",
    record_history: "Record History",
    view_records: "View Records",
    vitals_summary: "Vitals Summary",
    heart_rate: "Heart Rate",
    blood_pressure: "Blood Pressure",
    blood_glucose: "Blood Glucose",
    bmi_weight: "BMI & Weight",
    spo2: "Oxygen (SpO2)",
    recent_prescriptions: "Recent Prescriptions",
    upcoming_appointments: "Upcoming Appointments",
    no_prescriptions: "No prescriptions yet",
    no_appointments: "No upcoming appointments",

    // Chat
    chat_title: "AI Health Assistant",
    chat_subtitle: "Ask about your prescriptions, symptom guidance, Ayurvedic lifestyle tips, and exercises.",
    new_chat: "+ New chat",
    conversations: "Conversations",
    type_message: "Ask a health question in your language…",
    send: "Send",
    thinking: "AI Assistant is thinking…",
    chat_disclaimer: "AI assistant provides guidance, not final medical diagnosis. In an emergency, contact a hospital immediately.",
    emergency_detected: "Emergency symptoms detected. Please seek emergency medical care immediately.",
    suggestion_rx: "Explain my prescription in simple words",
    suggestion_remedies: "Ayurvedic home remedies for cold & cough",
    suggestion_exercise: "Recommend safe morning yoga for me",
    suggestion_diet: "What healthy foods should I eat today?",
    no_previous_chats: "No previous chats",
    start_first_chat: "Start your first conversation with your AI Health Companion.",

    // Medical Records
    records_title: "Medical Records",
    records_subtitle: "Your complete health history — sessions, reports, and uploads.",
    add_medical_data: "Add medical data",
    record_new_history: "Record new history",
    upload_a_document: "Upload a document",
    view_read_rx: "View & Read Prescription",
    download_print_pdf: "Download / Print PDF",
    official_rx: "Official Rx",
    lab_report: "Lab Report",
    history_session: "History session",
    prescribed_by: "Prescribed by",
    medicines: "Medicines",
    advice: "Advice",
    yoga_lifestyle: "Yoga / Lifestyle",
    view_document: "View document →",
    view_full_history: "View full history →",
    continue_recording: "Continue recording →",
    no_records: "No health records yet. Start by recording your first history or uploading a document.",

    // Common
    save: "Save",
    cancel: "Cancel",
    close: "Close",
    loading: "Loading…",
    error: "Error",
    retry: "Retry",
    back: "Back",
    next: "Next",
    submit: "Submit",
    start: "Start",
    save_changes: "Save changes",

    // Demographic & Profile
    yrs: "yrs",
    gender_male: "Male",
    gender_female: "Female",
    gender_other: "Other",
    patient: "Patient",
    age_not_set: "Age not set",
    gender_not_set: "Gender not set",
    height_not_set: "Height not set",
    weight_not_set: "Weight not set",
    height: "Height",
    weight: "Weight",
    lang_en: "English",
    lang_hi: "Hindi",
    lang_bn: "Bengali",
    lang_ta: "Tamil",
    lang_te: "Telugu",
    lang_mr: "Marathi",
    lang_gu: "Gujarati",
    lang_kn: "Kannada",
    lang_ml: "Malayalam",
    lang_pa: "Punjabi",

    // Dates & Times
    today: "Today",
    yesterday: "Yesterday",
    tomorrow: "Tomorrow",
    last_updated: "Last updated",
    previous: "Previous",
    context: "Context",
    fasting: "Fasting",
    post_meal: "Post meal",
    random: "Random",
    no_data: "No data",
    no_readings_yet: "No readings yet",
    current_reading: "Current reading",

    // Vitals & Classification
    blood_pressure_label: "Blood pressure",
    blood_sugar_label: "Blood sugar",
    heart_rate_label: "Heart rate",
    usual_range: "Usual range",
    recorded: "Recorded",
    high: "High",
    low: "Low",
    stable: "Stable",
    higher_than_last: "Higher than last time",
    lower_than_last: "Lower than last time",

    // Reminders & Routine
    daily_health_routine: "Daily Health Reminders & Routine",
    medicine_reminders: "Medicine Reminders",
    prescriptions_doses: "Prescriptions & Scheduled Doses",
    active: "Active",
    taken: "Taken",
    take_dose: "Take Dose",
    no_meds_scheduled: "No medicines scheduled for today.",
    upload_rx_import: "Upload prescription to import medicines →",
    track_logs_reminders: "Track logs in Reminders",
    manage_reminders: "Manage All Reminders →",

    // Yoga
    todays_yoga: "Today's Yoga Matrix",
    yoga_subtitle: "Doctor-Prescribed & AI Form Coach",
    done: "Done",
    check_pose: "Check Pose",
    mark_done: "Mark Done",
    body_pointer_hint: "Hold postures with body pointer feedback",
    full_yoga_routine: "Full Yoga Matrix & Routine →",
    daily: "Daily",
    morning: "Morning",
    evening: "Evening",
    min: "min",

    // Personalized Nutrition & BMI
    nutrition_needs: "Personalized Nutrition & Caloric Needs",
    nutrition_subtitle: "Computed from your Height, Weight & BMI",
    bmi_label: "Body Mass Index (BMI)",
    normal_weight: "Normal Weight",
    underweight: "Underweight",
    overweight: "Overweight",
    obese: "Obese",
    target_calories: "Target Daily Calories",
    kcal_day: "kcal / day",
    clinical_goal: "Clinical Goal",
    goal_maintenance: "Optimal Maintenance & Vitality",
    goal_surplus: "Calorie Surplus & Muscle Building",
    goal_balanced: "Balanced Maintenance & Metabolic Health",
    goal_deficit: "Moderate Deficit & Active Fat Loss",
    goal_reset: "Metabolic Reset & Anti-Inflammatory Deficit",
    hydration_fiber: "Daily Hydration & Fiber",
    water_intake: "Water intake",
    dietary_fiber: "Dietary fiber",
    macronutrient_split: "Macronutrient Target Split (Based on Body Composition):",
    protein: "Protein",
    protein_desc: "Lean muscle repair & metabolic satiety",
    complex_carbs: "Complex Carbs",
    carbs_desc: "Whole grains, pulses & sustained yoga energy",
    healthy_fats: "Healthy Fats",
    fats_desc: "Hormone production & joint lubrication",
    key_micronutrients: "Key Micronutrients Required for Your BMI Profile:",
    height_weight_prompt_title: "Set Your Height & Weight to Calculate Nutrients",
    height_weight_prompt_desc: "Enter your biometric parameters in your profile to view your exact Body Mass Index (BMI), personalized daily caloric target, macronutrient distribution, and micronutrient checklist.",
    enter_height_weight_btn: "Enter Height & Weight in Profile →",

    // Clinical Summary
    clinical_summary: "Current Clinical Summary",
    latest_diagnosis: "Latest diagnosis",
    recent_concern: "Recent concern",
    no_clinical_summary: "No clinical summary yet. Record your medical history to build one.",

    // Quick Action Subtitles
    chat_subtitle_short: "Ask a clinical question",
    exercise_desc: "Daily to-do checklist & CV pose coach",
    record_history_desc: "Answer questions by voice or text",
    upload_docs_desc: "Add a prescription or lab report",
    tracker_desc: "Blood pressure, sugar & vitals",
    reminders_desc: "Set custom medicine & lifestyle alarms",

    // Lists & Appointments
    recent_medical_history: "Recent Medical History",
    no_medical_history: "No medical history recorded yet.",
    recent_health_readings: "Recent Health Readings",
    no_health_readings: "No health readings available yet.",
    upcoming_appointments: "Upcoming Doctor Appointments",
    doctor: "Doctor",
    status_booked: "Booked",
    status_in_progress: "In Consultation",
    status_completed: "Completed",
    status_cancelled: "Cancelled",
  },

  hi: {
    // Nav & Shell
    care: "स्वास्थ्य सेवा",
    dashboard: "डैशबोर्ड",
    medical_records: "मेडिकल रिकॉर्ड्स",
    ai_health_assistant: "एआई स्वास्थ्य सहायक",
    upload_documents: "दस्तावेज़ अपलोड",
    book_appointment: "अपॉइंटमेंट बुक करें",
    daily_routine: "दैनिक दिनचर्या",
    health_tracker: "स्वास्थ्य ट्रैकर",
    exercise_yoga: "व्यायाम और योग",
    ayurvedic_care: "आयुर्वेदिक देखभाल",
    reminders: "दवा रिमाइंडर",
    account: "खाता",
    profile: "प्रोफ़ाइल",
    patient_workspace: "मरीज़ पोर्टल",
    signed_in: "लॉग इन हैं",
    logout: "लॉगआउट",
    menu: "मेनू",
    high_contrast: "उच्च कंट्रास्ट",
    standard_view: "सामान्य दृश्य",
    language: "भाषा",
    select_language: "भाषा चुनें",

    // Dashboard
    welcome_back: "वापसी पर स्वागत है",
    hello: "नमस्ते",
    health_overview: "आपका सम्पूर्ण स्वास्थ्य इतिहास — सत्र, रिपोर्ट और परामर्श।",
    quick_actions: "त्वरित क्रियाएं",
    talk_to_ai: "एआई सहायक से बात करें",
    record_history: "इतिहास रिकॉर्ड करें",
    view_records: "रिकॉर्ड्स देखें",
    vitals_summary: "वाइटल्स सारांश",
    heart_rate: "हृदय गति",
    blood_pressure: "रक्तचाप (BP)",
    blood_glucose: "ब्लड शुगर",
    bmi_weight: "बीएमआई और वजन",
    spo2: "ऑक्सीजन (SpO2)",
    recent_prescriptions: "हाल के नुस्खे (Prescriptions)",
    upcoming_appointments: "आगामी अपॉइंटमेंट्स",
    no_prescriptions: "अभी कोई नुस्खा नहीं है",
    no_appointments: "कोई आगामी अपॉइंटमेंट नहीं",

    // Chat
    chat_title: "एआई स्वास्थ्य सहायक",
    chat_subtitle: "अपने नुस्खे, लक्षण मार्गदर्शन, आयुर्वेदिक उपाय और व्यायाम के बारे में पूछें।",
    new_chat: "+ नई बातचीत",
    conversations: "पिछली बातचीत",
    type_message: "अपनी भाषा में स्वास्थ्य सम्बन्धी सवाल पूछें…",
    send: "भेजें",
    thinking: "एआई सहायक सोच रहा है…",
    chat_disclaimer: "एआई सहायक केवल स्वास्थ्य मार्गदर्शन देता है, यह डॉक्टर का विकल्प नहीं है। आपातकाल में तुरंत अस्पताल जाएं।",
    emergency_detected: "आपातकालीन लक्षण पाए गए। कृपया तुरंत आपातकालीन चिकित्सा सहायता लें।",
    suggestion_rx: "मेरे नुस्खे को सरल शब्दों में समझाएं",
    suggestion_remedies: "खांसी और जुकाम के आयुर्वेदिक घरेलू नुस्खे",
    suggestion_exercise: "मेरे लिए सुबह का सुरक्षित योग सुझाएं",
    suggestion_diet: "मुझे आज स्वस्थ रहने के लिए क्या खाना चाहिए?",
    no_previous_chats: "कोई पिछली बातचीत नहीं",
    start_first_chat: "अपने एआई स्वास्थ्य साथी के साथ पहली बातचीत शुरू करें।",

    // Medical Records
    records_title: "मेडिकल रिकॉर्ड्स",
    records_subtitle: "आपका सम्पूर्ण स्वास्थ्य इतिहास — सत्र, रिपोर्ट और अपलोड।",
    add_medical_data: "मेडिकल डेटा जोड़ें",
    record_new_history: "नया इतिहास दर्ज करें",
    upload_a_document: "दस्तावेज़ अपलोड करें",
    view_read_rx: "नुस्खा देखें और पढ़ें",
    download_print_pdf: "पीडीएफ डाउनलोड / प्रिंट करें",
    official_rx: "आधिकारिक नुस्खा",
    lab_report: "लैब रिपोर्ट",
    history_session: "इतिहास सत्र",
    prescribed_by: "द्वारा निर्धारित",
    medicines: "दवाइयां",
    advice: "सलाह",
    yoga_lifestyle: "योग / जीवनशैली",
    view_document: "दस्तावेज़ देखें →",
    view_full_history: "पूर्ण इतिहास देखें →",
    continue_recording: "रिकॉर्डिंग जारी रखें →",
    no_records: "अभी कोई रिकॉर्ड नहीं है। नया इतिहास दर्ज करके या रिपोर्ट अपलोड करके शुरुआत करें।",

    // Common
    save: "सुरक्षित करें",
    cancel: "रद्द करें",
    close: "बंद करें",
    loading: "लोड हो रहा है…",
    error: "त्रुटि",
    retry: "पुनः प्रयास करें",
    back: "पीछे",
    next: "आगे",
    submit: "जमा करें",
    start: "शुरू करें",
    save_changes: "बदलाव सुरक्षित करें",

    // Demographic & Profile
    yrs: "वर्ष",
    gender_male: "पुरुष",
    gender_female: "महिला",
    gender_other: "अन्य",
    patient: "मरीज़",
    age_not_set: "उम्र दर्ज नहीं",
    gender_not_set: "लिंग दर्ज नहीं",
    height_not_set: "ऊंचाई दर्ज नहीं",
    weight_not_set: "वजन दर्ज नहीं",
    height: "ऊंचाई",
    weight: "वजन",
    lang_en: "अंग्रेज़ी",
    lang_hi: "हिन्दी",
    lang_bn: "बंगाली",
    lang_ta: "तमिल",
    lang_te: "तेलुगु",
    lang_mr: "मराठी",
    lang_gu: "गुजराती",
    lang_kn: "कन्नड़",
    lang_ml: "मलयालम",
    lang_pa: "पंजाबी",

    // Dates & Times
    today: "आज",
    yesterday: "कल",
    tomorrow: "कल (आने वाला)",
    last_updated: "अंतिम अपडेट",
    previous: "पिछला",
    context: "संदर्भ",
    fasting: "खाली पेट (Fasting)",
    post_meal: "भोजन के बाद (Post-meal)",
    random: "सामान्य (Random)",
    no_data: "कोई डेटा नहीं",
    no_readings_yet: "अभी कोई रीडिंग नहीं है",
    current_reading: "वर्तमान रीडिंग",

    // Vitals & Classification
    blood_pressure_label: "रक्तचाप (BP)",
    blood_sugar_label: "ब्लड शुगर",
    heart_rate_label: "हृदय गति",
    usual_range: "सामान्य सीमा",
    recorded: "दर्ज किया गया",
    high: "उच्च",
    low: "निम्न",
    stable: "स्थिर",
    higher_than_last: "पिछली बार से अधिक",
    lower_than_last: "पिछली बार से कम",

    // Reminders & Routine
    daily_health_routine: "दैनिक स्वास्थ्य रिमाइंडर और दिनचर्या",
    medicine_reminders: "दवा रिमाइंडर",
    prescriptions_doses: "दवाइयां और निर्धारित खुराक",
    active: "सक्रिय",
    taken: "ली गई",
    take_dose: "खुराक लें",
    no_meds_scheduled: "आज के लिए कोई दवा निर्धारित नहीं है।",
    upload_rx_import: "दवाइयां जोड़ने के लिए नुस्खा (Rx) अपलोड करें →",
    track_logs_reminders: "रिमाइंडर में लॉग देखें",
    manage_reminders: "सभी रिमाइंडर प्रबंधित करें →",

    // Yoga
    todays_yoga: "आज का योग अभ्यास",
    yoga_subtitle: "डॉक्टर द्वारा निर्धारित और एआई कोच",
    done: "पूर्ण",
    check_pose: "मुद्रा जांचें",
    mark_done: "पूर्ण चिह्नित करें",
    body_pointer_hint: "बॉडी पॉइंटर फीडबैक के साथ मुद्रा बनाएं",
    full_yoga_routine: "पूरा योग कार्यक्रम →",
    daily: "दैनिक",
    morning: "सुबह",
    evening: "शाम",
    min: "मिनट",

    // Personalized Nutrition & BMI
    nutrition_needs: "व्यक्तिगत पोषण और कैलोरी आवश्यकताएं",
    nutrition_subtitle: "आपकी ऊंचाई, वजन और बीएमआई से गणना की गई",
    bmi_label: "बॉडी मास इंडेक्स (BMI)",
    normal_weight: "सामान्य वजन",
    underweight: "कम वजन",
    overweight: "अधिक वजन",
    obese: "मोटापा",
    target_calories: "दैनिक लक्षित कैलोरी",
    kcal_day: "किलो कैलोरी / दिन",
    clinical_goal: "नैदानिक लक्ष्य",
    goal_maintenance: "इष्टतम रखरखाव और जीवन शक्ति",
    goal_surplus: "कैलोरी वृद्धि और मांसपेशी निर्माण",
    goal_balanced: "संतुलित रखरखाव और चयापचय स्वास्थ्य",
    goal_deficit: "मध्यम वसा कमी और फैट लॉस",
    goal_reset: "मेटाबोलिक रीसेट और सूजन-रोधी आहार",
    hydration_fiber: "दैनिक जल और फाइबर",
    water_intake: "पानी का सेवन",
    dietary_fiber: "आहार फाइबर",
    macronutrient_split: "मैक्रोन्यूट्रिएंट लक्षित विभाजन (शारीरिक संरचना अनुसार):",
    protein: "प्रोटीन",
    protein_desc: "मांसपेशियों की मरम्मत और तृप्ति",
    complex_carbs: "जटिल कार्ब्स",
    carbs_desc: "साबुत अनाज, दालें और निरंतर ऊर्जा",
    healthy_fats: "स्वस्थ वसा",
    fats_desc: "हार्मोन निर्माण और जोड़ों का स्वास्थ्य",
    key_micronutrients: "आपके बीएमआई प्रोफाइल के लिए आवश्यक प्रमुख सूक्ष्म पोषक तत्व:",
    height_weight_prompt_title: "पोषण की गणना के लिए ऊंचाई और वजन दर्ज करें",
    height_weight_prompt_desc: "अपना सटीक बीएमआई (BMI), दैनिक कैलोरी लक्ष्य, और पोषक तत्वों की सूची देखने के लिए प्रोफ़ाइल में अपनी ऊंचाई और वजन दर्ज करें।",
    enter_height_weight_btn: "प्रोफ़ाइल में ऊंचाई और वजन दर्ज करें →",

    // Clinical Summary
    clinical_summary: "वर्तमान नैदानिक सारांश",
    latest_diagnosis: "नवीनतम निदान",
    recent_concern: "हालिया समस्या",
    no_clinical_summary: "अभी कोई नैदानिक सारांश नहीं है। इसे बनाने के लिए अपना मेडिकल इतिहास दर्ज करें।",

    // Quick Action Subtitles
    chat_subtitle_short: "चिकित्सीय प्रश्न पूछें",
    exercise_desc: "दैनिक चेकलिस्ट और योग कोच",
    record_history_desc: "आवाज या टेक्स्ट से प्रश्नों के उत्तर दें",
    upload_docs_desc: "पर्चा या लैब रिपोर्ट जोड़ें",
    tracker_desc: "रक्तचाप, शुगर और महत्वपूर्ण संकेत",
    reminders_desc: "दवा और जीवनशैली अलार्म सेट करें",

    // Lists & Appointments
    recent_medical_history: "हालिया चिकित्सा इतिहास",
    no_medical_history: "अभी कोई मेडिकल इतिहास दर्ज नहीं है।",
    recent_health_readings: "हालिया स्वास्थ्य रीडिंग",
    no_health_readings: "अभी कोई स्वास्थ्य रीडिंग उपलब्ध नहीं है।",
    upcoming_appointments: "आगामी डॉक्टर अपॉइंटमेंट्स",
    doctor: "डॉक्टर",
    status_booked: "बुक किया गया",
    status_in_progress: "परामर्श जारी",
    status_completed: "पूर्ण",
    status_cancelled: "रद्द",
  },

  bn: {
    care: "স্বাস্থ্য সেবা",
    dashboard: "ড্যাশবোর্ড",
    medical_records: "মেডিকেল রেকর্ডস",
    ai_health_assistant: "এআই স্বাস্থ্য সহকারী",
    upload_documents: "নথি আপলোড",
    book_appointment: "অ্যাপয়েন্টমেন্ট বুকিং",
    daily_routine: "দৈনন্দিন রুটিন",
    health_tracker: "স্বাস্থ্য ট্র্যাকার",
    exercise_yoga: "ব্যায়াম ও যোগব্যায়াম",
    ayurvedic_care: "আয়ুর্বেদিক সেবা",
    reminders: "ঔষধের অনুস্মারক",
    account: "অ্যাকাউন্ট",
    profile: "প্রোফাইল",
    patient_workspace: "রোগীর পোর্টাল",
    signed_in: "লগ ইন আছেন",
    logout: "লগআউট",
    menu: "মেনু",
    high_contrast: "উচ্চ কনট্রাস্ট",
    standard_view: "সাধারণ দৃশ্য",
    language: "ভাষা",
    select_language: "ভাষা নির্বাচন করুন",
    welcome_back: "স্বাগতম",
    hello: "নমস্কার",
    health_overview: "আপনার সম্পূর্ণ স্বাস্থ্য ইতিহাস — সেশন, রিপোর্ট এবং প্রেসক্রিপশন।",
    quick_actions: "দ্রুত পদক্ষেপ",
    talk_to_ai: "এআই সহকারীর সাথে কথা বলুন",
    record_history: "ইতিহাস রেকর্ড করুন",
    view_records: "রেকর্ড দেখুন",
    vitals_summary: "ভাইটালস সারাংশ",
    heart_rate: "হৃদস্পন্দন",
    blood_pressure: "রক্তচাপ (BP)",
    blood_glucose: "ব্লাড সুগার",
    bmi_weight: "বিএমআই ও ওজন",
    spo2: "অক্সিজেন (SpO2)",
    recent_prescriptions: "সাম্প্রতিক প্রেসক্রিপশন",
    upcoming_appointments: "আসন্ন অ্যাপয়েন্টমেন্ট",
    no_prescriptions: "এখনও কোনো প্রেসক্রিপশন নেই",
    no_appointments: "কোনো আসন্ন অ্যাপয়েন্টমেন্ট নেই",
    chat_title: "এআই স্বাস্থ্য সহকারী",
    chat_subtitle: "আপনার প্রেসক্রিপশন, লক্ষণ, আয়ুর্বেদিক পরামর্শ এবং ব্যায়াম সম্পর্কে জানুন।",
    new_chat: "+ নতুন চ্যাট",
    conversations: "কথোপকথন",
    type_message: "আপনার ভাষায় স্বাস্থ্য সংক্রান্ত প্রশ্ন লিখুন…",
    send: "পাঠান",
    thinking: "এআই চিন্তা করছে…",
    chat_disclaimer: "এআই সহকারী কেবল পরামর্শ দেয়, ডাক্তারের বিকল্প নয়। জরুরি অবস্থায় অবিলম্বে হাসপাতালে যান।",
    emergency_detected: "জরুরি লক্ষণ সনাক্ত হয়েছে। দয়া করে অবিলম্বে জরুরি স্বাস্থ্যসেবা নিন।",
    suggestion_rx: "আমার প্রেসক্রিপশনটি সহজ ভাষায় বুঝিয়ে দিন",
    suggestion_remedies: "সর্দি ও কাশির জন্য আয়ুর্বেদিক ঘরোয়া প্রতিকার",
    suggestion_exercise: "আমার জন্য নিরাপদ সকালের যোগব্যায়াম বলুন",
    suggestion_diet: "সুস্থ থাকতে আজ আমার কী খাওয়া উচিত?",
    no_previous_chats: "কোনো পূর্ববর্তী চ্যাট নেই",
    start_first_chat: "আপনার এআই স্বাস্থ্য সহকারীর সাথে প্রথম আলোচনা শুরু করুন।",
    records_title: "মেডিকেল রেকর্ডস",
    records_subtitle: "আপনার সম্পূর্ণ স্বাস্থ্য ইতিহাস — সেশন, রিপোর্ট এবং আপলোড।",
    add_medical_data: "তথ্য যোগ করুন",
    record_new_history: "নতুন ইতিহাস রেকর্ড করুন",
    upload_a_document: "নথি আপলোড করুন",
    view_read_rx: "প্রেসক্রিপশন পড়ুন",
    download_print_pdf: "পিডিএফ ডাউনলোড / প্রিন্ট",
    official_rx: "অফিসিয়াল প্রেসক্রিপশন",
    lab_report: "ল্যাব রিপোর্ট",
    history_session: "ইতিহাস সেশন",
    prescribed_by: "চিকিৎসক",
    medicines: "ঔষধ",
    advice: "পরামর্শ",
    yoga_lifestyle: "যোগ / জীবনধারা",
    view_document: "নথি দেখুন →",
    view_full_history: "সম্পূর্ণ ইতিহাস →",
    continue_recording: "রেকর্ডিং চালিয়ে যান →",
    no_records: "কোনো রেকর্ড পাওয়া যায়নি।",
    save: "সংরক্ষণ",
    cancel: "বাতিল",
    close: "বন্ধ করুন",
    loading: "লোড হচ্ছে…",
    error: "ত্রুটি",
    retry: "পুনরায় চেষ্টা",
    back: "পিছনে",
    next: "পরবর্তী",
    submit: "জমা দিন",
    start: "শুরু করুন",
    save_changes: "পরিবর্তন সংরক্ষণ করুন",

    // Demographic & Profile
    yrs: "বছর",
    gender_male: "পুরুষ",
    gender_female: "মহিলা",
    gender_other: "অন্যান্য",
    patient: "রোগী",
    age_not_set: "বয়স অনির্ধারিত",
    gender_not_set: "লিঙ্গ অনির্ধারিত",
    height_not_set: "উচ্চতা অনির্ধারিত",
    weight_not_set: "ওজন অনির্ধারিত",
    height: "উচ্চতা",
    weight: "ওজন",
    lang_en: "ইংরেজি",
    lang_hi: "হিন্দি",
    lang_bn: "বাংলা",
    lang_ta: "তামিল",
    lang_te: "তেলেগু",
    lang_mr: "মারাঠি",
    lang_gu: "গুজরাতি",
    lang_kn: "কন্নড়",
    lang_ml: "মালয়ালম",
    lang_pa: "পাঞ্জাবি",

    // Dates & Times
    today: "আজ",
    yesterday: "গতকাল",
    tomorrow: "আগামীকাল",
    last_updated: "সর্বশেষ আপডেট",
    previous: "পূর্ববর্তী",
    context: "প্রসঙ্গ",
    fasting: "খালি পেটে (Fasting)",
    post_meal: "খাবারের পরে (Post-meal)",
    random: "সাধারণ (Random)",
    no_data: "কোনো তথ্য নেই",
    no_readings_yet: "এখনও কোনো রিডিং নেই",
    current_reading: "বর্তমান রিডিং",

    // Vitals & Classification
    blood_pressure_label: "রক্তচাপ (BP)",
    blood_sugar_label: "ব্লাড সুগার",
    heart_rate_label: "হৃদস্পন্দন",
    usual_range: "স্বাভাবিক মাত্রা",
    recorded: "রেকর্ডকৃত",
    high: "উচ্চ",
    low: "নিম্ন",
    stable: "স্থিতিশীল",
    higher_than_last: "আগের বারের চেয়ে বেশি",
    lower_than_last: "আগের বারের চেয়ে কম",

    // Reminders & Routine
    daily_health_routine: "দৈনন্দিন স্বাস্থ্য অনুস্মারক ও রুটিন",
    medicine_reminders: "ওষুধের অনুস্মারক",
    prescriptions_doses: "প্রেসক্রিপশন ও নির্ধারিত ডোজ",
    active: "সক্রিয়",
    taken: "নেওয়া হয়েছে",
    take_dose: "ডোজ গ্রহণ করুন",
    no_meds_scheduled: "আজকের জন্য কোনো ওষুধ নির্ধারিত নেই।",
    upload_rx_import: "ওষুধ যোগ করতে প্রেসক্রিপশন আপলোড করুন →",
    track_logs_reminders: "অনুস্মারকে লগ দেখুন",
    manage_reminders: "সব অনুস্মারক পরিচালনা করুন →",

    // Yoga
    todays_yoga: "আজকের যোগব্যায়াম তালিকা",
    yoga_subtitle: "ডাক্তার নির্ধারিত ও এআই পোজ কোচ",
    done: "সম্পন্ন",
    check_pose: "ভঙ্গি পরীক্ষা করুন",
    mark_done: "সম্পন্ন চিহ্নিত করুন",
    body_pointer_hint: "বডি পয়েন্টার নির্দেশনায় ভঙ্গি বজায় রাখুন",
    full_yoga_routine: "সম্পূর্ণ যোগব্যায়াম রুটিন →",
    daily: "প্রতিদিন",
    morning: "সকাল",
    evening: "সন্ধ্যা",
    min: "মিনিট",

    // Personalized Nutrition & BMI
    nutrition_needs: "ব্যক্তিগত পুষ্টি ও ক্যালোরির চাহিদা",
    nutrition_subtitle: "উচ্চতা, ওজন ও বিএমআই অনুযায়ী গণনাকৃত",
    bmi_label: "বডি ম্যাস ইনডেক্স (BMI)",
    normal_weight: "স্বাভাবিক ওজন",
    underweight: "স্বল্প ওজন",
    overweight: "অতিরিক্ত ওজন",
    obese: "স্থূলতা",
    target_calories: "দৈনিক লক্ষ্যমাত্রা ক্যালোরি",
    kcal_day: "কিলোক্যালোরি / দিন",
    clinical_goal: "চিকিৎসা লক্ষ্য",
    goal_maintenance: "সর্বোত্তম রক্ষণাবেক্ষণ ও প্রাণশক্তি",
    goal_surplus: "ক্যালোরি বৃদ্ধি ও পেশি গঠন",
    goal_balanced: "ভারসাম্যপূর্ণ রক্ষণাবেক্ষণ ও স্বাস্থ্য",
    goal_deficit: "পরিমিত ঘাটতি ও চর্বি হ্রাস",
    goal_reset: "মেটাবলিক রিসেট ও প্রদাহ-বিরোধী ডায়েট",
    hydration_fiber: "দৈনিক পানি ও ফাইবার",
    water_intake: "পানি গ্রহণ",
    dietary_fiber: "খাদ্যতালিকাগত ফাইবার",
    macronutrient_split: "ম্যাক্রোনিউট্রিয়েন্ট লক্ষ্য বিভাজন (শারীরিক গঠন অনুযায়ী):",
    protein: "প্রোটিন",
    protein_desc: "পেশি মেরামত ও মেটাবলিক সন্তুষ্টি",
    complex_carbs: "জটিল কার্বস",
    carbs_desc: "আস্ত শস্যদানা, ডাল ও দীর্ঘস্থায়ী শক্তি",
    healthy_fats: "স্বাস্থ্যকর ফ্যাট",
    fats_desc: "হরমোন উৎপাদন ও জয়েন্টের সুরক্ষা",
    key_micronutrients: "আপনার বিএমআই প্রোফাইলের জন্য প্রয়োজনীয় প্রধান মাইক্রোনিউট্রিয়েন্ট:",
    height_weight_prompt_title: "পুষ্টি হিসাবের জন্য উচ্চতা ও ওজন লিখুন",
    height_weight_prompt_desc: "সঠিক বিএমআই (BMI), ক্যালোরি লক্ষ্য ও পুষ্টির নির্দেশিকা দেখতে প্রোফাইলে উচ্চতা এবং ওজন যুক্ত করুন।",
    enter_height_weight_btn: "প্রোফাইলে উচ্চতা ও ওজন লিখুন →",

    // Clinical Summary
    clinical_summary: "বর্তমান চিকিৎসার সারাংশ",
    latest_diagnosis: "সর্বশেষ রোগ নির্ণয়",
    recent_concern: "সাম্প্রতিক উদ্বেগ",
    no_clinical_summary: "এখনও চিকিৎসার সারাংশ নেই। এটি তৈরি করতে চিকিৎসার ইতিহাস রেকর্ড করুন।",

    // Quick Action Subtitles
    chat_subtitle_short: "চিকিৎসা সংক্রান্ত প্রশ্ন জিজ্ঞাসা করুন",
    exercise_desc: "দৈনিক চেকলিস্ট ও এআই ভঙ্গি কোচ",
    record_history_desc: "ভয়েস বা টেক্সটের মাধ্যমে উত্তর দিন",
    upload_docs_desc: "প্রেসক্রিপশন বা ল্যাব রিপোর্ট যোগ করুন",
    tracker_desc: "রক্তচাপ, সুগার ও গুরুত্বপূর্ণ লক্ষণ",
    reminders_desc: "ওষুধ ও জীবনধারার অ্যালার্ম সেট করুন",

    // Lists & Appointments
    recent_medical_history: "সাম্প্রতিক চিকিৎসার ইতিহাস",
    no_medical_history: "এখনও কোনো চিকিৎসার ইতিহাস রেকর্ড করা হয়নি।",
    recent_health_readings: "সাম্প্রতিক স্বাস্থ্য রিডিং",
    no_health_readings: "এখনও কোনো স্বাস্থ্য রিডিং পাওয়া যায়নি।",
    upcoming_appointments: "আসন্ন ডাক্তারের অ্যাপয়েন্টমেন্ট",
    doctor: "ডাক্তার",
    status_booked: "নিশ্চিত হয়েছে",
    status_in_progress: "পরামর্শ চলছে",
    status_completed: "সম্পন্ন",
    status_cancelled: "বাতিল",
  },

  ta: {
    care: "சுகாதாரம்",
    dashboard: "முகப்பு",
    medical_records: "மருத்துவ ஆவணங்கள்",
    ai_health_assistant: "AI சுகாதார உதவியாளர்",
    upload_documents: "ஆவண பதிவேற்றம்",
    book_appointment: "முன்பதிவு செய்ய",
    daily_routine: "தினசரி வழக்கம்",
    health_tracker: "உடல்நல கண்காணிப்பாளர்",
    exercise_yoga: "உடற்பயிற்சி & யோகா",
    ayurvedic_care: "ஆயுர்வேத பராமரிப்பு",
    reminders: "மருந்து நினைவூட்டல்",
    account: "கணக்கு",
    profile: "சுயவிவரம்",
    patient_workspace: "நோயாளி தளம்",
    signed_in: "உள்நுழைந்துள்ளீர்கள்",
    logout: "வெளியேறு",
    menu: "மெனு",
    high_contrast: "உயர் மாறுபாடு",
    standard_view: "வழக்கமான பார்வை",
    language: "மொழி",
    select_language: "மொழியைத் தேர்ந்தெடுக்கவும்",
    welcome_back: "நல்வரவு",
    hello: "வணக்கம்",
    health_overview: "உங்கள் முழுமையான மருத்துவ வரலாறு — அமர்வுகள், அறிக்கைகள் மற்றும் பதிவேற்றங்கள்.",
    quick_actions: "விரைவு நடவடிக்கைகள்",
    talk_to_ai: "AI உதவியாளரிடம் பேசுங்கள்",
    record_history: "வரலாறை பதிவு செய்",
    view_records: "ஆவணங்களைப் பார்க்க",
    vitals_summary: "முக்கிய அளவீடுகள்",
    heart_rate: "இதயத் துடிப்பு",
    blood_pressure: "இரத்த அழுத்தம் (BP)",
    blood_glucose: "இரத்த சர்க்கரை",
    bmi_weight: "பிஎம்ஐ & எடை",
    spo2: "ஆக்ஸிஜன் (SpO2)",
    recent_prescriptions: "சமீபத்திய மருந்துக் குறிப்புகள்",
    upcoming_appointments: "வரவிருக்கும் முன்பதிவுகள்",
    no_prescriptions: "மருந்துக் குறிப்புகள் எதுவும் இல்லை",
    no_appointments: "முன்பதிவுகள் எதுவும் இல்லை",
    chat_title: "AI சுகாதார உதவியாளர்",
    chat_subtitle: "உங்கள் மருந்துகள், அறிகுறிகள் மற்றும் ஆயுர்வேத குறிப்புகள் பற்றி கேளுங்கள்.",
    new_chat: "+ புதிய உரையாடல்",
    conversations: "உரையாடல்கள்",
    type_message: "உங்கள் மொழியில் சுகாதார கேள்வியைக் கேளுங்கள்…",
    send: "அனுப்பு",
    thinking: "AI உதவியாளர் சிந்திக்கிறது…",
    chat_disclaimer: "AI உதவியாளர் வழிகாட்டுதலை மட்டுமே வழங்குகிறது. அவசரநிலைக்கு மருத்துவமனையை அணுகவும்.",
    emergency_detected: "அவசர அறிகுறிகள் கண்டறியப்பட்டன. உடனடியாக மருத்துவ உதவியை நாடுங்கள்.",
    suggestion_rx: "எனது மருந்துக் குறிப்பை எளிய முறையில் விளக்குங்கள்",
    suggestion_remedies: "சளி மற்றும் இருமலுக்கான ஆயுர்வேத வீட்டு வைத்தியம்",
    suggestion_exercise: "எனக்கு ஏற்ற யோகாசனங்களை பரிந்துரைக்கவும்",
    suggestion_diet: "நான் இன்று என்ன ஆரோக்கியமான உணவை சாப்பிட வேண்டும்?",
    no_previous_chats: "முந்தைய உரையாடல்கள் இல்லை",
    start_first_chat: "AI மருத்துவ உதவியாளருடன் உரையாடலைத் தொடங்குங்கள்.",
    records_title: "மருத்துவ ஆவணங்கள்",
    records_subtitle: "உங்கள் முழுமையான மருத்துவ வரலாறு — அமர்வுகள் மற்றும் அறிக்கைகள்.",
    add_medical_data: "தரவைச் சேர்க்கவும்",
    record_new_history: "புதிய வரலாறு பதிவு",
    upload_a_document: "ஆவணத்தை பதிவேற்றவும்",
    view_read_rx: "மருந்துக் குறிப்பைப் பார்க்க",
    download_print_pdf: "PDF பதிவிறக்கம் / அச்சிடு",
    official_rx: "அதிகாரப்பூர்வ குறிப்பு",
    lab_report: "பரிசோதனை அறிக்கை",
    history_session: "அமர்வு",
    prescribed_by: "பரிந்துரைத்தவர்",
    medicines: "மருந்துகள்",
    advice: "ஆலோசனை",
    yoga_lifestyle: "யோகா / வாழ்க்கை முறை",
    view_document: "ஆவணத்தைப் பார் →",
    view_full_history: "முழு வரலாறு →",
    continue_recording: "தொடரவும் →",
    no_records: "ஆவணங்கள் எதுவும் இல்லை.",
    save: "சேமிக்க",
    cancel: "ரத்து செய்",
    close: "மூடு",
    loading: "ஏற்றுகிறது…",
    error: "பிழை",
    retry: "மீண்டும் முயல்க",
    back: "பின்னால்",
    next: "அடுத்து",
    submit: "சமர்ப்பிக்கவும்",
    start: "தொடங்கு",
    save_changes: "மாற்றங்களைச் சேமிக்கவும்",

    // Demographic & Profile
    yrs: "ஆண்டுகள்",
    gender_male: "ஆண்",
    gender_female: "பெண்",
    gender_other: "மற்றவை",
    patient: "நோயாளி",
    age_not_set: "வயது பதிவு செய்யப்படவில்லை",
    gender_not_set: "பாலினம் பதிவு செய்யப்படவில்லை",
    height_not_set: "உயரம் பதிவு செய்யப்படவில்லை",
    weight_not_set: "எடை பதிவு செய்யப்படவில்லை",
    height: "உயரம்",
    weight: "எடை",
    lang_en: "ஆங்கிலம்",
    lang_hi: "இந்தி",
    lang_bn: "வங்காளம்",
    lang_ta: "தமிழ்",
    lang_te: "தெலுங்கு",
    lang_mr: "மராத்தி",
    lang_gu: "குஜராத்தி",
    lang_kn: "கன்னடம்",
    lang_ml: "மலையாளம்",
    lang_pa: "பஞ்சாபி",

    // Dates & Times
    today: "இன்று",
    yesterday: "நேற்று",
    tomorrow: "நாளை",
    last_updated: "கடைசியாக புதுப்பிக்கப்பட்டது",
    previous: "முந்தைய",
    context: "சூழல்",
    fasting: "வெறும் வயிற்றில் (Fasting)",
    post_meal: "உணவுக்குப் பின் (Post-meal)",
    random: "வழக்கமான (Random)",
    no_data: "தரவு எதுவும் இல்லை",
    no_readings_yet: "அளவீடுகள் எதுவும் இல்லை",
    current_reading: "தற்போதைய அளவீடு",

    // Vitals & Classification
    blood_pressure_label: "இரத்த அழுத்தம் (BP)",
    blood_sugar_label: "இரத்த சர்க்கரை",
    heart_rate_label: "இதயத் துடிப்பு",
    usual_range: "வழக்கமான வரம்பு",
    recorded: "பதிவு செய்யப்பட்டது",
    high: "அதிகம்",
    low: "குறைவு",
    stable: "நிலையானது",
    higher_than_last: "முந்தைய விட அதிகம்",
    lower_than_last: "முந்தைய விட குறைவு",

    // Reminders & Routine
    daily_health_routine: "தினசரி சுகாதார நினைவூட்டல்கள் & வழக்கம்",
    medicine_reminders: "மருந்து நினைவூட்டல்கள்",
    prescriptions_doses: "மருந்துகள் & திட்டமிடப்பட்ட அளவுகள்",
    active: "செயலில்",
    taken: "எடுத்துக்கொள்ளப்பட்டது",
    take_dose: "மருந்தை உட்கொள்ளவும்",
    no_meds_scheduled: "இன்று மருந்துகள் எதுவும் திட்டமிடப்படவில்லை.",
    upload_rx_import: "மருந்துகளைச் சேர்க்க சீட்டை பதிவேற்றவும் →",
    track_logs_reminders: "நினைவூட்டல் பதிவுகளைக் கண்காணிக்கவும்",
    manage_reminders: "அனைத்து நினைவூட்டல்களையும் நிர்வகிக்கவும் →",

    // Yoga
    todays_yoga: "இன்றைய யோகா அட்டவணை",
    yoga_subtitle: "மருத்துவர் பரிந்துரைத்த & AI நிலைப் பயிற்சி",
    done: "முடிந்தது",
    check_pose: "நிலையை சரிபார்க்கவும்",
    mark_done: "முடிந்ததாகக் குறிக்கவும்",
    body_pointer_hint: "உடல் சுட்டி வழிகாட்டுதலுடன் நிலையை பிடிக்கவும்",
    full_yoga_routine: "முழு யோகா அட்டவணை →",
    daily: "தினசரி",
    morning: "காலை",
    evening: "மாலை",
    min: "நிமிடம்",

    // Personalized Nutrition & BMI
    nutrition_needs: "தனிப்பயனாக்கப்பட்ட ஊட்டச்சத்து & கலோரி தேவைகள்",
    nutrition_subtitle: "உயரம், எடை மற்றும் பிஎம்ஐ அடிப்படையில் கணக்கிடப்பட்டது",
    bmi_label: "உடல் நிறை குறியீட்டெண் (BMI)",
    normal_weight: "சாதாரண எடை",
    underweight: "குறைந்த எடை",
    overweight: "அதிக எடை",
    obese: "உடல் பருமன்",
    target_calories: "தினசரி இலக்கு கலோரிகள்",
    kcal_day: "கிலோ கலோரி / நாள்",
    clinical_goal: "மருத்துவ இலக்கு",
    goal_maintenance: "உகந்த பராமரிப்பு & புத்துணர்ச்சி",
    goal_surplus: "கலோரி அதிகரிப்பு & தசை வளர்ச்சி",
    goal_balanced: "சமச்சீர் பராமரிப்பு & வளர்சிதை மாற்ற ஆரோக்கியம்",
    goal_deficit: "மிதமான குறைப்பு & கொழுப்பு இழப்பு",
    goal_reset: "வளர்சிதை மாற்ற மீட்டமைப்பு & வீக்கத்தைக் குறைக்கும் உணவு",
    hydration_fiber: "தினசரி நீர் & நார்ச்சத்து",
    water_intake: "தண்ணீர் உட்கொள்ளல்",
    dietary_fiber: "உணவு நார்ச்சத்து",
    macronutrient_split: "மேக்ரோநியூட்ரியண்ட் இலக்கு பிரிவு (உடல் அமைப்பின்படி):",
    protein: "புரதம்",
    protein_desc: "தசை பழுதுபார்ப்பு & ஆற்றல் நிலைத்தன்மை",
    complex_carbs: "கூட்டு மாவுச்சத்துக்கள்",
    carbs_desc: "முழு தானியங்கள், பருப்புகள் & நீண்ட ஆற்றல்",
    healthy_fats: "ஆரோக்கியமான கொழுப்புகள்",
    fats_desc: "ஹார்மோன் உற்பத்தி & மூட்டுகளின் ஆரோக்கியம்",
    key_micronutrients: "உங்கள் பிஎம்ஐ-க்கு தேவையான முக்கிய நுண் ஊட்டச்சத்துக்கள்:",
    height_weight_prompt_title: "ஊட்டச்சத்தை கணக்கிட உயரம் & எடையைப் பதிவு செய்யவும்",
    height_weight_prompt_desc: "துல்லியமான பிஎம்ஐ (BMI), தினசரி கலோரி இலக்கு மற்றும் ஊட்டச்சத்து விவரங்களைப் பெற சுயவிவரத்தில் உயரம் மற்றும் எடையை உள்ளிடவும்.",
    enter_height_weight_btn: "சுயவிவரத்தில் உயரம் மற்றும் எடையைப் பதிவு செய் →",

    // Clinical Summary
    clinical_summary: "தற்போதைய மருத்துவ சுருக்கம்",
    latest_diagnosis: "சமீபத்திய நோயறிதல்",
    recent_concern: "சமீபத்திய கவலை",
    no_clinical_summary: "மருத்துவ சுருக்கம் இல்லை. உருவாக்க உங்கள் மருத்துவ வரலாற்றைப் பதிவு செய்யவும்.",

    // Quick Action Subtitles
    chat_subtitle_short: "மருத்துவக் கேள்வியைக் கேளுங்கள்",
    exercise_desc: "தினசரி சரிபார்ப்பு பட்டியல் & AI யோகா பயிற்சி",
    record_history_desc: "குரல் அல்லது உரை மூலம் பதிலளிக்கவும்",
    upload_docs_desc: "மருந்து சீட்டு அல்லது ஆய்வக அறிக்கையைச் சேர்க்கவும்",
    tracker_desc: "இரத்த அழுத்தம், சர்க்கரை & முக்கிய அளவீடுகள்",
    reminders_desc: "மருந்து மற்றும் வாழ்க்கை முறை நினைவூட்டல்களை அமைக்கவும்",

    // Lists & Appointments
    recent_medical_history: "சமீபத்திய மருத்துவ வரலாறு",
    no_medical_history: "மருத்துவ வரலாறு எதுவும் இதுவரை பதிவு செய்யப்படவில்லை.",
    recent_health_readings: "சமீபத்திய சுகாதார அளவீடுகள்",
    no_health_readings: "சுகாதார அளவீடுகள் எதுவும் கிடைக்கவில்லை.",
    upcoming_appointments: "வரவிருக்கும் மருத்துவர் சந்திப்புகள்",
    doctor: "மருத்துவர்",
    status_booked: "பதிவு செய்யப்பட்டது",
    status_in_progress: "ஆலோசனை நடக்கிறது",
    status_completed: "முடிந்தது",
    status_cancelled: "ரத்து செய்யப்பட்டது",
  },

  te: {
    care: "వైద్య సేవలు",
    dashboard: "డ్యాష్‌బోర్డ్",
    medical_records: "వైద్య రికార్డులు",
    ai_health_assistant: "AI ఆరోగ్య సహాయకుడు",
    upload_documents: "పత్రాల అప్‌లోడ్",
    book_appointment: "అపాయింట్‌మెంట్ బుక్ చేయండి",
    daily_routine: "రోజువారీ దినచర్య",
    health_tracker: "ఆరోగ్య ట్రాకర్",
    exercise_yoga: "వ్యాయామం & యోగా",
    ayurvedic_care: "ఆయుర్వేద సంరక్షణ",
    reminders: "మందుల రిమైండర్లు",
    account: "ఖాతా",
    profile: "ప్రొఫైల్",
    patient_workspace: "రోగి కార్యస్థలం",
    signed_in: "లాగిన్ అయ్యారు",
    logout: "లాగ్ అవుట్",
    menu: "మెనూ",
    high_contrast: "అధిక కాంట్రాస్ట్",
    standard_view: "సాధారణ వీక్షణ",
    language: "భాష",
    select_language: "భాషను ఎంచుకోండి",
    welcome_back: "స్వాగతం",
    hello: "నమస్కారం",
    health_overview: "మీ సంపూర్ణ ఆరోగ్య చరిత్ర — నివేదికలు మరియు ప్రిస్క్రిప్షన్లు.",
    quick_actions: "శీఘ్ర చర్యలు",
    talk_to_ai: "AI సహాయకుడితో మాట్లాడండి",
    record_history: "చరిత్రను నమోదు చేయండి",
    view_records: "రికార్డులను చూడండి",
    vitals_summary: "ముఖ్య సంకేతాలు",
    heart_rate: "గుండె వేగం",
    blood_pressure: "రక్తపోటు (BP)",
    blood_glucose: "బ్లడ్ షుగర్",
    bmi_weight: "BMI & బరువు",
    spo2: "ఆక్సిజన్ (SpO2)",
    recent_prescriptions: "ఇటీవలి ప్రిస్క్రిప్షన్లు",
    upcoming_appointments: "రాబోయే అపాయింట్‌మెంట్లు",
    no_prescriptions: "ఇంకా ప్రిస్క్రిప్షన్లు లేవు",
    no_appointments: "రాబోయే అపాయింట్‌మెంట్లు లేవు",
    chat_title: "AI ఆరోగ్య సహాయకుడు",
    chat_subtitle: "మీ ప్రిస్క్రిప్షన్లు, లక్షణాలు మరియు ఆయుర్వేద చిట్కాల గురించి అడగండి.",
    new_chat: "+ కొత్త సంభాషణ",
    conversations: "సంభాషణలు",
    type_message: "మీ భాషలో ఆరోగ్య ప్రశ్నను అడగండి…",
    send: "పంపండి",
    thinking: "AI ఆలోచిస్తోంది…",
    chat_disclaimer: "AI కేవలం మార్గదర్శకత్వం మాత్రమే ఇస్తుంది. అత్యవసర పరిస్థితిలో ఆసుపత్రికి వెళ్లండి.",
    emergency_detected: "అత్యవసర లక్షణాలు గుర్తించబడ్డాయి. తక్షణ వైద్య సహాయం తీసుకోండి.",
    suggestion_rx: "నా ప్రిస్క్రిప్షన్‌ను సులభంగా వివరించండి",
    suggestion_remedies: "జలుబు మరియు దగ్గుకు ఆయుర్వేద చిట్కాలు",
    suggestion_exercise: "నా కోసం సురక్షితమైన యోగాసనాలను సూచించండి",
    suggestion_diet: "నేను ఈ రోజు ఎలాంటి ఆరోగ్యకరమైన ఆహారం తీసుకోవాలి?",
    no_previous_chats: "గత సంభాషణలు లేవు",
    start_first_chat: "AI ఆరోగ్య సహచరుడితో మొదటి సంభాషణను ప్రారంభించండి.",
    records_title: "వైద్య రికార్డులు",
    records_subtitle: "మీ పూర్తి ఆరోగ్య చరిత్ర — సెషన్లు, నివేదికలు మరియు అప్‌లోడ్‌లు.",
    add_medical_data: "డేటాను జోడించండి",
    record_new_history: "కొత్త చరిత్రను నమోదు చేయండి",
    upload_a_document: "పత్రాన్ని అప్‌లోడ్ చేయండి",
    view_read_rx: "ప్రిస్క్రిప్షన్ చూడండి & చదవండి",
    download_print_pdf: "PDF డౌన్‌లోడ్ / ప్రింట్",
    official_rx: "అధికారిక ప్రిస్క్రిప్షన్",
    lab_report: "ల్యాబ్ నివేదిక",
    history_session: "చరిత్ర సెషన్",
    prescribed_by: "సూచించిన డాక్టర్",
    medicines: "మందులు",
    advice: "సలహా",
    yoga_lifestyle: "యోగా / జీవనశైలి",
    view_document: "పత్రం చూడండి →",
    view_full_history: "పూర్తి చరిత్ర →",
    continue_recording: "కొనసాగించండి →",
    no_records: "ఇంకా రికార్డులు లేవు.",
    save: "భద్రపరచు",
    cancel: "రద్దు చేయి",
    close: "మూసివేయి",
    loading: "లోడ్ అవుతోంది…",
    error: "లోపం",
    retry: "మళ్ళీ ప్రయత్నించండి",
    back: "వెనుకకు",
    next: "తరువాత",
    submit: "సమర్పించండి",
    start: "ప్రారంభించండి",
    save_changes: "మార్పులను భద్రపరచండి",

    // Demographic & Profile
    yrs: "సంవత్సరాలు",
    gender_male: "పురుషుడు",
    gender_female: "స్త్రీ",
    gender_other: "ఇతర",
    patient: "రోగి",
    age_not_set: "వయస్సు నమోదు కాలేదు",
    gender_not_set: "లింగం నమోదు కాలేదు",
    height_not_set: "ఎత్తు నమోదు కాలేదు",
    weight_not_set: "బరువు నమోదు కాలేదు",
    height: "ఎత్తు",
    weight: "బరువు",
    lang_en: "ఇంగ్లీష్",
    lang_hi: "హిందీ",
    lang_bn: "బెంగాలీ",
    lang_ta: "తమిళం",
    lang_te: "తెలుగు",
    lang_mr: "మరాఠీ",
    lang_gu: "గుజరాతీ",
    lang_kn: "కన్నడ",
    lang_ml: "మలయాళం",
    lang_pa: "పంజాబీ",

    // Dates & Times
    today: "ఈరోజు",
    yesterday: "నిన్న",
    tomorrow: "రేపు",
    last_updated: "చివరిగా అప్‌డేట్ చేసినది",
    previous: "మునుపటి",
    context: "సందర్భం",
    fasting: "ఖాళీ కడుపుతో (Fasting)",
    post_meal: "భోజనం తర్వాత (Post-meal)",
    random: "సాధారణ (Random)",
    no_data: "డేటా లేదు",
    no_readings_yet: "ఇంకా రీడింగ్‌లు లేవు",
    current_reading: "ప్రస్తుత రీడింగ్",

    // Vitals & Classification
    blood_pressure_label: "రక్తపోటు (BP)",
    blood_sugar_label: "బ్లడ్ షుగర్",
    heart_rate_label: "గుండె వేగం",
    usual_range: "సాధారణ పరిధి",
    recorded: "నమోదైనది",
    high: "అధికం",
    low: "తక్కువ",
    stable: "స్థిరంగా ఉంది",
    higher_than_last: "గత సారి కంటే ఎక్కువ",
    lower_than_last: "గత సారి కంటే తక్కువ",

    // Reminders & Routine
    daily_health_routine: "రోజువారీ ఆరోగ్య రిమైండర్‌లు & దినచర్య",
    medicine_reminders: "మందుల రిమైండర్‌లు",
    prescriptions_doses: "ప్రిస్క్రిప్షన్లు & మోతాదులు",
    active: "క్రియాశీలం",
    taken: "తీసుకున్నారు",
    take_dose: "మోతాదు తీసుకోండి",
    no_meds_scheduled: "ఈరోజు ఎలాంటి మందులు షెడ్యూల్ చేయబడలేదు.",
    upload_rx_import: "మందులను జోడించడానికి ప్రిస్క్రిప్షన్ అప్‌లోడ్ చేయండి →",
    track_logs_reminders: "రిమైండర్లలో లాగ్‌లను ట్రాక్ చేయండి",
    manage_reminders: "అన్ని రిమైండర్‌లను నిర్వహించండి →",

    // Yoga
    todays_yoga: "నేటి యోగా షెడ్యూల్",
    yoga_subtitle: "వైద్యులు సూచించిన & AI భంగిమ కోచ్",
    done: "పూర్తయింది",
    check_pose: "భంగిమను తనిఖీ చేయండి",
    mark_done: "పూర్తయినట్లు గుర్తించండి",
    body_pointer_hint: "బాడీ పాయింటర్ సూచనలతో భంగిమను పాటించండి",
    full_yoga_routine: "పూర్తి యోగా దినచర్య →",
    daily: "రోజువారీ",
    morning: "ఉదయం",
    evening: "సాయంత్రం",
    min: "నిమిషాలు",

    // Personalized Nutrition & BMI
    nutrition_needs: "వ్యక్తిగత పోషకాహారం & కేలరీల అవసరాలు",
    nutrition_subtitle: "ఎత్తు, బరువు & BMI ఆధారంగా లెక్కించబడింది",
    bmi_label: "బాడీ మాస్ ఇండెక్స్ (BMI)",
    normal_weight: "సాధారణ బరువు",
    underweight: "తక్కువ బరువు",
    overweight: "అధిక బరువు",
    obese: "స్థూలకాయం",
    target_calories: "రోజువారీ లక్ష్య కేలరీలు",
    kcal_day: "కిలో కేలరీలు / రోజు",
    clinical_goal: "వైద్య లక్ష్యం",
    goal_maintenance: "సరైన సంరక్షణ & ఉత్తేజం",
    goal_surplus: "కేలరీల పెరుగుదల & కండరాల నిర్మాణం",
    goal_balanced: "సమతుల్య నిర్వహణ & జీవక్రియ ఆరోగ్యం",
    goal_deficit: "మితమైన లోటు & కొవ్వు తగ్గింపు",
    goal_reset: "జీవక్రియ రీసెట్ & వాపు నిరోధక ఆహారం",
    hydration_fiber: "రోజువారీ నీరు & ఫైబర్",
    water_intake: "నీరు తీసుకోవడం",
    dietary_fiber: "ఆహార పీచు (ఫైబర్)",
    macronutrient_split: "మాక్రోన్యూట్రియెంట్ లక్ష్య విభజన (శరీర నిర్మాణం ఆధారంగా):",
    protein: "ప్రోటీన్",
    protein_desc: "కండరాల మరమ్మత్తు & జీవక్రియ సంతృప్తి",
    complex_carbs: "కాంప్లెక్స్ పిండి పదార్థాలు",
    carbs_desc: "ధాన్యాలు, పప్పులు & దీర్ఘకాలిక శక్తి",
    healthy_fats: "ఆరోగ్యకరమైన కొవ్వులు",
    fats_desc: "హార్మోన్ల ఉత్పత్తి & కీళ్ల ఆరోగ్యం",
    key_micronutrients: "మీ BMI ప్రొఫైల్ కోసం అవసరమైన ప్రధాన సూక్ష్మ పోషకాలు:",
    height_weight_prompt_title: "పోషణను లెక్కించడానికి ఎత్తు మరియు బరువు నమోదు చేయండి",
    height_weight_prompt_desc: "ఖచ్చితమైన BMI, రోజువారీ కేలరీల లక్ష్యం మరియు పోషకాల వివరాలను చూడటానికి ప్రొఫైల్‌లో మీ ఎత్తు మరియు బరువును నమోదు చేయండి.",
    enter_height_weight_btn: "ప్రొఫైల్‌లో ఎత్తు & బరువు నమోదు చేయండి →",

    // Clinical Summary
    clinical_summary: "ప్రస్తుత క్లినికల్ సారాంశం",
    latest_diagnosis: "తాజా రోగ నిర్ధారణ",
    recent_concern: "ఇటీవలి ఆందోళన",
    no_clinical_summary: "ఇంకా క్లినికల్ సారాంశం లేదు. దీనిని నిర్మించడానికి వైద్య చరిత్రను నమోదు చేయండి.",

    // Quick Action Subtitles
    chat_subtitle_short: "వైద్యపరమైన ప్రశ్న అడగండి",
    exercise_desc: "రోజువారీ చెక్‌లిస్ట్ & AI యోగా కోచ్",
    record_history_desc: "వాయిస్ లేదా టెక్స్ట్ ద్వారా సమాధానం ఇవ్వండి",
    upload_docs_desc: "ప్రిస్క్రిప్షన్ లేదా ల్యాబ్ రిపోర్ట్ జోడించండి",
    tracker_desc: "రక్తపోటు, షుగర్ & ప్రాణాధార సంకేతాలు",
    reminders_desc: "మందులు మరియు జీవనశైలి అలారాలను సెట్ చేయండి",

    // Lists & Appointments
    recent_medical_history: "ఇటీవలి వైద్య చరిత్ర",
    no_medical_history: "ఇంతవరకు ఎలాంటి వైద్య చరిత్ర నమోదు కాలేదు.",
    recent_health_readings: "ఇటీవలి ఆరోగ్య రీడింగ్‌లు",
    no_health_readings: "ఇంకా ఆరోగ్య రీడింగ్‌లు అందుబాటులో లేవు.",
    upcoming_appointments: "రాబోయే డాక్టర్ అపాయింట్‌మెంట్‌లు",
    doctor: "డాక్టర్",
    status_booked: "బుక్ చేయబడింది",
    status_in_progress: "సంప్రదింపులు జరుగుతున్నాయి",
    status_completed: "పూర్తయింది",
    status_cancelled: "రద్దు చేయబడింది",
  },

  mr: {
    care: "आरोग्य सेवा",
    dashboard: "डॅशबोर्ड",
    medical_records: "वैद्यकीय नोंदी",
    ai_health_assistant: "एआय आरोग्य सहाय्यक",
    upload_documents: "कागदपत्रे अपलोड",
    book_appointment: "अपॉइंटमेंट बुक करा",
    daily_routine: "दैनंदिन दिनचर्या",
    health_tracker: "आरोग्य ट्रॅकर",
    exercise_yoga: "व्यायाम आणि योग",
    ayurvedic_care: "आयुर्वेदिक काळजी",
    reminders: "औषध स्मरणपत्रे",
    account: "खाते",
    profile: "प्रोफाइल",
    patient_workspace: "रुग्ण कक्ष",
    signed_in: "साइन इन आहात",
    logout: "लॉगआउट",
    menu: "मेनू",
    high_contrast: "उच्च कॉन्ट्रास्ट",
    standard_view: "सामान्य दृश्य",
    language: "भाषा",
    select_language: "भाषा निवडा",
    welcome_back: "पुन्हा स्वागत आहे",
    hello: "नमस्कार",
    health_overview: "तुमचा संपूर्ण आरोग्य इतिहास — सत्रे, अहवाल आणि प्रिस्क्रिप्शन.",
    quick_actions: "जलद कृती",
    talk_to_ai: "एआय सहाय्यकाशी बोला",
    record_history: "इतिहास नोंदवा",
    view_records: "नोंदी पहा",
    vitals_summary: "महत्त्वपूर्ण चिन्हे",
    heart_rate: "हृदयाचे ठोके",
    blood_pressure: "रक्तदाब (BP)",
    blood_glucose: "ब्लड शुगर",
    bmi_weight: "बीएमआय आणि वजन",
    spo2: "ऑक्सिजन (SpO2)",
    recent_prescriptions: "अलीकडील औषधोपचार",
    upcoming_appointments: "आगामी अपॉइंटमेंट्स",
    no_prescriptions: "अद्याप कोणतीही औषधोपचार नोंद नाही",
    no_appointments: "कोणत्याही आगामी अपॉइंटमेंट्स नाहीत",
    chat_title: "एआय आरोग्य सहाय्यक",
    chat_subtitle: "तुमची औषधे, लक्षणे आणि आयुर्वेदिक टिप्सबद्दल विचारा.",
    new_chat: "+ नवीन संभाषण",
    conversations: "संभाषणे",
    type_message: "तुमच्या भाषेत आरोग्याशी संबंधित प्रश्न विचारा…",
    send: "पाठवा",
    thinking: "एआय विचार करत आहे…",
    chat_disclaimer: "एआय सहाय्यक केवळ मार्गदर्शन करतो, वैद्यकीय निदान नाही. आणीबाणीत तात्काळ डॉक्टरांशी संपर्क साधा.",
    emergency_detected: "तातडीची लक्षणे आढळली. कृपया ताबडतोब वैद्यकीय मदत घ्या.",
    suggestion_rx: "माझे प्रिस्क्रिप्शन सोप्या भाषेत समजावून सांगा",
    suggestion_remedies: "सर्दी आणि खोकल्यासाठी आयुर्वेदिक घरगुती उपाय",
    suggestion_exercise: "माझ्यासाठी सकाळचे सुरक्षित योगासने सुचवा",
    suggestion_diet: "निरोगी राहण्यासाठी मी आज काय खावे?",
    no_previous_chats: "मागील संभाषणे नाहीत",
    start_first_chat: "तुमच्या एआय आरोग्य साथीदारासोबत पहिले संभाषण सुरू करा.",
    records_title: "वैद्यकीय नोंदी",
    records_subtitle: "तुमचा संपूर्ण वैद्यकीय इतिहास — सत्रे, अहवाल आणि अपलोड.",
    add_medical_data: "वैद्यकीय माहिती जोडा",
    record_new_history: "नवीन इतिहास नोंदवा",
    upload_a_document: "दस्तऐवज अपलोड करा",
    view_read_rx: "प्रिस्क्रिप्शन पहा आणि वाचा",
    download_print_pdf: "पीडीएफ डाउनलोड / प्रिंट",
    official_rx: "अधिकृत प्रिस्क्रिप्शन",
    lab_report: "लॅब अहवाल",
    history_session: "इतिहास सत्र",
    prescribed_by: "डॉक्टर",
    medicines: "औषधे",
    advice: "सल्ला",
    yoga_lifestyle: "योग / जीवनशैली",
    view_document: "कागदपत्र पहा →",
    view_full_history: "पूर्ण इतिहास →",
    continue_recording: "नोंद सुरू ठेवा →",
    no_records: "अद्याप कोणत्याही नोंदी नाहीत.",
    save: "जतन करा",
    cancel: "रद्द करा",
    close: "बंद करा",
    loading: "लोड होत आहे…",
    error: "त्रुटी",
    retry: "पुन्हा प्रयत्न करा",
    back: "मागे",
    next: "पुढे",
    submit: "सादर करा",
    start: "सुरू करा",
    save_changes: "बदल जतन करा",

    // Demographic & Profile
    yrs: "वर्षे",
    gender_male: "पुरुष",
    gender_female: "महिला",
    gender_other: "इतर",
    patient: "रुग्ण",
    age_not_set: "वय नोंदवले नाही",
    gender_not_set: "लिंग नोंदवले नाही",
    height_not_set: "उंची नोंदवली नाही",
    weight_not_set: "वजन नोंदवले नाही",
    height: "उंची",
    weight: "वजन",
    lang_en: "इंग्रजी",
    lang_hi: "हिंदी",
    lang_bn: "बंगाली",
    lang_ta: "तमिळ",
    lang_te: "तेलुगू",
    lang_mr: "मराठी",
    lang_gu: "गुजराती",
    lang_kn: "कन्नड",
    lang_ml: "मल्याळम",
    lang_pa: "पंजाबी",

    // Dates & Times
    today: "आज",
    yesterday: "काल",
    tomorrow: "उद्या",
    last_updated: "शेवटचे अपडेट",
    previous: "मागील",
    context: "संदर्भ",
    fasting: "उपाशी पोटी (Fasting)",
    post_meal: "जेवणानंतर (Post-meal)",
    random: "सामान्य (Random)",
    no_data: "माहिती उपलब्ध नाही",
    no_readings_yet: "अद्याप कोणतीही नोंद नाही",
    current_reading: "सध्याची नोंद",

    // Vitals & Classification
    blood_pressure_label: "रक्तदाब (BP)",
    blood_sugar_label: "ब्लड शुगर",
    heart_rate_label: "हृदयाचे ठोके",
    usual_range: "सामान्य मर्यादा",
    recorded: "नोंदवले",
    high: "उच्च",
    low: "कमी",
    stable: "स्थिर",
    higher_than_last: "मागील वेळेपेक्षा जास्त",
    lower_than_last: "मागील वेळेपेक्षा कमी",

    // Reminders & Routine
    daily_health_routine: "दैनंदिन आरोग्य स्मरणपत्रे आणि दिनचर्या",
    medicine_reminders: "औषध स्मरणपत्रे",
    prescriptions_doses: "प्रिस्क्रिप्शन आणि नियोजित डोस",
    active: "सक्रिय",
    taken: "घेतले",
    take_dose: "डोस घ्या",
    no_meds_scheduled: "आजसाठी कोणतीही औषधे नियोजित नाहीत.",
    upload_rx_import: "औषधे आयात करण्यासाठी प्रिस्क्रिप्शन अपलोड करा →",
    track_logs_reminders: "स्मरणपत्रांमध्ये नोंदी पहा",
    manage_reminders: "सर्व स्मरणपत्रे व्यवस्थापित करा →",

    // Yoga
    todays_yoga: "आजची योगासने",
    yoga_subtitle: "डॉक्टरांनी शिफारस केलेले आणि एआय योग प्रशिक्षक",
    done: "पूर्ण",
    check_pose: "मुद्रा तपासा",
    mark_done: "पूर्ण म्हणून चिन्हांकित करा",
    body_pointer_hint: "बॉडी पॉईंटर सूचनेनुसार मुद्रा धरा",
    full_yoga_routine: "पूर्ण योग दिनचर्या →",
    daily: "दररोज",
    morning: "सकाळ",
    evening: "संध्याकाळ",
    min: "मिनिटे",

    // Personalized Nutrition & BMI
    nutrition_needs: "वैयक्तिक पोषण आणि कॅलरी गरजा",
    nutrition_subtitle: "उंची, वजन आणि बीएमआय वरून गणना केली",
    bmi_label: "बॉडी मास इंडेक्स (BMI)",
    normal_weight: "सामान्य वजन",
    underweight: "कमी वजन",
    overweight: "जास्त वजन",
    obese: "लठ्ठपणा",
    target_calories: "दैनिक लक्ष्य कॅलरी",
    kcal_day: "किलो कॅलरी / दिवस",
    clinical_goal: "वैद्यकीय ध्येय",
    goal_maintenance: "उत्तम देखभाल आणि चैतन्य",
    goal_surplus: "कॅलरी वाढ आणि स्नायूंची बांधणी",
    goal_balanced: "संतुलित देखभाल आणि चयापचय आरोग्य",
    goal_deficit: "मध्यम तूट आणि चरबी कमी करणे",
    goal_reset: "मेटाबॉलिक रीसेट आणि दाहक-विरोधी आहार",
    hydration_fiber: "दररोज पाणी आणि फायबर",
    water_intake: "पाणी पिण्याचे प्रमाण",
    dietary_fiber: "आहारातील फायबर",
    macronutrient_split: "मॅक्रोन्युट्रिएंट लक्ष्य विभाजन (शारीरिक रचनेनुसार):",
    protein: "प्रथिने (Protein)",
    protein_desc: "स्नायूंची दुरुस्ती आणि तृप्ती",
    complex_carbs: "कॉम्प्लेक्स कार्ब्स",
    carbs_desc: "तृणधान्ये, डाळी आणि दीर्घकाळ टिकणारी ऊर्जा",
    healthy_fats: "निरोगी चरबी",
    fats_desc: "हार्मोन निर्मिती आणि सांध्यांचे आरोग्य",
    key_micronutrients: "तुमच्या बीएमआय प्रोफाइलसाठी आवश्यक प्रमुख सूक्ष्म पोषक घटक:",
    height_weight_prompt_title: "पोषणाची गणना करण्यासाठी उंची व वजन नोंदवा",
    height_weight_prompt_desc: "तुमचा अचूक बीएमआय (BMI), दैनंदिन कॅलरी लक्ष्य आणि पोषक तत्वांची यादी पाहण्यासाठी प्रोफाइलमध्ये उंची आणि वजन प्रविष्ट करा.",
    enter_height_weight_btn: "प्रोफाइलमध्ये उंची आणि वजन प्रविष्ट करा →",

    // Clinical Summary
    clinical_summary: "सध्याचा वैद्यकीय सारांश",
    latest_diagnosis: "नवीनतम निदान",
    recent_concern: "अलीकडील समस्या",
    no_clinical_summary: "अद्याप कोणताही सारांश नाही. तो तयार करण्यासाठी वैद्यकीय इतिहास नोंदवा.",

    // Quick Action Subtitles
    chat_subtitle_short: "वैद्यकीय प्रश्न विचारा",
    exercise_desc: "दैनंदिन चेकलिस्ट आणि योग प्रशिक्षक",
    record_history_desc: "आवाज किंवा मजकुराद्वारे उत्तरे द्या",
    upload_docs_desc: "प्रिस्क्रिप्शन किंवा लॅब रिपोर्ट जोडा",
    tracker_desc: "रक्तदाब, साखर आणि महत्त्वपूर्ण चिन्हे",
    reminders_desc: "औषध आणि जीवनशैलीचे अलार्म सेट करा",

    // Lists & Appointments
    recent_medical_history: "अलीकडील वैद्यकीय इतिहास",
    no_medical_history: "अद्याप कोणताही वैद्यकीय इतिहास नोंदवलेला नाही.",
    recent_health_readings: "अलीकडील आरोग्य नोंदी",
    no_health_readings: "अद्याप कोणत्याही नोंदी उपलब्ध नाहीत.",
    upcoming_appointments: "आगामी डॉक्टरांच्या भेटी",
    doctor: "डॉक्टर",
    status_booked: "बुक केले",
    status_in_progress: "सल्लामसलत सुरू आहे",
    status_completed: "पूर्ण झाले",
    status_cancelled: "रद्द केले",
  },

  gu: {
    care: "આરોગ્ય સંભાળ",
    dashboard: "ડૅશબોર્ડ",
    medical_records: "મેડિકલ રેકોર્ડ્સ",
    ai_health_assistant: "AI આરોગ્ય સહાયક",
    upload_documents: "દસ્તાવેજ અપલોડ",
    book_appointment: "એપોઇન્ટમેન્ટ બુક કરો",
    daily_routine: "દૈનિક દિનચર્યા",
    health_tracker: "હેલ્થ ટ્રેકર",
    exercise_yoga: "કસરત અને યોગ",
    ayurvedic_care: "આયુર્વેદિક સંભાળ",
    reminders: "દવા રીમાઇન્ડર્સ",
    account: "ખાતું",
    profile: "પ્રોફાઇલ",
    patient_workspace: "દર્દી પોર્ટલ",
    signed_in: "લૉગ ઇન છો",
    logout: "લૉગ આઉટ",
    menu: "મેનુ",
    high_contrast: "હાઇ કોન્ટ્રાસ્ટ",
    standard_view: "સામાન્ય દૃશ્ય",
    language: "ભાષા",
    select_language: "ભાષા પસંદ કરો",
    welcome_back: "સ્વાગત છે",
    hello: "નમસ્તે",
    health_overview: "તમારો સંપૂર્ણ આરોગ્ય ઇતિહાસ — સત્રો, અહેવાલો અને પ્રિસ્ક્રિપ્શન્સ.",
    quick_actions: "ઝડપી ક્રિયાઓ",
    talk_to_ai: "AI સહાયક સાથે વાત કરો",
    record_history: "ઇતિહાસ રેકોર્ડ કરો",
    view_records: "રેકોર્ડ જુઓ",
    vitals_summary: "વાઇટલ્સ સારાંશ",
    heart_rate: "હૃદયના ધબકારા",
    blood_pressure: "બ્લડ પ્રેશર (BP)",
    blood_glucose: "બ્લડ સુગર",
    bmi_weight: "BMI અને વજન",
    spo2: "ઓક્સિજન (SpO2)",
    recent_prescriptions: "તાજેતરના પ્રિસ્ક્રિપ્શન્સ",
    upcoming_appointments: "આગામી એપોઇન્ટમેન્ટ્સ",
    no_prescriptions: "હજી કોઈ પ્રિસ્ક્રિપ્શન નથી",
    no_appointments: "કોઈ આગામી એપોઇન્ટમેન્ટ નથી",
    chat_title: "AI આરોગ્ય સહાયક",
    chat_subtitle: "તમારી દવાઓ, લક્ષણો અને આયુર્વેદિક ઉપચાર વિશે પૂછો.",
    new_chat: "+ નવી વાતચીત",
    conversations: "વાતચીત",
    type_message: "તમારી ભાષામાં પ્રશ્ન પૂછો…",
    send: "મોકલો",
    thinking: "AI વિચારી રહ્યું છે…",
    chat_disclaimer: "AI સહાયક માત્ર માર્ગદર્શન આપે છે, ડૉક્ટરનો વિકલ્પ નથી.",
    emergency_detected: "ઇમરજન્સી લક્ષણો જણાયા છે. કૃપા કરીને તાત્કાલિક સારવાર લો.",
    suggestion_rx: "મારું પ્રિસ્ક્રિપ્શન સરળ ભાષામાં સમજાવો",
    suggestion_remedies: "ખાંસી અને શરદી માટે આયુર્વેદિક ઘરેલું ઉપાય",
    suggestion_exercise: "મારા માટે સલામત સવારના યોગાસનો જણાવો",
    suggestion_diet: "આજે તંદુરસ્ત રહેવા માટે મારે શું ખાવું જોઈએ?",
    no_previous_chats: "કોઈ અગાઉની ચેટ નથી",
    start_first_chat: "તમારા AI સાથી સાથે વાતચીત શરૂ કરો.",
    records_title: "મેડિકલ રેકોર્ડ્સ",
    records_subtitle: "તમારો સંપૂર્ણ આરોગ્ય ઇતિહાસ.",
    add_medical_data: "ડેટા ઉમેરો",
    record_new_history: "નવો ઇતિહાસ નોંધો",
    upload_a_document: "દસ્તાવેજ અપલોડ કરો",
    view_read_rx: "પ્રિસ્ક્રિપ્શન વાંચો",
    download_print_pdf: "PDF ડાઉનલોડ / પ્રિન્ટ",
    official_rx: "અધિકૃત પ્રિસ્ક્રિપ્શન",
    lab_report: "લેબ રિપોર્ટ",
    history_session: "ઇતિહાસ સત્ર",
    prescribed_by: "તબીબ",
    medicines: "દવાઓ",
    advice: "સલાહ",
    yoga_lifestyle: "યોગ / જીવનશૈલી",
    view_document: "દસ્તાવેજ જુઓ →",
    view_full_history: "સંપૂર્ણ ઇતિહાસ →",
    continue_recording: "ચાલુ રાખો →",
    no_records: "કોઈ રેકોર્ડ મળ્યો નથી.",
    save: "સાચવો",
    cancel: "રદ કરો",
    close: "બંધ કરો",
    loading: "લોડ થઈ રહ્યું છે…",
    error: "ભૂલ",
    retry: "ફરી પ્રયાસ કરો",
    back: "પાછા",
    next: "આગળ",
    submit: "સબમિટ કરો",
    start: "શરૂ કરો",
    save_changes: "ફેરફારો સાચવો",

    // Demographic & Profile
    yrs: "વર્ષ",
    gender_male: "પુરુષ",
    gender_female: "સ્ત્રી",
    gender_other: "અન્ય",
    patient: "દર્દી",
    age_not_set: "ઉંમર નોંધાયેલ નથી",
    gender_not_set: "જાતિ નોંધાયેલ નથી",
    height_not_set: "ઊંચાઈ નોંધાયેલ નથી",
    weight_not_set: "વજન નોંધાયેલ નથી",
    height: "ઊંચાઈ",
    weight: "વજન",
    lang_en: "અંગ્રેજી",
    lang_hi: "હિન્દી",
    lang_bn: "બંગાળી",
    lang_ta: "તમિલ",
    lang_te: "તેલુગુ",
    lang_mr: "મરાઠી",
    lang_gu: "ગુજરાતી",
    lang_kn: "કન્નડ",
    lang_ml: "મલયાલમ",
    lang_pa: "પંજાબી",

    // Dates & Times
    today: "આજે",
    yesterday: "ગઈકાલે",
    tomorrow: "આવતીકાલે",
    last_updated: "છેલ્લે અપડેટ કરેલ",
    previous: "અગાઉનું",
    context: "સંદર્ભ",
    fasting: "ભૂખ્યા પેટે (Fasting)",
    post_meal: "જમ્યા પછી (Post-meal)",
    random: "સામાન્ય (Random)",
    no_data: "કોઈ માહિતી નથી",
    no_readings_yet: "હજી સુધી કોઈ રીડિંગ નથી",
    current_reading: "વર્તમાન રીડિંગ",

    // Vitals & Classification
    blood_pressure_label: "રક્તચાપ (BP)",
    blood_sugar_label: "બ્લડ શુગર",
    heart_rate_label: "હૃદયના ધબકારા",
    usual_range: "સામાન્ય શ્રેણી",
    recorded: "નોંધાયેલ",
    high: "ઉચ્ચ",
    low: "ઓછું",
    stable: "સ્થિર",
    higher_than_last: "છેલ્લી વખત કરતાં વધુ",
    lower_than_last: "છેલ્લી વખત કરતાં ઓછું",

    // Reminders & Routine
    daily_health_routine: "દૈનિક આરોગ્ય રીમાઇન્ડર્સ અને દિનચર્યા",
    medicine_reminders: "દવા રીમાઇન્ડર્સ",
    prescriptions_doses: "પ્રિસ્ક્રિપ્શન્સ અને સુનિશ્ચિત ડોઝ",
    active: "સક્રિય",
    taken: "લીધેલ",
    take_dose: "ડોઝ લો",
    no_meds_scheduled: "આજના માટે કોઈ દવા સુનિશ્ચિત નથી.",
    upload_rx_import: "દવાઓ ઉમેરવા માટે પ્રિસ્ક્રિપ્શન અપલોડ કરો →",
    track_logs_reminders: "રીમાઇન્ડર્સમાં લોગ જુઓ",
    manage_reminders: "બધા રીમાઇન્ડર્સ મેનેજ કરો →",

    // Yoga
    todays_yoga: "આજનું યોગ શેડ્યૂલ",
    yoga_subtitle: "ડૉક્ટર દ્વારા સૂચવેલ અને AI યોગ કોચ",
    done: "સંપૂર્ણ",
    check_pose: "મુદ્રા ચકાસો",
    mark_done: "પૂર્ણ તરીકે ચિહ્નિત કરો",
    body_pointer_hint: "બોડી પોઇન્ટર માર્ગદર્શન સાથે મુદ્રા જાળવો",
    full_yoga_routine: "સંપૂર્ણ યોગ દિનચર્યા →",
    daily: "દૈનિક",
    morning: "સવાર",
    evening: "સાંજ",
    min: "મિનિટ",

    // Personalized Nutrition & BMI
    nutrition_needs: "વ્યક્તિગત પોષણ અને કેલરી જરૂરિયાતો",
    nutrition_subtitle: "ઊંચાઈ, વજન અને બીએમઆઈ પરથી ગણતરી કરેલ",
    bmi_label: "બોડી માસ ઇન્ડેક્સ (BMI)",
    normal_weight: "સામાન્ય વજન",
    underweight: "ઓછું વજન",
    overweight: "વધુ વજન",
    obese: "મેદસ્વીતા",
    target_calories: "દૈનિક લક્ષ્ય કેલરી",
    kcal_day: "કિલો કેલરી / દિવસ",
    clinical_goal: "ક્લિનિકલ ધ્યેય",
    goal_maintenance: "શ્રેષ્ઠ જાળવણી અને ઊર્જા",
    goal_surplus: "કેલરી વધારો અને સ્નાયુ નિર્માણ",
    goal_balanced: "સંતુલિત જાળવણી અને ચયાપચય સ્વાસ્થ્ય",
    goal_deficit: "મધ્યમ ઘટાડો અને ચરબી ઘટાડવી",
    goal_reset: "મેટાબોલિક રીસેટ અને સોજા-વિરોધી આહાર",
    hydration_fiber: "દૈનિક પાણી અને ફાઇબર",
    water_intake: "પાણીનું સેવન",
    dietary_fiber: "આહાર ફાઇબર",
    macronutrient_split: "મેક્રોન્યુટ્રિઅન્ટ લક્ષ્ય વિતરણ (શરીર રચના મુજબ):",
    protein: "પ્રોટીન",
    protein_desc: "સ્નાયુ સમારકામ અને તૃપ્તિ",
    complex_carbs: "જટિલ કાર્બોહાઇડ્રેટ્સ",
    carbs_desc: "આખા અનાજ, કઠોળ અને લાંબી ઊર્જા",
    healthy_fats: "તંદુરસ્ત ચરબી",
    fats_desc: "હોર્મોન ઉત્પાદન અને સાંધાનું સ્વાસ્થ્ય",
    key_micronutrients: "તમારી બીએમઆઈ પ્રોફાઇલ માટે જરૂરી મુખ્ય સૂક્ષ્મ પોષકતત્ત્વો:",
    height_weight_prompt_title: "પોષણની ગણતરી માટે ઊંચાઈ અને વજન દાખલ કરો",
    height_weight_prompt_desc: "તમારું સચોટ બીએમઆઈ (BMI), દૈનિક કેલરી લક્ષ્ય અને પોષક તત્વો જોવા માટે પ્રોફાઇલમાં ઊંચાઈ અને વજન ઉમેરો.",
    enter_height_weight_btn: "પ્રોફાઇલમાં ઊંચાઈ અને વજન દાખલ કરો →",

    // Clinical Summary
    clinical_summary: "વર્તમાન તબીબી સારાંશ",
    latest_diagnosis: "તાજેતરનું નિદાન",
    recent_concern: "તાજેતરની ચિંતા",
    no_clinical_summary: "હજી કોઈ તબીબી સારાંશ નથી. તે બનાવવા માટે ઇતિહાસ રેકોર્ડ કરો.",

    // Quick Action Subtitles
    chat_subtitle_short: "તબીબી પ્રશ્ન પૂછો",
    exercise_desc: "દૈનિક ચેકલિસ્ટ અને યોગ કોચ",
    record_history_desc: "અવાજ અથવા ટેક્સ્ટ દ્વારા જવાબ આપો",
    upload_docs_desc: "પ્રિસ્ક્રિપ્શન અથવા લેબ રિપોર્ટ ઉમેરો",
    tracker_desc: "રક્તચાપ, શુગર અને મહત્વપૂર્ણ સંકેતો",
    reminders_desc: "દવા અને જીવનશૈલી એલાર્મ સેટ કરો",

    // Lists & Appointments
    recent_medical_history: "તાજેતરનો તબીબી ઇતિહાસ",
    no_medical_history: "હજુ સુધી કોઈ તબીબી ઇતિહાસ નોંધાયેલ નથી.",
    recent_health_readings: "તાજેતરના આરોગ્ય રીડિંગ્સ",
    no_health_readings: "કોઈ આરોગ્ય રીડિંગ્સ ઉપલબ્ધ નથી.",
    upcoming_appointments: "આગામી ડૉક્ટરની મુલાકાતો",
    doctor: "ડૉક્ટર",
    status_booked: "બુક થયેલ",
    status_in_progress: "પરામર્શ ચાલુ છે",
    status_completed: "પૂર્ણ થયેલ",
    status_cancelled: "રદ થયેલ",
  },

  kn: {
    care: "ಆರೋಗ್ಯ ಸೇವೆ",
    dashboard: "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
    medical_records: "ವೈದ್ಯಕೀಯ ದಾಖಲೆಗಳು",
    ai_health_assistant: "AI ಆರೋಗ್ಯ ಸಹಾಯಕ",
    upload_documents: "ದಾಖಲೆಗಳ ಅಪ್‌ಲೋಡ್",
    book_appointment: "ಅಪಾಯಿಂಟ್‌ಮೆಂಟ್ ಬುಕ್ ಮಾಡಿ",
    daily_routine: "ದೈನಂದಿನ ದಿನಚರಿ",
    health_tracker: "ಆರೋಗ್ಯ ಟ್ರ್ಯಾಕರ್",
    exercise_yoga: "ವ್ಯಾಯಾಮ ಮತ್ತು ಯೋಗ",
    ayurvedic_care: "ಆಯುರ್ವೇದ ಆರೈಕೆ",
    reminders: "ಔಷಧ ಜ್ಞಾಪನೆಗಳು",
    account: "ಖಾತೆ",
    profile: "ಪ್ರೊಫೈಲ್",
    patient_workspace: "ರೋಗಿಯ ಸ್ಥಳ",
    signed_in: "ಸೈನ್ ಇನ್ ಆಗಿದ್ದೀರಿ",
    logout: "ಲಾಗ್ ಔಟ್",
    menu: "ಮೆನು",
    high_contrast: "ಹೆಚ್ಚಿನ ಕಾಂಟ್ರಾಸ್ಟ್",
    standard_view: "ಸಾಮಾನ್ಯ ನೋಟ",
    language: "ಭಾಷೆ",
    select_language: "ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ",
    welcome_back: "ಮರಳಿ ಸ್ವಾಗತ",
    hello: "ನಮಸ್ಕಾರ",
    health_overview: "ನಿಮ್ಮ ಸಂಪೂರ್ಣ ಆರೋಗ್ಯ ಇತಿಹಾಸ — ಸೆಷನ್‌ಗಳು, ವರದಿಗಳು ಮತ್ತು ಪ್ರಿಸ್ಕ್ರಿಪ್ಷನ್‌ಗಳು.",
    quick_actions: "ತ್ವರಿತ ಕ್ರಿಯೆಗಳು",
    talk_to_ai: "AI ಸಹಾಯಕನೊಂದಿಗೆ ಮಾತನಾಡಿ",
    record_history: "ಇತಿಹಾಸ ದಾಖಲಿಸಿ",
    view_records: "ದಾಖಲೆಗಳನ್ನು ನೋಡಿ",
    vitals_summary: "ಪ್ರಮುಖ ಅಂಕಿಅಂಶಗಳು",
    heart_rate: "ಹೃದಯ ಬಡಿತ",
    blood_pressure: "ರಕ್ತದೊತ್ತಡ (BP)",
    blood_glucose: "ರಕ್ತದಲ್ಲಿನ ಸಕ್ಕರೆ",
    bmi_weight: "BMI & ತೂಕ",
    spo2: "ಆಕ್ಸಿಜನ್ (SpO2)",
    recent_prescriptions: "ಇತ್ತೀಚಿನ ಪ್ರಿಸ್ಕ್ರಿಪ್ಷನ್‌ಗಳು",
    upcoming_appointments: "ಮುಂಬರುವ ಅಪಾಯಿಂಟ್‌ಮೆಂಟ್‌ಗಳು",
    no_prescriptions: "ಇನ್ನೂ ಯಾವುದೇ ಪ್ರಿಸ್ಕ್ರಿಪ್ಷನ್‌ಗಳಿಲ್ಲ",
    no_appointments: "ಯಾವುದೇ ಮುಂಬರುವ ಅಪಾಯಿಂಟ್‌ಮೆಂಟ್‌ಗಳಿಲ್ಲ",
    chat_title: "AI ಆರೋಗ್ಯ ಸಹಾಯಕ",
    chat_subtitle: "ನಿಮ್ಮ ಪ್ರಿಸ್ಕ್ರಿಪ್ಷನ್‌ಗಳು, ರೋಗಲಕ್ಷಣಗಳು ಮತ್ತು ಆಯುರ್ವೇದ ಸಲಹೆಗಳ ಬಗ್ಗೆ ಕೇಳಿ.",
    new_chat: "+ ಹೊಸ ಚಾಟ್",
    conversations: "ಸಂಭಾಷಣೆಗಳು",
    type_message: "ನಿಮ್ಮ ಭಾಷೆಯಲ್ಲಿ ಆರೋಗ್ಯ ಪ್ರಶ್ನೆಯನ್ನು ಕೇಳಿ…",
    send: "ಕಳುಹಿಸಿ",
    thinking: "AI ಯೋಚಿಸುತ್ತಿದೆ…",
    chat_disclaimer: "AI ಸಹಾಯಕ ಕೇವಲ ಮಾರ್ಗದರ್ಶನ ನೀಡುತ್ತದೆ, ವೈದ್ಯರ ಬದಲಿಗೆ ಅಲ್ಲ.",
    emergency_detected: "ತುರ್ತು ಲಕ್ಷಣಗಳು ಕಂಡುಬಂದಿವೆ. ದಯವಿಟ್ಟು ತಕ್ಷಣ ವೈದ್ಯರನ್ನು ಸಂಪರ್ಕಿಸಿ.",
    suggestion_rx: "ನನ್ನ ಪ್ರಿಸ್ಕ್ರಿಪ್ಷನ್ ಸರಳವಾಗಿ ವಿವರಿಸಿ",
    suggestion_remedies: "ನೆಗಡಿ ಮತ್ತು ಕೆಮ್ಮಿಗೆ ಆಯುರ್ವೇದ ಮನೆಮದ್ದುಗಳು",
    suggestion_exercise: "ನನಗಾಗಿ ಸುರಕ್ಷಿತ ಯೋಗಾಸನಗಳನ್ನು ಸೂಚಿಸಿ",
    suggestion_diet: "ಆರೋಗ್ಯವಾಗಿರಲು ಇಂದು ನಾನು ಏನು ಸೇವಿಸಬೇಕು?",
    no_previous_chats: "ಹಿಂದಿನ ಸಂಭಾಷಣೆಗಳಿಲ್ಲ",
    start_first_chat: "AI ಸಹಾಯಕನೊಂದಿಗೆ ಮೊದಲ ಸಂಭಾಷಣೆಯನ್ನು ಪ್ರಾರಂಭಿಸಿ.",
    records_title: "ವೈದ್ಯಕೀಯ ದಾಖಲೆಗಳು",
    records_subtitle: "ನಿಮ್ಮ ಸಂಪೂರ್ಣ ಆರೋಗ್ಯ ಇತಿಹಾಸ.",
    add_medical_data: "ಮಾಹಿತಿ ಸೇರಿಸಿ",
    record_new_history: "ಹೊಸ ಇತಿಹಾಸ ದಾಖಲಿಸಿ",
    upload_a_document: "ದಾಖಲೆ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ",
    view_read_rx: "ಪ್ರಿಸ್ಕ್ರಿಪ್ಷನ್ ನೋಡಿ",
    download_print_pdf: "PDF ಡೌನ್‌ಲೋಡ್ / ಪ್ರಿಂಟ್",
    official_rx: "ಅಧಿಕೃತ ಪ್ರಿಸ್ಕ್ರಿಪ್ಷನ್",
    lab_report: "ಲ್ಯಾಬ್ ವರದಿ",
    history_session: "ಸೆಷನ್",
    prescribed_by: "ವೈದ್ಯರು",
    medicines: "ಔಷಧಿಗಳು",
    advice: "ಸಲಹೆ",
    yoga_lifestyle: "ಯೋಗ / ಜೀವನಶೈಲಿ",
    view_document: "ದಾಖಲೆ ನೋಡಿ →",
    view_full_history: "ಸಂಪೂರ್ಣ ಇತಿಹಾಸ →",
    continue_recording: "ಮುಂದುವರಿಸಿ →",
    no_records: "ದಾಖಲೆಗಳು ಲಭ್ಯವಿಲ್ಲ.",
    save: "ಉಳಿಸಿ",
    cancel: "ರದ್ದುಮಾಡಿ",
    close: "ಮುಚ್ಚಿ",
    loading: "ಲೋಡ್ ಆಗುತ್ತಿದೆ…",
    error: "ದೋಷ",
    retry: "ಮರುಪ್ರಯತ್ನಿಸಿ",
    back: "ಹಿಂದೆ",
    next: "ಮುಂದೆ",
    submit: "ಸಲ್ಲಿಸಿ",
    start: "ಪ್ರಾರಂಭಿಸಿ",
    save_changes: "ಬದಲಾವಣೆಗಳನ್ನು ಉಳಿಸಿ",

    // Demographic & Profile
    yrs: "ವರ್ಷಗಳು",
    gender_male: "ಪುರುಷ",
    gender_female: "ಮಹಿಳೆ",
    gender_other: "ಇತರ",
    patient: "ರೋಗಿ",
    age_not_set: "ವಯಸ್ಸು ನಮೂದಿಸಿಲ್ಲ",
    gender_not_set: "ಲಿಂಗ ನಮೂದಿಸಿಲ್ಲ",
    height_not_set: "ಎತ್ತರ ನಮೂದಿಸಿಲ್ಲ",
    weight_not_set: "ತೂಕ ನಮೂದಿಸಿಲ್ಲ",
    height: "ಎತ್ತರ",
    weight: "ತೂಕ",
    lang_en: "ಇಂಗ್ಲಿಷ್",
    lang_hi: "ಹಿಂದಿ",
    lang_bn: "ಬಂಗಾಳಿ",
    lang_ta: "ತಮಿಳು",
    lang_te: "ತೆಲುಗು",
    lang_mr: "ಮರಾಠಿ",
    lang_gu: "ಗುಜರಾತಿ",
    lang_kn: "ಕನ್ನಡ",
    lang_ml: "ಮಲಯಾಳಂ",
    lang_pa: "ಪಂಜಾಬಿ",

    // Dates & Times
    today: "ಇಂದು",
    yesterday: "ನಿನ್ನೆ",
    tomorrow: "ನಾಳೆ",
    last_updated: "ಕೊನೆಯದಾಗಿ ನವೀಕರಿಸಲಾಗಿದೆ",
    previous: "ಹಿಂದಿನ",
    context: "ಸಂದರ್ಭ",
    fasting: "ಖಾಲಿ ಹೊಟ್ಟೆಯಲ್ಲಿ (Fasting)",
    post_meal: "ಊಟದ ನಂತರ (Post-meal)",
    random: "ಸಾಮಾನ್ಯ (Random)",
    no_data: "ಯಾವುದೇ ಮಾಹಿತಿ ಇಲ್ಲ",
    no_readings_yet: "ಇನ್ನೂ ಯಾವುದೇ ರೀಡಿಂಗ್ಸ್ ಇಲ್ಲ",
    current_reading: "ಪ್ರಸ್ತುತ ರೀಡಿಂಗ್",

    // Vitals & Classification
    blood_pressure_label: "ರಕ್ತದೊತ್ತಡ (BP)",
    blood_sugar_label: "ರಕ್ತದ ಸಕ್ಕರೆ (షుಗರ್)",
    heart_rate_label: "ಹೃದಯ ಬಡಿತ",
    usual_range: "ಸಾಮಾನ್ಯ ಶ್ರೇಣಿ",
    recorded: "ದಾಖಲಿಸಲಾಗಿದೆ",
    high: "ಹೆಚ್ಚು",
    low: "ಕಡಿಮೆ",
    stable: "ಸ್ಥಿರವಾಗಿದೆ",
    higher_than_last: "ಹಿಂದಿನ ಬಾರಿಗಿಂತ ಹೆಚ್ಚು",
    lower_than_last: "ಹಿಂದಿನ ಬಾರಿಗಿಂತ ಕಡಿಮೆ",

    // Reminders & Routine
    daily_health_routine: "ದೈನಂದಿನ ಆರೋಗ್ಯ ಜ್ಞಾಪನೆಗಳು ಮತ್ತು ದಿನಚರಿ",
    medicine_reminders: "ಔಷಧ ಜ್ಞಾಪನೆಗಳು",
    prescriptions_doses: "ಪ್ರಿಸ್ಕ್ರಿಪ್ಷನ್‌ಗಳು ಮತ್ತು ನಿಗದಿತ ಪ್ರಮಾಣ",
    active: "ಸಕ್ರಿಯ",
    taken: "ತೆಗೆದುಕೊಳ್ಳಲಾಗಿದೆ",
    take_dose: "ಡೋಸ್ ತೆಗೆದುಕೊಳ್ಳಿ",
    no_meds_scheduled: "ಇಂದಿಗೆ ಯಾವುದೇ ಔಷಧಿಗಳನ್ನು ನಿಗದಿಪಡಿಸಲಾಗಿಲ್ಲ.",
    upload_rx_import: "ಔಷಧಿಗಳನ್ನು ಸೇರಿಸಲು ಪ್ರಿಸ್ಕ್ರಿಪ್ಷನ್ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ →",
    track_logs_reminders: "ಜ್ಞಾಪನೆಗಳಲ್ಲಿ ಲಾಗ್‌ಗಳನ್ನು ಟ್ರ್ಯಾಕ್ ಮಾಡಿ",
    manage_reminders: "ಎಲ್ಲಾ ಜ್ಞಾಪನೆಗಳನ್ನು ನಿರ್ವಹಿಸಿ →",

    // Yoga
    todays_yoga: "ಇಂದಿನ ಯೋಗ ವೇಳಾಪಟ್ಟಿ",
    yoga_subtitle: "ವೈದ್ಯರು ಸೂಚಿಸಿದ ಮತ್ತು AI ಭಂಗಿ ತರಬೇತುದಾರ",
    done: "ಪೂರ್ಣಗೊಂಡಿದೆ",
    check_pose: "ಭಂಗಿಯನ್ನು ಪರೀಕ್ಷಿಸಿ",
    mark_done: "ಪೂರ್ಣಗೊಂಡಿದೆ ಎಂದು ಗುರುತಿಸಿ",
    body_pointer_hint: "ಬಾಡಿ ಪಾಯಿಂಟರ್ ಮಾರ್ಗದರ್ಶನದೊಂದಿಗೆ ಭಂಗಿ ಹಿಡಿಯಿರಿ",
    full_yoga_routine: "ಸಂಪೂರ್ಣ ಯೋಗ ದಿನಚರಿ →",
    daily: "ದೈನಂದಿನ",
    morning: "ಬೆಳಿಗ್ಗೆ",
    evening: "ಸಂಜೆ",
    min: "ನಿಮಿಷ",

    // Personalized Nutrition & BMI
    nutrition_needs: "ವೈಯಕ್ತಿಕ ಪೌಷ್ಟಿಕಾಂಶ ಮತ್ತು ಕ್ಯಾಲೋರಿ ಅಗತ್ಯಗಳು",
    nutrition_subtitle: "ಎತ್ತರ, ತೂಕ ಮತ್ತು ಬಿಎಂಐ ಆಧರಿಸಿ ಲೆಕ್ಕಹಾಕಲಾಗಿದೆ",
    bmi_label: "ಬಾಡಿ ಮಾಸ್ ಇಂಡೆಕ್ಸ್ (BMI)",
    normal_weight: "ಸಾಮಾನ್ಯ ತೂಕ",
    underweight: "ಕಡಿಮೆ ತೂಕ",
    overweight: "ಅಧಿಕ ತೂಕ",
    obese: "ಸ್ಥೂಲಕಾಯ",
    target_calories: "ದೈನಂದಿನ ಗುರಿ ಕ್ಯಾಲೋರಿಗಳು",
    kcal_day: "ಕಿಲೋ ಕ್ಯಾಲೋರಿ / ದಿನ",
    clinical_goal: "ವೈದ್ಯಕೀಯ ಗುರಿ",
    goal_maintenance: "ಉತ್ತಮ ನಿರ್ವಹಣೆ ಮತ್ತು ಚೈತನ್ಯ",
    goal_surplus: "ಕ್ಯಾಲೋರಿ ಹೆಚ್ಚಳ ಮತ್ತು ಸ್ನಾಯು ನಿರ್ಮಾಣ",
    goal_balanced: "ಸಮತೋಲಿತ ನಿರ್ವಹಣೆ ಮತ್ತು ಚಯಾಪಚಯ ಆರೋಗ್ಯ",
    goal_deficit: "ಮಿತವಾದ ಕೊರತೆ ಮತ್ತು ಕೊಬ್ಬು ನಷ್ಟ",
    goal_reset: "ಮೆಟಾಬಾಲಿಕ್ ಮರುಹೊಂದಿಸುವಿಕೆ ಮತ್ತು ಉರಿಯೂತ ವಿರೋಧಿ ಆಹಾರ",
    hydration_fiber: "ದೈನಂದಿನ ನೀರು ಮತ್ತು ನಾರು",
    water_intake: "ನೀರಿನ ಸೇವನೆ",
    dietary_fiber: "ಆಹಾರದ ನಾರು (ಫೈಬರ್)",
    macronutrient_split: "ಮ್ಯಾಕ್ರೋನ್ಯೂಟ್ರಿಯೆಂಟ್ ಗುರಿ ವಿಭಜನೆ (ದೇಹದ ರಚನೆಯ ಆಧಾರದ ಮೇಲೆ):",
    protein: "ಪ್ರೋಟೀನ್",
    protein_desc: "ಸ್ನಾಯು ದುರಸ್ತಿ ಮತ್ತು ಚಯಾಪಚಯ ತೃಪ್ತಿ",
    complex_carbs: "ಸಂಕೀರ್ಣ ಕಾರ್ಬೋಹೈಡ್ರೇಟ್‌ಗಳು",
    carbs_desc: "ಧಾನ್ಯಗಳು, ಕಾಳುಗಳು ಮತ್ತು ದೀರ್ಘಕಾಲಿಕ ಶಕ್ತಿ",
    healthy_fats: "ಆರೋಗ್ಯಕರ ಕೊಬ್ಬುಗಳು",
    fats_desc: "ಹಾರ್ಮೋನ್ ಉತ್ಪಾದನೆ ಮತ್ತು ಕೀಲುಗಳ ನಯಗೊಳಿಸುವಿಕೆ",
    key_micronutrients: "ನಿಮ್ಮ ಬಿಎಂಐ ಪ್ರೊಫೈಲ್‌ಗೆ ಅಗತ್ಯವಿರುವ ಪ್ರಮುಖ ಸೂಕ್ಷ್ಮ ಪೋಷಕಾಂಶಗಳು:",
    height_weight_prompt_title: "ಪೋಷಕಾಂಶಗಳನ್ನು ಲೆಕ್ಕಹಾಕಲು ಎತ್ತರ ಮತ್ತು ತೂಕವನ್ನು ನಮೂದಿಸಿ",
    height_weight_prompt_desc: "ನಿಖರವಾದ ಬಿಎಂಐ (BMI), ದೈನಂದಿನ ಕ್ಯಾಲೋರಿ ಗುರಿ ಮತ್ತು ಪೌಷ್ಟಿಕಾಂಶದ ವಿವರಗಳನ್ನು ನೋಡಲು ಪ್ರೊಫೈಲ್‌ನಲ್ಲಿ ಎತ್ತರ ಮತ್ತು ತೂಕವನ್ನು ನಮೂದಿಸಿ.",
    enter_height_weight_btn: "ಪ್ರೊಫೈಲ್‌ನಲ್ಲಿ ಎತ್ತರ ಮತ್ತು ತೂಕವನ್ನು ನಮೂದಿಸಿ →",

    // Clinical Summary
    clinical_summary: "ಪ್ರಸ್ತುತ ವೈದ್ಯಕೀಯ ಸಾರಾಂಶ",
    latest_diagnosis: "ಇತ್ತೀಚಿನ ರೋಗನಿರ್ಣಯ",
    recent_concern: "ಇತ್ತೀಚಿನ ಕಾಳಜಿ",
    no_clinical_summary: "ಇನ್ನೂ ಯಾವುದೇ ವೈದ್ಯಕೀಯ ಸಾರಾಂಶವಿಲ್ಲ. ನಿರ್ಮಿಸಲು ವೈದ್ಯಕೀಯ ಇತಿಹಾಸವನ್ನು ದಾಖಲಿಸಿ.",

    // Quick Action Subtitles
    chat_subtitle_short: "ವೈದ್ಯಕೀಯ ಪ್ರಶ್ನೆ ಕೇಳಿ",
    exercise_desc: "ದೈನಂದಿನ ಪರಿಶೀಲನಾ ಪಟ್ಟಿ ಮತ್ತು AI ಯೋಗ ತರಬೇತುದಾರ",
    record_history_desc: "ಧ್ವನಿ ಅಥವಾ ಪಠ್ಯದ ಮೂಲಕ ಉತ್ತರಿಸಿ",
    upload_docs_desc: "ಪ್ರಿಸ್ಕ್ರಿಪ್ಷನ್ ಅಥವಾ ಲ್ಯಾಬ್ ವರದಿ ಸೇರಿಸಿ",
    tracker_desc: "ರಕ್ತದೊತ್ತಡ, ಸಕ್ಕರೆ ಮತ್ತು ಪ್ರಮುಖ ಲಕ್ಷಣಗಳು",
    reminders_desc: "ಔಷಧಿ ಮತ್ತು ಜೀವನಶೈಲಿ ಎಚ್ಚರಿಕೆಗಳನ್ನು ಹೊಂದಿಸಿ",

    // Lists & Appointments
    recent_medical_history: "ಇತ್ತೀಚಿನ ವೈದ್ಯಕೀಯ ಇತಿಹಾಸ",
    no_medical_history: "ಇನ್ನೂ ಯಾವುದೇ ವೈದ್ಯಕೀಯ ಇತಿಹಾಸ ದಾಖಲಾಗಿಲ್ಲ.",
    recent_health_readings: "ಇತ್ತೀಚಿನ ಆರೋಗ್ಯ ರೀಡಿಂಗ್‌ಗಳು",
    no_health_readings: "ಯಾವುದೇ ಆರೋಗ್ಯ ರೀಡಿಂಗ್‌ಗಳು ಲಭ್ಯವಿಲ್ಲ.",
    upcoming_appointments: "ಮುಂಬರುವ ವೈದ್ಯರ ಭೇಟಿಗಳು",
    doctor: "ವೈದ್ಯರು",
    status_booked: "ಕಾಯ್ದಿರಿಸಲಾಗಿದೆ",
    status_in_progress: "ಸಮಾಲೋಚನೆ ನಡೆಯುತ್ತಿದೆ",
    status_completed: "ಪೂರ್ಣಗೊಂಡಿದೆ",
    status_cancelled: "ರದ್ದುಗೊಳಿಸಲಾಗಿದೆ",
  },

  ml: {
    care: "ആരോഗ്യ സംരക്ഷണം",
    dashboard: "ഡാഷ്‌ബോർഡ്",
    medical_records: "മെഡിക്കൽ രേഖകൾ",
    ai_health_assistant: "AI ആരോഗ്യ സഹായി",
    upload_documents: "രേഖകൾ അപ്‌ലോഡ് ചെയ്യുക",
    book_appointment: "അപ്പോയിന്റ്മെന്റ് ബുക്ക് ചെയ്യുക",
    daily_routine: "ദിനചര്യ",
    health_tracker: "ഹെൽത്ത് ട്രാക്കർ",
    exercise_yoga: "വ്യായാമവും യോഗയും",
    ayurvedic_care: "ആയുർവേദ പരിചരണം",
    reminders: "മരുന്ന് ഓർമ്മപ്പെടുത്തലുകൾ",
    account: "അക്കൗണ്ട്",
    profile: "പ്രൊഫൈൽ",
    patient_workspace: "രോഗിയുടെ പോർട്ടൽ",
    signed_in: "ലോഗിൻ ചെയ്തു",
    logout: "ലോഗൗട്ട്",
    menu: "മെനു",
    high_contrast: "ഉയർന്ന കോൺട്രാസ്റ്റ്",
    standard_view: "സാധാരണ കാഴ്ച",
    language: "ഭാഷ",
    select_language: "ഭാഷ തിരഞ്ഞെടുക്കുക",
    welcome_back: "സ്വാഗതം",
    hello: "നമസ്കാരം",
    health_overview: "നിങ്ങളുടെ പൂർണ്ണമായ ആരോഗ്യ ചരിത്രം — പരിശോധനകൾ, റിപ്പോർട്ടുകൾ.",
    quick_actions: "ദ്രുത പ്രവർത്തനങ്ങൾ",
    talk_to_ai: "AI സഹായിയോട് സംസാരിക്കുക",
    record_history: "ചരിത്രം രേഖപ്പെടുത്തുക",
    view_records: "രേഖകൾ കാണുക",
    vitals_summary: "പ്രധാന വിവരങ്ങൾ",
    heart_rate: "ഹൃദയമിടിപ്പ്",
    blood_pressure: "രക്തസമ്മർദ്ദം (BP)",
    blood_glucose: "ബ്ലഡ് ഷുഗർ",
    bmi_weight: "ബിഎംഐ & ഭാരം",
    spo2: "ഓക്സിജൻ (SpO2)",
    recent_prescriptions: "സമീപകാല കുറിപ്പടികൾ",
    upcoming_appointments: "വരാനിരിക്കുന്ന അപ്പോയിന്റ്മെന്റുകൾ",
    no_prescriptions: "കുറിപ്പടികൾ ലഭ്യമല്ല",
    no_appointments: "അപ്പോയിന്റ്മെന്റുകൾ ലഭ്യമല്ല",
    chat_title: "AI ആരോഗ്യ സഹായി",
    chat_subtitle: "നിങ്ങളുടെ മരുന്നുകൾ, ലക്ഷണങ്ങൾ, ആയുർവേദ മാർഗ്ഗങ്ങൾ എന്നിവയെക്കുറിച്ച് ചോദിക്കുക.",
    new_chat: "+ പുതിയ സംഭാഷണം",
    conversations: "സംഭാഷണങ്ങൾ",
    type_message: "നിങ്ങളുടെ ഭാഷയിൽ ആരോഗ്യ ചോദ്യം ചോദിക്കുക…",
    send: "അയക്കുക",
    thinking: "AI ചിന്തിക്കുന്നു…",
    chat_disclaimer: "AI സഹായി മാർഗ്ഗനിർദ്ദേശം മാത്രമാണ് നൽകുന്നത്, ഡോക്ടർക്ക് പകരമല്ല.",
    emergency_detected: "അടിയന്തര ലക്ഷണങ്ങൾ കണ്ടെത്തി. ഉടൻ തന്നെ വൈദ്യസഹായം തേടുക.",
    suggestion_rx: "എന്റെ കുറിപ്പടി ലളിതമായി വിശദീകരിക്കുക",
    suggestion_remedies: "ജലദോഷത്തിനും ചുമയ്ക്കും ആയുർവേദ പ്രതിവിധികൾ",
    suggestion_exercise: "എനിക്ക് അനുയോജ്യമായ യോഗാസനങ്ങൾ നിർദ്ദേശിക്കുക",
    suggestion_diet: "ആരോഗ്യവാനായിരിക്കാൻ ഇന്ന് എന്തൊക്കെ കഴിക്കണം?",
    no_previous_chats: "മുമ്പത്തെ സംഭാഷണങ്ങളില്ല",
    start_first_chat: "AI സഹായിയുമായി ആദ്യ സംഭാഷണം ആരംഭിക്കുക.",
    records_title: "മെഡിക്കൽ രേഖകൾ",
    records_subtitle: "നിങ്ങളുടെ പൂർണ്ണമായ ആരോഗ്യ ചരിത്രം.",
    add_medical_data: "വിവരങ്ങൾ ചേർക്കുക",
    record_new_history: "പുതിയ ചരിത്രം രേഖപ്പെടുത്തുക",
    upload_a_document: "രേഖ അപ്‌ലോഡ് ചെയ്യുക",
    view_read_rx: "കുറിപ്പടി കാണുക",
    download_print_pdf: "PDF ഡൗൺലോഡ് / പ്രിന്റ്",
    official_rx: "ഔദ്യോഗിക കുറിപ്പടി",
    lab_report: "ലാബ് റിപ്പോർട്ട്",
    history_session: "സെഷൻ",
    prescribed_by: "ഡോക്ടർ",
    medicines: "മരുന്നുകൾ",
    advice: "ഉപദേശം",
    yoga_lifestyle: "യോഗ / ജീവിതശൈലി",
    view_document: "രേഖ കാണുക →",
    view_full_history: "പൂർണ്ണ ചരിത്രം →",
    continue_recording: "തുടരുക →",
    no_records: "രേഖകൾ ലഭ്യമല്ല.",
    save: "സംരക്ഷിക്കുക",
    cancel: "റദ്ദാക്കുക",
    close: "അടയ്ക്കുക",
    loading: "ലോഡ് ചെയ്യുന്നു…",
    error: "പിശക്",
    retry: "വീണ്ടും ശ്രമിക്കുക",
    back: "പിന്നോട്ട്",
    next: "അടുത്തത്",
    submit: "സമർപ്പിക്കുക",
    start: "ആരംഭിക്കുക",
    save_changes: "മാറ്റങ്ങൾ സംരക്ഷിക്കുക",

    // Demographic & Profile
    yrs: "വർഷം",
    gender_male: "പുരുഷൻ",
    gender_female: "സ്ത്രീ",
    gender_other: "മറ്റുള്ളവ",
    patient: "രോഗി",
    age_not_set: "പ്രായം രേഖപ്പെടുത്തിയിട്ടില്ല",
    gender_not_set: "ലിംഗം രേഖപ്പെടുത്തിയിട്ടില്ല",
    height_not_set: "ഉയരം രേഖപ്പെടുത്തിയിട്ടില്ല",
    weight_not_set: "ഭാരം രേഖപ്പെടുത്തിയിട്ടില്ല",
    height: "ഉയരം",
    weight: "ഭാരം",
    lang_en: "ഇംഗ്ലീഷ്",
    lang_hi: "ഹിന്ദി",
    lang_bn: "ബംഗാളി",
    lang_ta: "തമിഴ്",
    lang_te: "തെലുങ്ക്",
    lang_mr: "മറാഠി",
    lang_gu: "ഗുജറാത്തി",
    lang_kn: "കന്നഡ",
    lang_ml: "മലയാളം",
    lang_pa: "പഞ്ചാബി",

    // Dates & Times
    today: "ഇന്ന്",
    yesterday: "ഇന്നലെ",
    tomorrow: "നാളെ",
    last_updated: "അവസാനം അപ്ഡേറ്റ് ചെയ്തത്",
    previous: "മുമ്പത്തെ",
    context: "സന്ദർഭം",
    fasting: "വെറും വയറ്റിൽ (Fasting)",
    post_meal: "ഭക്ഷണത്തിനു ശേഷം (Post-meal)",
    random: "സാധാരണ (Random)",
    no_data: "വിവരങ്ങൾ ലഭ്യമല്ല",
    no_readings_yet: "ഇതുവരെ റീഡിംഗുകൾ ഇല്ല",
    current_reading: "നിലവിലെ റീഡിംഗ്",

    // Vitals & Classification
    blood_pressure_label: "രക്തസമ്മർദ്ദം (BP)",
    blood_sugar_label: "രക്തത്തിലെ പഞ്ചസാര",
    heart_rate_label: "ഹൃദയമിടിപ്പ് നിരക്ക്",
    usual_range: "സാധാരണ പരിധി",
    recorded: "രേഖപ്പെടുത്തി",
    high: "കൂടിയത്",
    low: "കുറഞ്ഞത്",
    stable: "സ്ഥിരതയുള്ളത്",
    higher_than_last: "കഴിഞ്ഞ തവണയേക്കാൾ കൂടുതൽ",
    lower_than_last: "കഴിഞ്ഞ തവണയേക്കാൾ കുറവ്",

    // Reminders & Routine
    daily_health_routine: "ദൈനംദിന ആരോഗ്യ ഓർമ്മപ്പെടുത്തലുകളും ദിനചര്യയും",
    medicine_reminders: "മരുന്ന് ഓർമ്മപ്പെടുത്തലുകൾ",
    prescriptions_doses: "കുറിപ്പടികളും നിശ്ചിത ഡോസുകളും",
    active: "സജീവം",
    taken: "കഴിച്ചു",
    take_dose: "മരുന്ന് കഴിക്കുക",
    no_meds_scheduled: "ഇന്നത്തേക്ക് മരുന്നുകൾ ഷെഡ്യൂൾ ചെയ്തിട്ടില്ല.",
    upload_rx_import: "മരുന്നുകൾ ചേർക്കാൻ കുറിപ്പടി അപ്‌ലോഡ് ചെയ്യുക →",
    track_logs_reminders: "റിമൈൻഡറുകളിലെ ലോഗുകൾ ട്രാക്ക് ചെയ്യുക",
    manage_reminders: "എല്ലാ റിമൈൻഡറുകളും നിയന്ത്രിക്കുക →",

    // Yoga
    todays_yoga: "ഇന്നത്തെ യോഗ ക്രമം",
    yoga_subtitle: "ഡോക്ടർ നിർദ്ദേശിച്ചതും AI യോഗ പരിശീലകനും",
    done: "പൂർത്തിയായി",
    check_pose: "നില പരിശോധിക്കുക",
    mark_done: "പൂർത്തിയായതായി അടയാളപ്പെടുത്തുക",
    body_pointer_hint: "ബോഡി പോയിന്റർ നിർദ്ദേശങ്ങളോടെ യോഗാസനം ചെയ്യുക",
    full_yoga_routine: "മുഴുവൻ യോഗ ദിനചര്യ →",
    daily: "ദിവസേന",
    morning: "രാവിലെ",
    evening: "വൈകുന്നേരം",
    min: "മിനിറ്റ്",

    // Personalized Nutrition & BMI
    nutrition_needs: "വ്യക്തിഗത പോഷകാഹാരവും കലോറി ആവശ്യകതകളും",
    nutrition_subtitle: "ഉയരം, ഭാരം, ബിഎംഐ എന്നിവ അടിസ്ഥാനമാക്കി കണക്കാക്കിയത്",
    bmi_label: "ബോഡി മാസ് ഇൻഡക്സ് (BMI)",
    normal_weight: "സാധാരണ ഭാരം",
    underweight: "ഭാരക്കുറവ്",
    overweight: "അമിതഭാരം",
    obese: "അമിതവണ്ണം (Obese)",
    target_calories: "പ്രതിദിന ലക്ഷ്യ കലോറികൾ",
    kcal_day: "കിലോ കലോറി / ദിവസം",
    clinical_goal: "ക്ലിനിക്കൽ ലക്ഷ്യം",
    goal_maintenance: "മികച്ച പരിപാലനവും ഊർജ്ജസ്വലതയും",
    goal_surplus: "കലോറി വർദ്ധനവും പേശീ നിർമ്മാണവും",
    goal_balanced: "സന്തുലിത പരിപാലനവും മെറ്റബോളിക് ആരോഗ്യവും",
    goal_deficit: "മിതമായ കുറവും കൊഴുപ്പ് കുറയ്ക്കലും",
    goal_reset: "മെറ്റബോളിക് റീസെറ്റും വീക്കം കുറയ്ക്കുന്ന ഭക്ഷണവും",
    hydration_fiber: "പ്രതിദിന ജലവും നാരുകളും",
    water_intake: "വെള്ളം കുടിക്കുന്നത്",
    dietary_fiber: "ഭക്ഷണത്തിലെ നാരുകൾ (ഫൈബർ)",
    macronutrient_split: "മാക്രോ ന്യൂട്രിയന്റ് ലക്ഷ്യ വിഭജനം (ശരീരഘടന അടിസ്ഥാനമാക്കി):",
    protein: "പ്രോട്ടീൻ",
    protein_desc: "പേശികളുടെ പുനർനിർമ്മാണവും സംതൃപ്തിയും",
    complex_carbs: "കോംപ്ലക്സ് കാർബോഹൈഡ്രേറ്റ്",
    carbs_desc: "ധാന്യങ്ങൾ, പയറുവർഗ്ഗങ്ങൾ & നീണ്ടുനിൽക്കുന്ന ഊർജ്ജം",
    healthy_fats: "ആരോഗ്യകരമായ കൊഴുപ്പുകൾ",
    fats_desc: "ഹോർമോൺ ഉൽപാദനവും സന്ധികളുടെ സംരക്ഷണവും",
    key_micronutrients: "നിങ്ങളുടെ ബിഎംഐ പ്രൊഫൈലിന് ആവശ്യമായ പ്രധാന സൂക്ഷ്മ പോഷകങ്ങൾ:",
    height_weight_prompt_title: "പോഷകാഹാരം കണക്കാക്കാൻ ഉയരവും ഭാരവും രേഖപ്പെടുത്തുക",
    height_weight_prompt_desc: "കൃത്യമായ ബിഎംഐ (BMI), പ്രതിദിന കലോറി ലക്ഷ്യം, പോഷക വിവരങ്ങൾ എന്നിവ കാണാൻ പ്രൊഫൈലിൽ ഉയരവും ഭാരവും നൽകുക.",
    enter_height_weight_btn: "പ്രൊഫൈലിൽ ഉയരവും ഭാരവും നൽകുക →",

    // Clinical Summary
    clinical_summary: "നിലവിലെ ക്ലിനിക്കൽ സംഗ്രഹം",
    latest_diagnosis: "ഏറ്റവും പുതിയ രോഗനിർണയം",
    recent_concern: "സമീപകാല ആശങ്ക",
    no_clinical_summary: "ഇതുവരെ ക്ലിനിക്കൽ സംഗ്രഹം ഇല്ല. ഇത് നിർമ്മിക്കാൻ നിങ്ങളുടെ മെഡിക്കൽ ചരിത്രം രേഖപ്പെടുത്തുക.",

    // Quick Action Subtitles
    chat_subtitle_short: "ആരോഗ്യപരമായ ചോദ്യം ചോദിക്കുക",
    exercise_desc: "പ്രതിദിന ചെക്ക്‌ലിസ്റ്റും AI യോഗ പരിശീലകനും",
    record_history_desc: "ശബ്ദം വഴിയോ ടെക്‌സ്‌റ്റ് വഴിയോ ഉത്തരം നൽകുക",
    upload_docs_desc: "കുറിപ്പടിയോ ലാബ് റിപ്പോർട്ടോ ചേർക്കുക",
    tracker_desc: "രക്തസമ്മർദ്ദം, ഷുഗർ, പ്രധാന ലക്ഷണങ്ങൾ",
    reminders_desc: "മരുന്നുകളും ജീവിതശൈലി അലാറങ്ങളും സജ്ജീകരിക്കുക",

    // Lists & Appointments
    recent_medical_history: "സമീപകാല മെഡിക്കൽ ചരിത്രം",
    no_medical_history: "ഇതുവരെ മെഡിക്കൽ ചരിത്രമൊന്നും രേഖപ്പെടുത്തിയിട്ടില്ല.",
    recent_health_readings: "സമീപകാല ആരോഗ്യ റീഡിംഗുകൾ",
    no_health_readings: "ആരോഗ്യ റീഡിംഗുകളൊന്നും ലഭ്യമല്ല.",
    upcoming_appointments: "വരാനിരിക്കുന്ന ഡോക്ടർ അപ്പോയിന്റ്മെന്റുകൾ",
    doctor: "ഡോക്ടർ",
    status_booked: "ബുക്ക് ചെയ്തു",
    status_in_progress: "കൂടിയാലോചന നടക്കുന്നു",
    status_completed: "പൂർത്തിയായി",
    status_cancelled: "റദ്ദാക്കി",
  },

  pa: {
    care: "ਸਿਹਤ ਸੰਭਾਲ",
    dashboard: "ਡੈਸ਼ਬੋਰਡ",
    medical_records: "ਮੈਡੀਕਲ ਰਿਕਾਰਡ",
    ai_health_assistant: "AI ਸਿਹਤ ਸਹਾਇਕ",
    upload_documents: "ਦਸਤਾਵੇਜ਼ ਅੱਪਲੋਡ",
    book_appointment: "ਮੁਲਾਕਾਤ ਬੁੱਕ ਕਰੋ",
    daily_routine: "ਰੋਜ਼ਾਨਾ ਨੇਮ",
    health_tracker: "ਸਿਹਤ ਟਰੈਕਰ",
    exercise_yoga: "ਕਸਰਤ ਅਤੇ ਯੋਗਾ",
    ayurvedic_care: "ਆਯੁਰਵੈਦਿਕ ਦੇਖਭਾਲ",
    reminders: "ਦਵਾਈ ਰੀਮਾਈਂਡਰ",
    account: "ਖਾਤਾ",
    profile: "ਪ੍ਰੋਫਾਈਲ",
    patient_workspace: "ਮਰੀਜ਼ ਪੋਰਟਲ",
    signed_in: "ਲੌਗ ਇਨ ਹੋ",
    logout: "ਲੌਗ ਆਉਟ",
    menu: "ਮੀਨੂ",
    high_contrast: "ਉੱਚ ਕੰਟਰਾਸਟ",
    standard_view: "ਸਧਾਰਨ ਦ੍ਰਿਸ਼",
    language: "ਭਾਸ਼ਾ",
    select_language: "ਭਾਸ਼ਾ ਚੁਣੋ",
    welcome_back: "ਜੀ ਆਇਆਂ ਨੂੰ",
    hello: "ਸਤਿ ਸ੍ਰੀ ਅਕਾਲ",
    health_overview: "ਤੁਹਾਡਾ ਪੂਰਾ ਸਿਹਤ ਇਤਿਹਾਸ — ਰਿਪੋਰਟਾਂ ਅਤੇ ਨੁਸਖੇ।",
    quick_actions: "ਤੁਰੰਤ ਕਾਰਵਾਈਆਂ",
    talk_to_ai: "AI ਸਹਾਇਕ ਨਾਲ ਗੱਲ ਕਰੋ",
    record_history: "ਇਤਿਹਾਸ ਦਰਜ ਕਰੋ",
    view_records: "ਰਿਕਾਰਡ ਦੇਖੋ",
    vitals_summary: "ਮਹੱਤਵਪੂਰਨ ਸੂਚਕ",
    heart_rate: "ਦਿਲ ਦੀ ਧੜਕਣ",
    blood_pressure: "ਬਲੱਡ ਪ੍ਰੈਸ਼ਰ (BP)",
    blood_glucose: "ਬਲੱਡ ਸ਼ੂਗਰ",
    bmi_weight: "BMI ਅਤੇ ਭਾਰ",
    spo2: "ਆਕਸੀਜਨ (SpO2)",
    recent_prescriptions: "ਤਾਜ਼ਾ ਨੁਸਖੇ",
    upcoming_appointments: "ਆਗਾਮੀ ਮੁਲਾਕਾਤਾਂ",
    no_prescriptions: "ਕੋਈ ਨੁਸਖਾ ਮੌਜੂਦ ਨਹੀਂ ਹੈ",
    no_appointments: "ਕੋਈ ਮੁਲਾਕਾਤ ਤਹਿ ਨਹੀਂ ਹੈ",
    chat_title: "AI ਸਿਹਤ ਸਹਾਇਕ",
    chat_subtitle: "ਆਪਣੀਆਂ ਦਵਾਈਆਂ, ਲੱਛਣਾਂ ਅਤੇ ਆਯੁਰਵੈਦਿਕ ਨੁਸਖਿਆਂ ਬਾਰੇ ਪੁੱਛੋ।",
    new_chat: "+ ਨਵੀਂ ਗੱਲਬਾਤ",
    conversations: "ਗੱਲਬਾਤ",
    type_message: "ਆਪਣੀ ਭਾਸ਼ਾ ਵਿੱਚ ਸਿਹਤ ਸੰਬੰਧੀ ਸਵਾਲ ਪੁੱਛੋ…",
    send: "ਭੇਜੋ",
    thinking: "AI ਸੋਚ ਰਿਹਾ ਹੈ…",
    chat_disclaimer: "AI ਸਹਾਇਕ ਸਿਰਫ਼ ਮਾਰਗਦਰਸ਼ਨ ਲਈ ਹੈ, ਡਾਕਟਰ ਦਾ ਬਦਲ ਨਹੀਂ।",
    emergency_detected: "ਐਮਰਜੈਂਸੀ ਲੱਛਣ ਮਿਲੇ ਹਨ। ਕਿਰਪਾ ਕਰਕੇ ਤੁਰੰਤ ਡਾਕਟਰੀ ਸਹਾਇਤਾ ਲਓ।",
    suggestion_rx: "ਮੇਰਾ ਨੁਸਖਾ ਸਰਲ ਸ਼ਬਦਾਂ ਵਿੱਚ ਸਮਝਾਓ",
    suggestion_remedies: "ਖੰਘ ਅਤੇ ਜ਼ੁਕਾਮ ਲਈ ਆਯੁਰਵੈਦਿਕ ਘਰੇਲੂ ਨੁਸਖੇ",
    suggestion_exercise: "ਮੇਰੇ ਲਈ ਸੁਰੱਖਿਅਤ ਸਵੇਰ ਦਾ ਯੋਗਾ ਸੁਝਾਓ",
    suggestion_diet: "ਤੰਦਰੁਸਤ ਰਹਿਣ ਲਈ ਮੈਨੂੰ ਅੱਜ ਕੀ ਖਾਣਾ ਚਾਹੀਦਾ ਹੈ?",
    no_previous_chats: "ਕੋਈ ਪਿਛਲੀ ਗੱਲਬਾਤ ਨਹੀਂ",
    start_first_chat: "ਆਪਣੇ AI ਸਹਾਇਕ ਨਾਲ ਗੱਲਬਾਤ ਸ਼ੁਰੂ ਕਰੋ।",
    records_title: "ਮੈਡੀਕਲ ਰਿਕਾਰਡ",
    records_subtitle: "ਤੁਹਾਡਾ ਪੂਰਾ ਸਿਹਤ ਇਤਿਹਾਸ।",
    add_medical_data: "ਡਾਟਾ ਸ਼ਾਮਲ ਕਰੋ",
    record_new_history: "ਨਵਾਂ ਇਤਿਹਾਸ ਦਰਜ ਕਰੋ",
    upload_a_document: "ਦਸਤਾਵੇਜ਼ ਅੱਪਲੋਡ ਕਰੋ",
    view_read_rx: "ਨੁਸਖਾ ਦੇਖੋ ਅਤੇ ਪੜ੍ਹੋ",
    download_print_pdf: "PDF ਡਾਊਨਲੋਡ / ਪ੍ਰਿੰਟ",
    official_rx: "ਅਧਿਕਾਰਤ ਨੁਸਖਾ",
    lab_report: "ਲੈਬ ਰਿਪੋਰਟ",
    history_session: "ਇਤਿਹਾਸ ਸੈਸ਼ਨ",
    prescribed_by: "ਡਾਕਟਰ",
    medicines: "ਦਵਾਈਆਂ",
    advice: "ਸਲਾਹ",
    yoga_lifestyle: "ਯੋਗਾ / ਜੀਵਨ ਸ਼ੈਲੀ",
    view_document: "ਦਸਤਾਵੇਜ਼ ਦੇਖੋ →",
    view_full_history: "ਪੂਰਾ ਇਤਿਹਾਸ →",
    continue_recording: "ਜਾਰੀ ਰੱਖੋ →",
    no_records: "ਕੋਈ ਰਿਕਾਰਡ ਨਹੀਂ ਮਿਲਿਆ।",
    save: "ਸੰਭਾਲੋ",
    cancel: "ਰੱਦ ਕਰੋ",
    close: "ਬੰਦ ਕਰੋ",
    loading: "ਲੋਡ ਹੋ ਰਿਹਾ ਹੈ…",
    error: "ਗ਼ਲਤੀ",
    retry: "ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ",
    back: "ਪਿੱਛੇ",
    next: "ਅੱਗੇ",
    submit: "ਜਮ੍ਹਾਂ ਕਰੋ",
    start: "ਸ਼ੁਰੂ ਕਰੋ",
    save_changes: "ਤਬਦੀਲੀਆਂ ਸੰਭਾਲੋ",

    // Demographic & Profile
    yrs: "ਸਾਲ",
    gender_male: "ਪੁਰਸ਼",
    gender_female: "ਔਰਤ",
    gender_other: "ਹੋਰ",
    patient: "ਮਰੀਜ਼",
    age_not_set: "ਉਮਰ ਦਰਜ ਨਹੀਂ",
    gender_not_set: "ਲਿੰਗ ਦਰਜ ਨਹੀਂ",
    height_not_set: "ਕੱਦ ਦਰਜ ਨਹੀਂ",
    weight_not_set: "ਭਾਰ ਦਰਜ ਨਹੀਂ",
    height: "ਕੱਦ",
    weight: "ਭਾਰ",
    lang_en: "ਅੰਗਰੇਜ਼ੀ",
    lang_hi: "ਹਿੰਦੀ",
    lang_bn: "ਬੰਗਾਲੀ",
    lang_ta: "ਤਾਮਿਲ",
    lang_te: "ਤੇਲਗੂ",
    lang_mr: "ਮਰਾਠੀ",
    lang_gu: "ਗੁਜਰਾਤੀ",
    lang_kn: "ਕੰਨੜ",
    lang_ml: "ਮਲਿਆਲਮ",
    lang_pa: "ਪੰਜਾਬੀ",

    // Dates & Times
    today: "ਅੱਜ",
    yesterday: "ਕੱਲ੍ਹ (ਬੀਤਿਆ)",
    tomorrow: "ਕੱਲ੍ਹ (ਆਉਣ ਵਾਲਾ)",
    last_updated: "ਆਖਰੀ ਅੱਪਡੇਟ",
    previous: "ਪਿਛਲਾ",
    context: "ਸੰਦਰਭ",
    fasting: "ਖਾਲੀ ਪੇਟ (Fasting)",
    post_meal: "ਖਾਣੇ ਤੋਂ ਬਾਅਦ (Post-meal)",
    random: "ਆਮ (Random)",
    no_data: "ਕੋਈ ਡਾਟਾ ਨਹੀਂ",
    no_readings_yet: "ਅਜੇ ਕੋਈ ਰੀਡਿੰਗ ਨਹੀਂ ਹੈ",
    current_reading: "ਮੌਜੂਦਾ ਰੀਡਿੰਗ",

    // Vitals & Classification
    blood_pressure_label: "ਬਲੱਡ ਪ੍ਰੈਸ਼ਰ (BP)",
    blood_sugar_label: "ਬਲੱਡ ਸ਼ੂਗਰ",
    heart_rate_label: "ਦਿਲ ਦੀ ਧੜਕਣ",
    usual_range: "ਆਮ ਸੀਮਾ",
    recorded: "ਦਰਜ ਕੀਤਾ ਗਿਆ",
    high: "ਉੱਚਾ",
    low: "ਘੱਟ",
    stable: "ਸਥਿਰ",
    higher_than_last: "ਪਿਛਲੀ ਵਾਰ ਨਾਲੋਂ ਵੱਧ",
    lower_than_last: "ਪਿਛਲੀ ਵਾਰ ਨਾਲੋਂ ਘੱਟ",

    // Reminders & Routine
    daily_health_routine: "ਰੋਜ਼ਾਨਾ ਸਿਹਤ ਰੀਮਾਈਂਡਰ ਅਤੇ ਰੁਟੀਨ",
    medicine_reminders: "ਦਵਾਈ ਰੀਮਾਈਂਡਰ",
    prescriptions_doses: "ਨੁਸਖੇ ਅਤੇ ਨਿਰਧਾਰਤ ਖੁਰਾਕਾਂ",
    active: "ਸਰਗਰਮ",
    taken: "ਲਈ ਗਈ",
    take_dose: "ਖੁਰਾਕ ਲਵੋ",
    no_meds_scheduled: "ਅੱਜ ਲਈ ਕੋਈ ਦਵਾਈ ਨਿਰਧਾਰਤ ਨਹੀਂ ਹੈ।",
    upload_rx_import: "ਦਵਾਈਆਂ ਜੋੜਨ ਲਈ ਨੁਸਖਾ (Rx) ਅੱਪਲੋਡ ਕਰੋ →",
    track_logs_reminders: "ਰੀਮਾਈਂਡਰਾਂ ਵਿੱਚ ਲੌਗ ਵੇਖੋ",
    manage_reminders: "ਸਾਰੇ ਰੀਮਾਈਂਡਰ ਪ੍ਰਬੰਧਿਤ ਕਰੋ →",

    // Yoga
    todays_yoga: "ਅੱਜ ਦਾ ਯੋਗਾ ਅਭਿਆਸ",
    yoga_subtitle: "ਡਾਕਟਰ ਦੁਆਰਾ ਨਿਰਧਾਰਤ ਅਤੇ AI ਕੋਚ",
    done: "ਪੂਰਾ ਹੋਇਆ",
    check_pose: "ਮੁਦਰਾ ਦੀ ਜਾਂਚ ਕਰੋ",
    mark_done: "ਪੂਰਾ ਚਿੰਨ੍ਹਿਤ ਕਰੋ",
    body_pointer_hint: "ਬਾਡੀ ਪੁਆਇੰਟਰ ਫੀਡਬੈਕ ਨਾਲ ਮੁਦਰਾ ਬਣਾਓ",
    full_yoga_routine: "ਪੂਰਾ ਯੋਗਾ ਰੁਟੀਨ →",
    daily: "ਰੋਜ਼ਾਨਾ",
    morning: "ਸਵੇਰੇ",
    evening: "ਸ਼ਾਮ",
    min: "ਮਿੰਟ",

    // Personalized Nutrition & BMI
    nutrition_needs: "ਵਿਅਕਤੀਗਤ ਪੋਸ਼ਣ ਅਤੇ ਕੈਲੋਰੀ ਲੋੜਾਂ",
    nutrition_subtitle: "ਤੁਹਾਡੇ ਕੱਦ, ਭਾਰ ਅਤੇ BMI ਤੋਂ ਗਣਨਾ ਕੀਤੀ ਗਈ",
    bmi_label: "ਬਾਡੀ ਮਾਸ ਇੰਡੈਕਸ (BMI)",
    normal_weight: "ਆਮ ਭਾਰ",
    underweight: "ਘੱਟ ਭਾਰ",
    overweight: "ਜ਼ਿਆਦਾ ਭਾਰ",
    obese: "ਮੋਟਾਪਾ",
    target_calories: "ਰੋਜ਼ਾਨਾ ਨਿਸ਼ਾਨਾ ਕੈਲੋਰੀਆਂ",
    kcal_day: "ਕਿਲੋ ਕੈਲੋਰੀ / ਦਿਨ",
    clinical_goal: "ਕਲੀਨਿਕਲ ਟੀਚਾ",
    goal_maintenance: "ਸਰਵੋਤਮ ਰੱਖ-ਰਖਾਅ ਅਤੇ ਊਰਜਾ",
    goal_surplus: "ਕੈਲੋਰੀ ਵਾਧਾ ਅਤੇ ਮਾਸਪੇਸ਼ੀ ਨਿਰਮਾਣ",
    goal_balanced: "ਸੰਤੁਲਿਤ ਰੱਖ-ਰਖਾਅ ਅਤੇ ਮੈਟਾਬੋਲਿਕ ਸਿਹਤ",
    goal_deficit: "ਦਰਮਿਆਨੀ ਘਾਟ ਅਤੇ ਚਰਬੀ ਘਟਾਉਣਾ",
    goal_reset: "ਮੈਟਾਬੋਲਿਕ ਰੀਸੈਟ ਅਤੇ ਸੋਜ-ਵਿਰੋਧੀ ਖੁਰਾਕ",
    hydration_fiber: "ਰੋਜ਼ਾਨਾ ਪਾਣੀ ਅਤੇ ਫਾਈਬਰ",
    water_intake: "ਪਾਣੀ ਦਾ ਸੇਵਨ",
    dietary_fiber: "ਖੁਰਾਕੀ ਫਾਈਬਰ",
    macronutrient_split: "ਮੈਕਰੋਨਿਊਟ੍ਰੀਐਂਟ ਟੀਚਾ ਵੰਡ (ਸਰੀਰ ਦੀ ਬਣਤਰ ਅਨੁਸਾਰ):",
    protein: "ਪ੍ਰੋਟੀਨ",
    protein_desc: "ਮਾਸਪੇਸ਼ੀਆਂ ਦੀ ਮੁਰੰਮਤ ਅਤੇ ਸੰਤੁਸ਼ਟੀ",
    complex_carbs: "ਕੰਪਲੈਕਸ ਕਾਰਬਸ",
    carbs_desc: "ਸਾਬਤ ਅਨਾਜ, ਦਾਲਾਂ ਅਤੇ ਨਿਰੰਤਰ ਊਰਜਾ",
    healthy_fats: "ਸਿਹਤਮੰਦ ਚਰਬੀ",
    fats_desc: "ਹਾਰਮੋਨ ਉਤਪਾਦਨ ਅਤੇ ਜੋੜਾਂ ਦੀ ਸਿਹਤ",
    key_micronutrients: "ਤੁਹਾਡੇ BMI ਪ੍ਰੋਫਾਈਲ ਲਈ ਲੋੜੀਂਦੇ ਮੁੱਖ ਸੂਖਮ ਪੌਸ਼ਟਿਕ ਤੱਤ:",
    height_weight_prompt_title: "ਪੋਸ਼ਣ ਦੀ ਗਣਨਾ ਲਈ ਕੱਦ ਅਤੇ ਭਾਰ ਦਰਜ ਕਰੋ",
    height_weight_prompt_desc: "ਆਪਣਾ ਸਹੀ BMI, ਰੋਜ਼ਾਨਾ ਕੈਲੋਰੀ ਟੀਚਾ ਅਤੇ ਪੌਸ਼ਟਿਕ ਤੱਤਾਂ ਦੀ ਸੂਚੀ ਵੇਖਣ ਲਈ ਪ੍ਰੋਫਾਈਲ ਵਿੱਚ ਕੱਦ ਅਤੇ ਭਾਰ ਦਰਜ ਕਰੋ।",
    enter_height_weight_btn: "ਪ੍ਰੋਫਾਈਲ ਵਿੱਚ ਕੱਦ ਅਤੇ ਭਾਰ ਦਰਜ ਕਰੋ →",

    // Clinical Summary
    clinical_summary: "ਮੌਜੂਦਾ ਕਲੀਨਿਕਲ ਸਾਰਾਂਸ਼",
    latest_diagnosis: "ਤਾਜ਼ਾ ਨਿਦਾਨ",
    recent_concern: "ਹਾਲੀਆ ਚਿੰਤਾ",
    no_clinical_summary: "ਅਜੇ ਕੋਈ ਕਲੀਨਿਕਲ ਸਾਰਾਂਸ਼ ਨਹੀਂ ਹੈ। ਇਸਨੂੰ ਬਣਾਉਣ ਲਈ ਆਪਣਾ ਮੈਡੀਕਲ ਇਤਿਹਾਸ ਦਰਜ ਕਰੋ।",

    // Quick Action Subtitles
    chat_subtitle_short: "ਕਲੀਨਿਕਲ ਸਵਾਲ ਪੁੱਛੋ",
    exercise_desc: "ਰੋਜ਼ਾਨਾ ਚੈੱਕਲਿਸਟ ਅਤੇ ਯੋਗਾ ਕੋਚ",
    record_history_desc: "ਆਵਾਜ਼ ਜਾਂ ਟੈਕਸਟ ਦੁਆਰਾ ਜਵਾਬ ਦਿਓ",
    upload_docs_desc: "ਨੁਸਖਾ ਜਾਂ ਲੈਬ ਰਿਪੋਰਟ ਸ਼ਾਮਲ ਕਰੋ",
    tracker_desc: "ਬਲੱਡ ਪ੍ਰੈਸ਼ਰ, ਸ਼ੂਗਰ ਅਤੇ ਮਹੱਤਵਪੂਰਨ ਸੰਕੇਤ",
    reminders_desc: "ਦਵਾਈ ਅਤੇ ਜੀਵਨ ਸ਼ੈਲੀ ਦੇ ਅਲਾਰਮ ਸੈੱਟ ਕਰੋ",

    // Lists & Appointments
    recent_medical_history: "ਹਾਲੀਆ ਮੈਡੀਕਲ ਇਤਿਹਾਸ",
    no_medical_history: "ਅਜੇ ਕੋਈ ਮੈਡੀਕਲ ਇਤਿਹਾਸ ਦਰਜ ਨਹੀਂ ਹੈ।",
    recent_health_readings: "ਹਾਲੀਆ ਸਿਹਤ ਰੀਡਿੰਗ",
    no_health_readings: "ਅਜੇ ਕੋਈ ਸਿਹਤ ਰੀਡਿੰਗ ਉਪਲਬਧ ਨਹੀਂ ਹੈ।",
    upcoming_appointments: "ਆਗਾਮੀ ਡਾਕਟਰ ਅਪਾਇੰਟਮੈਂਟਾਂ",
    doctor: "ਡਾਕਟਰ",
    status_booked: "ਬੁੱਕ ਕੀਤਾ ਗਿਆ",
    status_in_progress: "ਸਲਾਹ-ਮਸ਼ਵਰਾ ਜਾਰੀ ਹੈ",
    status_completed: "ਪੂਰਾ ਹੋਇਆ",
    status_cancelled: "ਰੱਦ ਕੀਤਾ ਗਿਆ",
  },
};

const LANG_KEY = "patient_preferred_language";

export function LanguageProvider({ children }) {
  const { patient, isAuthenticated, role } = useAuth();

  const [language, setLanguageState] = useState(() => {
    return localStorage.getItem(LANG_KEY) || patient?.preferredLanguage || "en";
  });

  // Sync if patient profile has a language preference
  useEffect(() => {
    if (patient?.preferredLanguage && patient.preferredLanguage !== language) {
      setLanguageState(patient.preferredLanguage);
      localStorage.setItem(LANG_KEY, patient.preferredLanguage);
    }
  }, [patient?.preferredLanguage]);

  // Set document language
  useEffect(() => {
    document.documentElement.lang = language;
    localStorage.setItem(LANG_KEY, language);
  }, [language]);

  const setLanguage = async (newLang) => {
    setLanguageState(newLang);
    localStorage.setItem(LANG_KEY, newLang);
    document.documentElement.lang = newLang;

    // If logged in as patient, persist to database
    if (isAuthenticated && role === "patient") {
      try {
        await updateCurrentPatient({ preferredLanguage: newLang });
      } catch (err) {
        console.warn("[LanguageProvider] Could not sync language to backend:", err?.message);
      }
    }
  };

  const t = (key, fallback = "") => {
    const bundle = TRANSLATIONS[language] || TRANSLATIONS.en;
    if (bundle && bundle[key] !== undefined) {
      return bundle[key];
    }
    // Fallback to English
    if (TRANSLATIONS.en && TRANSLATIONS.en[key] !== undefined) {
      return TRANSLATIONS.en[key];
    }
    return fallback || key;
  };

  const activeLangMeta = useMemo(() => {
    return SUPPORTED_LANGUAGES.find((l) => l.code === language) || SUPPORTED_LANGUAGES[0];
  }, [language]);

  const value = useMemo(
    () => ({
      language,
      setLanguage,
      t,
      languages: SUPPORTED_LANGUAGES,
      activeLanguage: activeLangMeta,
    }),
    [language, activeLangMeta],
  );

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
