import { createContext, useContext, useEffect, useMemo, useState } from "react";
import { useAuth } from "./AuthContext.jsx";
import { updateCurrentPatient } from "../api/auth.js";

const LanguageContext = createContext(null);

export const SUPPORTED_LANGUAGES = [
  { code: "en", name: "English", nativeName: "English" },
  { code: "hi", name: "Hindi", nativeName: "हिन्दी" },
  { code: "bn", name: "Bengali", nativeName: "বাংলা" },
  { code: "ta", name: "Tamil", nativeName: "தமிழ்" },
  { code: "te", name: "Telugu", nativeName: "తెలుగు" },
  { code: "mr", name: "Marathi", nativeName: "मराठी" },
  { code: "gu", name: "Gujarati", nativeName: "ગુજરાતી" },
  { code: "kn", name: "Kannada", nativeName: "ಕನ್ನಡ" },
  { code: "ml", name: "Malayalam", nativeName: "മലയാളം" },
  { code: "pa", name: "Punjabi", nativeName: "ਪੰਜਾਬੀ" },
];

export const TRANSLATIONS = {
  en: {
    // Nav & Shell
    care: "Care",
    dashboard: "Dashboard",
    medical_records: "Medical Records",
    ai_health_assistant: "AI Health Assistant",
    upload_documents: "Upload Documents",
    book_appointment: "Book Appointment",
    daily_routine: "Daily routine",
    health_tracker: "Health Tracker",
    exercise_yoga: "Exercise & Yoga",
    ayurvedic_care: "Ayurvedic Care",
    reminders: "Reminders",
    account: "Account",
    profile: "Profile",
    patient_workspace: "Patient workspace",
    signed_in: "Signed in",
    logout: "Logout",
    menu: "Menu",
    high_contrast: "High contrast",
    standard_view: "Standard view",
    language: "Language",
    select_language: "Select Language",

    // Dashboard
    welcome_back: "Welcome back",
    hello: "Hello",
    health_overview: "Your complete health history — sessions, reports, and uploads.",
    quick_actions: "Quick Actions",
    talk_to_ai: "Talk to AI Assistant",
    record_history: "Record History",
    view_records: "View Records",
    vitals_summary: "Vitals Summary",
    heart_rate: "Heart Rate",
    blood_pressure: "Blood Pressure",
    blood_glucose: "Blood Glucose",
    bmi_weight: "BMI & Weight",
    spo2: "Oxygen (SpO2)",
    recent_prescriptions: "Recent Prescriptions",
    upcoming_appointments: "Upcoming Appointments",
    no_prescriptions: "No prescriptions yet",
    no_appointments: "No upcoming appointments",

    // Chat
    chat_title: "AI Health Assistant",
    chat_subtitle: "Ask about your prescriptions, symptom guidance, Ayurvedic lifestyle tips, and exercises.",
    new_chat: "+ New chat",
    conversations: "Conversations",
    type_message: "Ask a health question in your language…",
    send: "Send",
    thinking: "AI Assistant is thinking…",
    chat_disclaimer: "AI assistant provides guidance, not final medical diagnosis. In an emergency, contact a hospital immediately.",
    emergency_detected: "Emergency symptoms detected. Please seek emergency medical care immediately.",
    suggestion_rx: "Explain my prescription in simple words",
    suggestion_remedies: "Ayurvedic home remedies for cold & cough",
    suggestion_exercise: "Recommend safe morning yoga for me",
    suggestion_diet: "What healthy foods should I eat today?",
    no_previous_chats: "No previous chats",
    start_first_chat: "Start your first conversation with your AI Health Companion.",

    // Medical Records
    records_title: "Medical Records",
    records_subtitle: "Your complete health history — sessions, reports, and uploads.",
    add_medical_data: "Add medical data",
    record_new_history: "Record new history",
    upload_a_document: "Upload a document",
    view_read_rx: "View & Read Prescription",
    download_print_pdf: "Download / Print PDF",
    official_rx: "Official Rx",
    lab_report: "Lab Report",
    history_session: "History session",
    prescribed_by: "Prescribed by",
    medicines: "Medicines",
    advice: "Advice",
    yoga_lifestyle: "Yoga / Lifestyle",
    view_document: "View document →",
    view_full_history: "View full history →",
    continue_recording: "Continue recording →",
    no_records: "No health records yet. Start by recording your first history or uploading a document.",

    // Common
    save: "Save",
    cancel: "Cancel",
    close: "Close",
    loading: "Loading…",
    error: "Error",
    retry: "Retry",
    back: "Back",
    next: "Next",
    submit: "Submit",
    start: "Start",
    save_changes: "Save changes",

    // Demographic & Profile
    yrs: "yrs",
    gender_male: "Male",
    gender_female: "Female",
    gender_other: "Other",
    patient: "Patient",
    age_not_set: "Age not set",
    gender_not_set: "Gender not set",
    height_not_set: "Height not set",
    weight_not_set: "Weight not set",
    height: "Height",
    weight: "Weight",
    lang_en: "English",
    lang_hi: "Hindi",
    lang_bn: "Bengali",
    lang_ta: "Tamil",
    lang_te: "Telugu",
    lang_mr: "Marathi",
    lang_gu: "Gujarati",
    lang_kn: "Kannada",
    lang_ml: "Malayalam",
    lang_pa: "Punjabi",

    // Dates & Times
    today: "Today",
    yesterday: "Yesterday",
    tomorrow: "Tomorrow",
    last_updated: "Last updated",
    previous: "Previous",
    context: "Context",
    fasting: "Fasting",
    post_meal: "Post meal",
    random: "Random",
    no_data: "No data",
    no_readings_yet: "No readings yet",
    current_reading: "Current reading",

    // Vitals & Classification
    blood_pressure_label: "Blood pressure",
    blood_sugar_label: "Blood sugar",
    heart_rate_label: "Heart rate",
    usual_range: "Usual range",
    recorded: "Recorded",
    high: "High",
    low: "Low",
    stable: "Stable",
    higher_than_last: "Higher than last time",
    lower_than_last: "Lower than last time",

    // Reminders & Routine
    daily_health_routine: "Daily Health Reminders & Routine",
    medicine_reminders: "Medicine Reminders",
    prescriptions_doses: "Prescriptions & Scheduled Doses",
    active: "Active",
    taken: "Taken",
    take_dose: "Take Dose",
    no_meds_scheduled: "No medicines scheduled for today.",
    upload_rx_import: "Upload prescription to import medicines →",
    track_logs_reminders: "Track logs in Reminders",
    manage_reminders: "Manage All Reminders →",

    // Yoga
    todays_yoga: "Today's Yoga Matrix",
    yoga_subtitle: "Doctor-Prescribed & AI Form Coach",
    done: "Done",
    check_pose: "Check Pose",
    mark_done: "Mark Done",
    body_pointer_hint: "Hold postures with body pointer feedback",
    full_yoga_routine: "Full Yoga Matrix & Routine →",
    daily: "Daily",
    morning: "Morning",
    evening: "Evening",
    min: "min",

    // Personalized Nutrition & BMI
    nutrition_needs: "Personalized Nutrition & Caloric Needs",
    nutrition_subtitle: "Computed from your Height, Weight & BMI",
    bmi_label: "Body Mass Index (BMI)",
    normal_weight: "Normal Weight",
    underweight: "Underweight",
    overweight: "Overweight",
    obese: "Obese",
    target_calories: "Target Daily Calories",
    kcal_day: "kcal / day",
    clinical_goal: "Clinical Goal",
    goal_maintenance: "Optimal Maintenance & Vitality",
    goal_surplus: "Calorie Surplus & Muscle Building",
    goal_balanced: "Balanced Maintenance & Metabolic Health",
    goal_deficit: "Moderate Deficit & Active Fat Loss",
    goal_reset: "Metabolic Reset & Anti-Inflammatory Deficit",
    hydration_fiber: "Daily Hydration & Fiber",
    water_intake: "Water intake",
    dietary_fiber: "Dietary fiber",
    macronutrient_split: "Macronutrient Target Split (Based on Body Composition):",
    protein: "Protein",
    protein_desc: "Lean muscle repair & metabolic satiety",
    complex_carbs: "Complex Carbs",
    carbs_desc: "Whole grains, pulses & sustained yoga energy",
    healthy_fats: "Healthy Fats",
    fats_desc: "Hormone production & joint lubrication",
    key_micronutrients: "Key Micronutrients Required for Your BMI Profile:",
    height_weight_prompt_title: "Set Your Height & Weight to Calculate Nutrients",
    height_weight_prompt_desc: "Enter your biometric parameters in your profile to view your exact Body Mass Index (BMI), personalized daily caloric target, macronutrient distribution, and micronutrient checklist.",
    enter_height_weight_btn: "Enter Height & Weight in Profile →",

    // Clinical Summary
    clinical_summary: "Current Clinical Summary",
    latest_diagnosis: "Latest diagnosis",
    recent_concern: "Recent concern",
    no_clinical_summary: "No clinical summary yet. Record your medical history to build one.",

    // Quick Action Subtitles
    chat_subtitle_short: "Ask a clinical question",
    exercise_desc: "Daily to-do checklist & CV pose coach",
    record_history_desc: "Answer questions by voice or text",
    upload_docs_desc: "Add a prescription or lab report",
    tracker_desc: "Blood pressure, sugar & vitals",
    reminders_desc: "Set custom medicine & lifestyle alarms",

    // Lists & Appointments
    recent_medical_history: "Recent Medical History",
    no_medical_history: "No medical history recorded yet.",
    recent_health_readings: "Recent Health Readings",
    no_health_readings: "No health readings available yet.",
    upcoming_appointments: "Upcoming Doctor Appointments",
    doctor: "Doctor",
    status_booked: "Booked",
    status_in_progress: "In Consultation",
    status_completed: "Completed",
    status_cancelled: "Cancelled",
  },

  hi: {
    // Nav & Shell
    care: "स्वास्थ्य सेवा",
    dashboard: "डैशबोर्ड",
    medical_records: "मेडिकल रिकॉर्ड्स",
    ai_health_assistant: "एआई स्वास्थ्य सहायक",
    upload_documents: "दस्तावेज़ अपलोड",
    book_appointment: "अपॉइंटमेंट बुक करें",
    daily_routine: "दैनिक दिनचर्या",
    health_tracker: "स्वास्थ्य ट्रैकर",
    exercise_yoga: "व्यायाम और योग",
    ayurvedic_care: "आयुर्वेदिक देखभाल",
    reminders: "दवा रिमाइंडर",
    account: "खाता",
    profile: "प्रोफ़ाइल",
    patient_workspace: "मरीज़ पोर्टल",
    signed_in: "लॉग इन हैं",
    logout: "लॉगआउट",
    menu: "मेनू",
    high_contrast: "उच्च कंट्रास्ट",
    standard_view: "सामान्य दृश्य",
    language: "भाषा",
    select_language: "भाषा चुनें",

    // Dashboard
    welcome_back: "वापसी पर स्वागत है",
    hello: "नमस्ते",
    health_overview: "आपका सम्पूर्ण स्वास्थ्य इतिहास — सत्र, रिपोर्ट और परामर्श।",
    quick_actions: "त्वरित क्रियाएं",
    talk_to_ai: "एआई सहायक से बात करें",
    record_history: "इतिहास रिकॉर्ड करें",
    view_records: "रिकॉर्ड्स देखें",
    vitals_summary: "वाइटल्स सारांश",
    heart_rate: "हृदय गति",
    blood_pressure: "रक्तचाप (BP)",
    blood_glucose: "ब्लड शुगर",
    bmi_weight: "बीएमआई और वजन",
    spo2: "ऑक्सीजन (SpO2)",
    recent_prescriptions: "हाल के नुस्खे (Prescriptions)",
    upcoming_appointments: "आगामी अपॉइंटमेंट्स",
    no_prescriptions: "अभी कोई नुस्खा नहीं है",
    no_appointments: "कोई आगामी अपॉइंटमेंट नहीं",

    // Chat
    chat_title: "एआई स्वास्थ्य सहायक",
    chat_subtitle: "अपने नुस्खे, लक्षण मार्गदर्शन, आयुर्वेदिक उपाय और व्यायाम के बारे में पूछें।",
    new_chat: "+ नई बातचीत",
    conversations: "पिछली बातचीत",
    type_message: "अपनी भाषा में स्वास्थ्य सम्बन्धी सवाल पूछें…",
    send: "भेजें",
    thinking: "एआई सहायक सोच रहा है…",
    chat_disclaimer: "एआई सहायक केवल स्वास्थ्य मार्गदर्शन देता है, यह डॉक्टर का विकल्प नहीं है। आपातकाल में तुरंत अस्पताल जाएं।",
    emergency_detected: "आपातकालीन लक्षण पाए गए। कृपया तुरंत आपातकालीन चिकित्सा सहायता लें।",
    suggestion_rx: "मेरे नुस्खे को सरल शब्दों में समझाएं",
    suggestion_remedies: "खांसी और जुकाम के आयुर्वेदिक घरेलू नुस्खे",
    suggestion_exercise: "मेरे लिए सुबह का सुरक्षित योग सुझाएं",
    suggestion_diet: "मुझे आज स्वस्थ रहने के लिए क्या खाना चाहिए?",
    no_previous_chats: "कोई पिछली बातचीत नहीं",
    start_first_chat: "अपने एआई स्वास्थ्य साथी के साथ पहली बातचीत शुरू करें।",

    // Medical Records
    records_title: "मेडिकल रिकॉर्ड्स",
    records_subtitle: "आपका सम्पूर्ण स्वास्थ्य इतिहास — सत्र, रिपोर्ट और अपलोड।",
    add_medical_data: "मेडिकल डेटा जोड़ें",
    record_new_history: "नया इतिहास दर्ज करें",
    upload_a_document: "दस्तावेज़ अपलोड करें",
    view_read_rx: "नुस्खा देखें और पढ़ें",
    download_print_pdf: "पीडीएफ डाउनलोड / प्रिंट करें",
    official_rx: "आधिकारिक नुस्खा",
    lab_report: "लैब रिपोर्ट",
    history_session: "इतिहास सत्र",
    prescribed_by: "द्वारा निर्धारित",
    medicines: "दवाइयां",
    advice: "सलाह",
    yoga_lifestyle: "योग / जीवनशैली",
    view_document: "दस्तावेज़ देखें →",
    view_full_history: "पूर्ण इतिहास देखें →",
    continue_recording: "रिकॉर्डिंग जारी रखें →",
    no_records: "अभी कोई रिकॉर्ड नहीं है। नया इतिहास दर्ज करके या रिपोर्ट अपलोड करके शुरुआत करें।",

    // Common
    save: "सुरक्षित करें",
    cancel: "रद्द करें",
    close: "बंद करें",
    loading: "लोड हो रहा है…",
    error: "त्रुटि",
    retry: "पुनः प्रयास करें",
    back: "पीछे",
    next: "आगे",
    submit: "जमा करें",
    start: "शुरू करें",
    save_changes: "बदलाव सुरक्षित करें",

    // Demographic & Profile
    yrs: "वर्ष",
    gender_male: "पुरुष",
    gender_female: "महिला",
    gender_other: "अन्य",
    patient: "मरीज़",
    age_not_set: "उम्र दर्ज नहीं",
    gender_not_set: "लिंग दर्ज नहीं",
    height_not_set: "ऊंचाई दर्ज नहीं",
    weight_not_set: "वजन दर्ज नहीं",
    height: "ऊंचाई",
    weight: "वजन",
    lang_en: "अंग्रेज़ी",
    lang_hi: "हिन्दी",
    lang_bn: "बंगाली",
    lang_ta: "तमिल",
    lang_te: "तेलुगु",
    lang_mr: "मराठी",
    lang_gu: "गुजराती",
    lang_kn: "कन्नड़",
    lang_ml: "मलयालम",
    lang_pa: "पंजाबी",

    // Dates & Times
    today: "आज",
    yesterday: "कल",
    tomorrow: "कल (आने वाला)",
    last_updated: "अंतिम अपडेट",
    previous: "पिछला",
    context: "संदर्भ",
    fasting: "खाली पेट (Fasting)",
    post_meal: "भोजन के बाद (Post-meal)",
    random: "सामान्य (Random)",
    no_data: "कोई डेटा नहीं",
    no_readings_yet: "अभी कोई रीडिंग नहीं है",
    current_reading: "वर्तमान रीडिंग",

    // Vitals & Classification
    blood_pressure_label: "रक्तचाप (BP)",
    blood_sugar_label: "ब्लड शुगर",
    heart_rate_label: "हृदय गति",
    usual_range: "सामान्य सीमा",
    recorded: "दर्ज किया गया",
    high: "उच्च",
    low: "निम्न",
    stable: "स्थिर",
    higher_than_last: "पिछली बार से अधिक",
    lower_than_last: "पिछली बार से कम",

    // Reminders & Routine
    daily_health_routine: "दैनिक स्वास्थ्य रिमाइंडर और दिनचर्या",
    medicine_reminders: "दवा रिमाइंडर",
    prescriptions_doses: "दवाइयां और निर्धारित खुराक",
    active: "सक्रिय",
    taken: "ली गई",
    take_dose: "खुराक लें",
    no_meds_scheduled: "आज के लिए कोई दवा निर्धारित नहीं है।",
    upload_rx_import: "दवाइयां जोड़ने के लिए नुस्खा (Rx) अपलोड करें →",
    track_logs_reminders: "रिमाइंडर में लॉग देखें",
    manage_reminders: "सभी रिमाइंडर प्रबंधित करें →",

    // Yoga
    todays_yoga: "आज का योग अभ्यास",
    yoga_subtitle: "डॉक्टर द्वारा निर्धारित और एआई कोच",
    done: "पूर्ण",
    check_pose: "मुद्रा जांचें",
    mark_done: "पूर्ण चिह्नित करें",
    body_pointer_hint: "बॉडी पॉइंटर फीडबैक के साथ मुद्रा बनाएं",
    full_yoga_routine: "पूरा योग कार्यक्रम →",
    daily: "दैनिक",
    morning: "सुबह",
    evening: "शाम",
    min: "मिनट",

    // Personalized Nutrition & BMI
    nutrition_needs: "व्यक्तिगत पोषण और कैलोरी आवश्यकताएं",
    nutrition_subtitle: "आपकी ऊंचाई, वजन और बीएमआई से गणना की गई",
    bmi_label: "बॉडी मास इंडेक्स (BMI)",
    normal_weight: "सामान्य वजन",
    underweight: "कम वजन",
    overweight: "अधिक वजन",
    obese: "मोटापा",
    target_calories: "दैनिक लक्षित कैलोरी",
    kcal_day: "किलो कैलोरी / दिन",
    clinical_goal: "नैदानिक लक्ष्य",
    goal_maintenance: "इष्टतम रखरखाव और जीवन शक्ति",
    goal_surplus: "कैलोरी वृद्धि और मांसपेशी निर्माण",
    goal_balanced: "संतुलित रखरखाव और चयापचय स्वास्थ्य",
    goal_deficit: "मध्यम वसा कमी और फैट लॉस",
    goal_reset: "मेटाबोलिक रीसेट और सूजन-रोधी आहार",
    hydration_fiber: "दैनिक जल और फाइबर",
    water_intake: "पानी का सेवन",
    dietary_fiber: "आहार फाइबर",
    macronutrient_split: "मैक्रोन्यूट्रिएंट लक्षित विभाजन (शारीरिक संरचना अनुसार):",
    protein: "प्रोटीन",
    protein_desc: "मांसपेशियों की मरम्मत और तृप्ति",
    complex_carbs: "जटिल कार्ब्स",
    carbs_desc: "साबुत अनाज, दालें और निरंतर ऊर्जा",
    healthy_fats: "स्वस्थ वसा",
    fats_desc: "हार्मोन निर्माण और जोड़ों का स्वास्थ्य",
    key_micronutrients: "आपके बीएमआई प्रोफाइल के लिए आवश्यक प्रमुख सूक्ष्म पोषक तत्व:",
    height_weight_prompt_title: "पोषण की गणना के लिए ऊंचाई और वजन दर्ज करें",
    height_weight_prompt_desc: "अपना सटीक बीएमआई (BMI), दैनिक कैलोरी लक्ष्य, और पोषक तत्वों की सूची देखने के लिए प्रोफ़ाइल में अपनी ऊंचाई और वजन दर्ज करें।",
    enter_height_weight_btn: "प्रोफ़ाइल में ऊंचाई और वजन दर्ज करें →",

    // Clinical Summary
    clinical_summary: "वर्तमान नैदानिक सारांश",
    latest_diagnosis: "नवीनतम निदान",
    recent_concern: "हालिया समस्या",
    no_clinical_summary: "अभी कोई नैदानिक सारांश नहीं है। इसे बनाने के लिए अपना मेडिकल इतिहास दर्ज करें।",

    // Quick Action Subtitles
    chat_subtitle_short: "चिकित्सीय प्रश्न पूछें",
    exercise_desc: "दैनिक चेकलिस्ट और योग कोच",
    record_history_desc: "आवाज या टेक्स्ट से प्रश्नों के उत्तर दें",
    upload_docs_desc: "पर्चा या लैब रिपोर्ट जोड़ें",
    tracker_desc: "रक्तचाप, शुगर और महत्वपूर्ण संकेत",
    reminders_desc: "दवा और जीवनशैली अलार्म सेट करें",

    // Lists & Appointments
    recent_medical_history: "हालिया चिकित्सा इतिहास",
    no_medical_history: "अभी कोई मेडिकल इतिहास दर्ज नहीं है।",
    recent_health_readings: "हालिया स्वास्थ्य रीडिंग",
    no_health_readings: "अभी कोई स्वास्थ्य रीडिंग उपलब्ध नहीं है।",
    upcoming_appointments: "आगामी डॉक्टर अपॉइंटमेंट्स",
    doctor: "डॉक्टर",
    status_booked: "बुक किया गया",
    status_in_progress: "परामर्श जारी",
    status_completed: "पूर्ण",
    status_cancelled: "रद्द",
  },

  bn: {
    care: "স্বাস্থ্য সেবা",
    dashboard: "ড্যাশবোর্ড",
    medical_records: "মেডিকেল রেকর্ডস",
    ai_health_assistant: "এআই স্বাস্থ্য সহকারী",
    upload_documents: "নথি আপলোড",
    book_appointment: "অ্যাপয়েন্টমেন্ট বুকিং",
    daily_routine: "দৈনন্দিন রুটিন",
    health_tracker: "স্বাস্থ্য ট্র্যাকার",
    exercise_yoga: "ব্যায়াম ও যোগব্যায়াম",
    ayurvedic_care: "আয়ুর্বেদিক সেবা",
    reminders: "ঔষধের অনুস্মারক",
    account: "অ্যাকাউন্ট",
    profile: "প্রোফাইল",
    patient_workspace: "রোগীর পোর্টাল",
    signed_in: "লগ ইন আছেন",
    logout: "লগআউট",
    menu: "মেনু",
    high_contrast: "উচ্চ কনট্রাস্ট",
    standard_view: "সাধারণ দৃশ্য",
    language: "ভাষা",
    select_language: "ভাষা নির্বাচন করুন",
    welcome_back: "স্বাগতম",
    hello: "নমস্কার",
    health_overview: "আপনার সম্পূর্ণ স্বাস্থ্য ইতিহাস — সেশন, রিপোর্ট এবং প্রেসক্রিপশন।",
    quick_actions: "দ্রুত পদক্ষেপ",
    talk_to_ai: "এআই সহকারীর সাথে কথা বলুন",
    record_history: "ইতিহাস রেকর্ড করুন",
    view_records: "রেকর্ড দেখুন",
    vitals_summary: "ভাইটালস সারাংশ",
    heart_rate: "হৃদস্পন্দন",
    blood_pressure: "রক্তচাপ (BP)",
    blood_glucose: "ব্লাড সুগার",
    bmi_weight: "বিএমআই ও ওজন",
    spo2: "অক্সিজেন (SpO2)",
    recent_prescriptions: "সাম্প্রতিক প্রেসক্রিপশন",
    upcoming_appointments: "আসন্ন অ্যাপয়েন্টমেন্ট",
    no_prescriptions: "এখনও কোনো প্রেসক্রিপশন নেই",
    no_appointments: "কোনো আসন্ন অ্যাপয়েন্টমেন্ট নেই",
    chat_title: "এআই স্বাস্থ্য সহকারী",
    chat_subtitle: "আপনার প্রেসক্রিপশন, লক্ষণ, আয়ুর্বেদিক পরামর্শ এবং ব্যায়াম সম্পর্কে জানুন।",
    new_chat: "+ নতুন চ্যাট",
    conversations: "কথোপকথন",
    type_message: "আপনার ভাষায় স্বাস্থ্য সংক্রান্ত প্রশ্ন লিখুন…",
    send: "পাঠান",
    thinking: "এআই চিন্তা করছে…",
    chat_disclaimer: "এআই সহকারী কেবল পরামর্শ দেয়, ডাক্তারের বিকল্প নয়। জরুরি অবস্থায় অবিলম্বে হাসপাতালে যান।",
    emergency_detected: "জরুরি লক্ষণ সনাক্ত হয়েছে। দয়া করে অবিলম্বে জরুরি স্বাস্থ্যসেবা নিন।",
    suggestion_rx: "আমার প্রেসক্রিপশনটি সহজ ভাষায় বুঝিয়ে দিন",
    suggestion_remedies: "সর্দি ও কাশির জন্য আয়ুর্বেদিক ঘরোয়া প্রতিকার",
    suggestion_exercise: "আমার জন্য নিরাপদ সকালের যোগব্যায়াম বলুন",
    suggestion_diet: "সুস্থ থাকতে আজ আমার কী খাওয়া উচিত?",
    no_previous_chats: "কোনো পূর্ববর্তী চ্যাট নেই",
    start_first_chat: "আপনার এআই স্বাস্থ্য সহকারীর সাথে প্রথম আলোচনা শুরু করুন।",
    records_title: "মেডিকেল রেকর্ডস",
    records_subtitle: "আপনার সম্পূর্ণ স্বাস্থ্য ইতিহাস — সেশন, রিপোর্ট এবং আপলোড।",
    add_medical_data: "তথ্য যোগ করুন",
    record_new_history: "নতুন ইতিহাস রেকর্ড করুন",
    upload_a_document: "নথি আপলোড করুন",
    view_read_rx: "প্রেসক্রিপশন পড়ুন",
    download_print_pdf: "পিডিএফ ডাউনলোড / প্রিন্ট",
    official_rx: "অফিসিয়াল প্রেসক্রিপশন",
    lab_report: "ল্যাব রিপোর্ট",
    history_session: "ইতিহাস সেশন",
    prescribed_by: "চিকিৎসক",
    medicines: "ঔষধ",
    advice: "পরামর্শ",
    yoga_lifestyle: "যোগ / জীবনধারা",
    view_document: "নথি দেখুন →",
    view_full_history: "সম্পূর্ণ ইতিহাস →",
    continue_recording: "রেকর্ডিং চালিয়ে যান →",
    no_records: "কোনো রেকর্ড পাওয়া যায়নি।",
    save: "সংরক্ষণ",
    cancel: "বাতিল",
    close: "বন্ধ করুন",
    loading: "লোড হচ্ছে…",
    error: "ত্রুটি",
    retry: "পুনরায় চেষ্টা",
    back: "পিছনে",
    next: "পরবর্তী",
    submit: "জমা দিন",
    start: "শুরু করুন",
    save_changes: "পরিবর্তন সংরক্ষণ করুন",
  },

  ta: {
    care: "சுகாதாரம்",
    dashboard: "முகப்பு",
    medical_records: "மருத்துவ ஆவணங்கள்",
    ai_health_assistant: "AI சுகாதார உதவியாளர்",
    upload_documents: "ஆவண பதிவேற்றம்",
    book_appointment: "முன்பதிவு செய்ய",
    daily_routine: "தினசரி வழக்கம்",
    health_tracker: "உடல்நல கண்காணிப்பாளர்",
    exercise_yoga: "உடற்பயிற்சி & யோகா",
    ayurvedic_care: "ஆயுர்வேத பராமரிப்பு",
    reminders: "மருந்து நினைவூட்டல்",
    account: "கணக்கு",
    profile: "சுயவிவரம்",
    patient_workspace: "நோயாளி தளம்",
    signed_in: "உள்நுழைந்துள்ளீர்கள்",
    logout: "வெளியேறு",
    menu: "மெனு",
    high_contrast: "உயர் மாறுபாடு",
    standard_view: "வழக்கமான பார்வை",
    language: "மொழி",
    select_language: "மொழியைத் தேர்ந்தெடுக்கவும்",
    welcome_back: "நல்வரவு",
    hello: "வணக்கம்",
    health_overview: "உங்கள் முழுமையான மருத்துவ வரலாறு — அமர்வுகள், அறிக்கைகள் மற்றும் பதிவேற்றங்கள்.",
    quick_actions: "விரைவு நடவடிக்கைகள்",
    talk_to_ai: "AI உதவியாளரிடம் பேசுங்கள்",
    record_history: "வரலாறை பதிவு செய்",
    view_records: "ஆவணங்களைப் பார்க்க",
    vitals_summary: "முக்கிய அளவீடுகள்",
    heart_rate: "இதயத் துடிப்பு",
    blood_pressure: "இரத்த அழுத்தம் (BP)",
    blood_glucose: "இரத்த சர்க்கரை",
    bmi_weight: "பிஎம்ஐ & எடை",
    spo2: "ஆக்ஸிஜன் (SpO2)",
    recent_prescriptions: "சமீபத்திய மருந்துக் குறிப்புகள்",
    upcoming_appointments: "வரவிருக்கும் முன்பதிவுகள்",
    no_prescriptions: "மருந்துக் குறிப்புகள் எதுவும் இல்லை",
    no_appointments: "முன்பதிவுகள் எதுவும் இல்லை",
    chat_title: "AI சுகாதார உதவியாளர்",
    chat_subtitle: "உங்கள் மருந்துகள், அறிகுறிகள் மற்றும் ஆயுர்வேத குறிப்புகள் பற்றி கேளுங்கள்.",
    new_chat: "+ புதிய உரையாடல்",
    conversations: "உரையாடல்கள்",
    type_message: "உங்கள் மொழியில் சுகாதார கேள்வியைக் கேளுங்கள்…",
    send: "அனுப்பு",
    thinking: "AI உதவியாளர் சிந்திக்கிறது…",
    chat_disclaimer: "AI உதவியாளர் வழிகாட்டுதலை மட்டுமே வழங்குகிறது. அவசரநிலைக்கு மருத்துவமனையை அணுகவும்.",
    emergency_detected: "அவசர அறிகுறிகள் கண்டறியப்பட்டன. உடனடியாக மருத்துவ உதவியை நாடுங்கள்.",
    suggestion_rx: "எனது மருந்துக் குறிப்பை எளிய முறையில் விளக்குங்கள்",
    suggestion_remedies: "சளி மற்றும் இருமலுக்கான ஆயுர்வேத வீட்டு வைத்தியம்",
    suggestion_exercise: "எனக்கு ஏற்ற யோகாசனங்களை பரிந்துரைக்கவும்",
    suggestion_diet: "நான் இன்று என்ன ஆரோக்கியமான உணவை சாப்பிட வேண்டும்?",
    no_previous_chats: "முந்தைய உரையாடல்கள் இல்லை",
    start_first_chat: "AI மருத்துவ உதவியாளருடன் உரையாடலைத் தொடங்குங்கள்.",
    records_title: "மருத்துவ ஆவணங்கள்",
    records_subtitle: "உங்கள் முழுமையான மருத்துவ வரலாறு — அமர்வுகள் மற்றும் அறிக்கைகள்.",
    add_medical_data: "தரவைச் சேர்க்கவும்",
    record_new_history: "புதிய வரலாறு பதிவு",
    upload_a_document: "ஆவணத்தை பதிவேற்றவும்",
    view_read_rx: "மருந்துக் குறிப்பைப் பார்க்க",
    download_print_pdf: "PDF பதிவிறக்கம் / அச்சிடு",
    official_rx: "அதிகாரப்பூர்வ குறிப்பு",
    lab_report: "பரிசோதனை அறிக்கை",
    history_session: "அமர்வு",
    prescribed_by: "பரிந்துரைத்தவர்",
    medicines: "மருந்துகள்",
    advice: "ஆலோசனை",
    yoga_lifestyle: "யோகா / வாழ்க்கை முறை",
    view_document: "ஆவணத்தைப் பார் →",
    view_full_history: "முழு வரலாறு →",
    continue_recording: "தொடரவும் →",
    no_records: "ஆவணங்கள் எதுவும் இல்லை.",
    save: "சேமிக்க",
    cancel: "ரத்து செய்",
    close: "மூடு",
    loading: "ஏற்றுகிறது…",
    error: "பிழை",
    retry: "மீண்டும் முயல்க",
    back: "பின்னால்",
    next: "அடுத்து",
    submit: "சமர்ப்பிக்கவும்",
    start: "தொடங்கு",
    save_changes: "மாற்றங்களைச் சேமிக்கவும்",
  },

  te: {
    care: "వైద్య సేవలు",
    dashboard: "డ్యాష్‌బోర్డ్",
    medical_records: "వైద్య రికార్డులు",
    ai_health_assistant: "AI ఆరోగ్య సహాయకుడు",
    upload_documents: "పత్రాల అప్‌లోడ్",
    book_appointment: "అపాయింట్‌మెంట్ బుక్ చేయండి",
    daily_routine: "రోజువారీ దినచర్య",
    health_tracker: "ఆరోగ్య ట్రాకర్",
    exercise_yoga: "వ్యాయామం & యోగా",
    ayurvedic_care: "ఆయుర్వేద సంరక్షణ",
    reminders: "మందుల రిమైండర్లు",
    account: "ఖాతా",
    profile: "ప్రొఫైల్",
    patient_workspace: "రోగి కార్యస్థలం",
    signed_in: "లాగిన్ అయ్యారు",
    logout: "లాగ్ అవుట్",
    menu: "మెనూ",
    high_contrast: "అధిక కాంట్రాస్ట్",
    standard_view: "సాధారణ వీక్షణ",
    language: "భాష",
    select_language: "భాషను ఎంచుకోండి",
    welcome_back: "స్వాగతం",
    hello: "నమస్కారం",
    health_overview: "మీ సంపూర్ణ ఆరోగ్య చరిత్ర — నివేదికలు మరియు ప్రిస్క్రిప్షన్లు.",
    quick_actions: "శీఘ్ర చర్యలు",
    talk_to_ai: "AI సహాయకుడితో మాట్లాడండి",
    record_history: "చరిత్రను నమోదు చేయండి",
    view_records: "రికార్డులను చూడండి",
    vitals_summary: "ముఖ్య సంకేతాలు",
    heart_rate: "గుండె వేగం",
    blood_pressure: "రక్తపోటు (BP)",
    blood_glucose: "బ్లడ్ షుగర్",
    bmi_weight: "BMI & బరువు",
    spo2: "ఆక్సిజన్ (SpO2)",
    recent_prescriptions: "ఇటీవలి ప్రిస్క్రిప్షన్లు",
    upcoming_appointments: "రాబోయే అపాయింట్‌మెంట్లు",
    no_prescriptions: "ఇంకా ప్రిస్క్రిప్షన్లు లేవు",
    no_appointments: "రాబోయే అపాయింట్‌మెంట్లు లేవు",
    chat_title: "AI ఆరోగ్య సహాయకుడు",
    chat_subtitle: "మీ ప్రిస్క్రిప్షన్లు, లక్షణాలు మరియు ఆయుర్వేద చిట్కాల గురించి అడగండి.",
    new_chat: "+ కొత్త సంభాషణ",
    conversations: "సంభాషణలు",
    type_message: "మీ భాషలో ఆరోగ్య ప్రశ్నను అడగండి…",
    send: "పంపండి",
    thinking: "AI ఆలోచిస్తోంది…",
    chat_disclaimer: "AI కేవలం మార్గదర్శకత్వం మాత్రమే ఇస్తుంది. అత్యవసర పరిస్థితిలో ఆసుపత్రికి వెళ్లండి.",
    emergency_detected: "అత్యవసర లక్షణాలు గుర్తించబడ్డాయి. తక్షణ వైద్య సహాయం తీసుకోండి.",
    suggestion_rx: "నా ప్రిస్క్రిప్షన్‌ను సులభంగా వివరించండి",
    suggestion_remedies: "జలుబు మరియు దగ్గుకు ఆయుర్వేద చిట్కాలు",
    suggestion_exercise: "నా కోసం సురక్షితమైన యోగాసనాలను సూచించండి",
    suggestion_diet: "నేను ఈ రోజు ఎలాంటి ఆరోగ్యకరమైన ఆహారం తీసుకోవాలి?",
    no_previous_chats: "గత సంభాషణలు లేవు",
    start_first_chat: "AI ఆరోగ్య సహచరుడితో మొదటి సంభాషణను ప్రారంభించండి.",
    records_title: "వైద్య రికార్డులు",
    records_subtitle: "మీ పూర్తి ఆరోగ్య చరిత్ర — సెషన్లు, నివేదికలు మరియు అప్‌లోడ్‌లు.",
    add_medical_data: "డేటాను జోడించండి",
    record_new_history: "కొత్త చరిత్రను నమోదు చేయండి",
    upload_a_document: "పత్రాన్ని అప్‌లోడ్ చేయండి",
    view_read_rx: "ప్రిస్క్రిప్షన్ చూడండి & చదవండి",
    download_print_pdf: "PDF డౌన్‌లోడ్ / ప్రింట్",
    official_rx: "అధికారిక ప్రిస్క్రిప్షన్",
    lab_report: "ల్యాబ్ నివేదిక",
    history_session: "చరిత్ర సెషన్",
    prescribed_by: "సూచించిన డాక్టర్",
    medicines: "మందులు",
    advice: "సలహా",
    yoga_lifestyle: "యోగా / జీవనశైలి",
    view_document: "పత్రం చూడండి →",
    view_full_history: "పూర్తి చరిత్ర →",
    continue_recording: "కొనసాగించండి →",
    no_records: "ఇంకా రికార్డులు లేవు.",
    save: "భద్రపరచు",
    cancel: "రద్దు చేయి",
    close: "మూసివేయి",
    loading: "లోడ్ అవుతోంది…",
    error: "లోపం",
    retry: "మళ్ళీ ప్రయత్నించండి",
    back: "వెనుకకు",
    next: "తరువాత",
    submit: "సమర్పించండి",
    start: "ప్రారంభించండి",
    save_changes: "మార్పులను భద్రపరచండి",
  },

  mr: {
    care: "आरोग्य सेवा",
    dashboard: "डॅशबोर्ड",
    medical_records: "वैद्यकीय नोंदी",
    ai_health_assistant: "एआय आरोग्य सहाय्यक",
    upload_documents: "कागदपत्रे अपलोड",
    book_appointment: "अपॉइंटमेंट बुक करा",
    daily_routine: "दैनंदिन दिनचर्या",
    health_tracker: "आरोग्य ट्रॅकर",
    exercise_yoga: "व्यायाम आणि योग",
    ayurvedic_care: "आयुर्वेदिक काळजी",
    reminders: "औषध स्मरणपत्रे",
    account: "खाते",
    profile: "प्रोफाइल",
    patient_workspace: "रुग्ण कक्ष",
    signed_in: "साइन इन आहात",
    logout: "लॉगआउट",
    menu: "मेनू",
    high_contrast: "उच्च कॉन्ट्रास्ट",
    standard_view: "सामान्य दृश्य",
    language: "भाषा",
    select_language: "भाषा निवडा",
    welcome_back: "पुन्हा स्वागत आहे",
    hello: "नमस्कार",
    health_overview: "तुमचा संपूर्ण आरोग्य इतिहास — सत्रे, अहवाल आणि प्रिस्क्रिप्शन.",
    quick_actions: "जलद कृती",
    talk_to_ai: "एआय सहाय्यकाशी बोला",
    record_history: "इतिहास नोंदवा",
    view_records: "नोंदी पहा",
    vitals_summary: "महत्त्वपूर्ण चिन्हे",
    heart_rate: "हृदयाचे ठोके",
    blood_pressure: "रक्तदाब (BP)",
    blood_glucose: "ब्लड शुगर",
    bmi_weight: "बीएमआय आणि वजन",
    spo2: "ऑक्सिजन (SpO2)",
    recent_prescriptions: "अलीकडील औषधोपचार",
    upcoming_appointments: "आगामी अपॉइंटमेंट्स",
    no_prescriptions: "अद्याप कोणतीही औषधोपचार नोंद नाही",
    no_appointments: "कोणत्याही आगामी अपॉइंटमेंट्स नाहीत",
    chat_title: "एआय आरोग्य सहाय्यक",
    chat_subtitle: "तुमची औषधे, लक्षणे आणि आयुर्वेदिक टिप्सबद्दल विचारा.",
    new_chat: "+ नवीन संभाषण",
    conversations: "संभाषणे",
    type_message: "तुमच्या भाषेत आरोग्याशी संबंधित प्रश्न विचारा…",
    send: "पाठवा",
    thinking: "एआय विचार करत आहे…",
    chat_disclaimer: "एआय सहाय्यक केवळ मार्गदर्शन करतो, वैद्यकीय निदान नाही. आणीबाणीत तात्काळ डॉक्टरांशी संपर्क साधा.",
    emergency_detected: "तातडीची लक्षणे आढळली. कृपया ताबडतोब वैद्यकीय मदत घ्या.",
    suggestion_rx: "माझे प्रिस्क्रिप्शन सोप्या भाषेत समजावून सांगा",
    suggestion_remedies: "सर्दी आणि खोकल्यासाठी आयुर्वेदिक घरगुती उपाय",
    suggestion_exercise: "माझ्यासाठी सकाळचे सुरक्षित योगासने सुचवा",
    suggestion_diet: "निरोगी राहण्यासाठी मी आज काय खावे?",
    no_previous_chats: "मागील संभाषणे नाहीत",
    start_first_chat: "तुमच्या एआय आरोग्य साथीदारासोबत पहिले संभाषण सुरू करा.",
    records_title: "वैद्यकीय नोंदी",
    records_subtitle: "तुमचा संपूर्ण वैद्यकीय इतिहास — सत्रे, अहवाल आणि अपलोड.",
    add_medical_data: "वैद्यकीय माहिती जोडा",
    record_new_history: "नवीन इतिहास नोंदवा",
    upload_a_document: "दस्तऐवज अपलोड करा",
    view_read_rx: "प्रिस्क्रिप्शन पहा आणि वाचा",
    download_print_pdf: "पीडीएफ डाउनलोड / प्रिंट",
    official_rx: "अधिकृत प्रिस्क्रिप्शन",
    lab_report: "लॅब अहवाल",
    history_session: "इतिहास सत्र",
    prescribed_by: "डॉक्टर",
    medicines: "औषधे",
    advice: "सल्ला",
    yoga_lifestyle: "योग / जीवनशैली",
    view_document: "कागदपत्र पहा →",
    view_full_history: "पूर्ण इतिहास →",
    continue_recording: "नोंद सुरू ठेवा →",
    no_records: "अद्याप कोणत्याही नोंदी नाहीत.",
    save: "जतन करा",
    cancel: "रद्द करा",
    close: "बंद करा",
    loading: "लोड होत आहे…",
    error: "त्रुटी",
    retry: "पुन्हा प्रयत्न करा",
    back: "मागे",
    next: "पुढे",
    submit: "सादर करा",
    start: "सुरू करा",
    save_changes: "बदल जतन करा",
  },

  gu: {
    care: "આરોગ્ય સંભાળ",
    dashboard: "ડૅશબોર્ડ",
    medical_records: "મેડિકલ રેકોર્ડ્સ",
    ai_health_assistant: "AI આરોગ્ય સહાયક",
    upload_documents: "દસ્તાવેજ અપલોડ",
    book_appointment: "એપોઇન્ટમેન્ટ બુક કરો",
    daily_routine: "દૈનિક દિનચર્યા",
    health_tracker: "હેલ્થ ટ્રેકર",
    exercise_yoga: "કસરત અને યોગ",
    ayurvedic_care: "આયુર્વેદિક સંભાળ",
    reminders: "દવા રીમાઇન્ડર્સ",
    account: "ખાતું",
    profile: "પ્રોફાઇલ",
    patient_workspace: "દર્દી પોર્ટલ",
    signed_in: "લૉગ ઇન છો",
    logout: "લૉગ આઉટ",
    menu: "મેનુ",
    high_contrast: "હાઇ કોન્ટ્રાસ્ટ",
    standard_view: "સામાન્ય દૃશ્ય",
    language: "ભાષા",
    select_language: "ભાષા પસંદ કરો",
    welcome_back: "સ્વાગત છે",
    hello: "નમસ્તે",
    health_overview: "તમારો સંપૂર્ણ આરોગ્ય ઇતિહાસ — સત્રો, અહેવાલો અને પ્રિસ્ક્રિપ્શન્સ.",
    quick_actions: "ઝડપી ક્રિયાઓ",
    talk_to_ai: "AI સહાયક સાથે વાત કરો",
    record_history: "ઇતિહાસ રેકોર્ડ કરો",
    view_records: "રેકોર્ડ જુઓ",
    vitals_summary: "વાઇટલ્સ સારાંશ",
    heart_rate: "હૃદયના ધબકારા",
    blood_pressure: "બ્લડ પ્રેશર (BP)",
    blood_glucose: "બ્લડ સુગર",
    bmi_weight: "BMI અને વજન",
    spo2: "ઓક્સિજન (SpO2)",
    recent_prescriptions: "તાજેતરના પ્રિસ્ક્રિપ્શન્સ",
    upcoming_appointments: "આગામી એપોઇન્ટમેન્ટ્સ",
    no_prescriptions: "હજી કોઈ પ્રિસ્ક્રિપ્શન નથી",
    no_appointments: "કોઈ આગામી એપોઇન્ટમેન્ટ નથી",
    chat_title: "AI આરોગ્ય સહાયક",
    chat_subtitle: "તમારી દવાઓ, લક્ષણો અને આયુર્વેદિક ઉપચાર વિશે પૂછો.",
    new_chat: "+ નવી વાતચીત",
    conversations: "વાતચીત",
    type_message: "તમારી ભાષામાં પ્રશ્ન પૂછો…",
    send: "મોકલો",
    thinking: "AI વિચારી રહ્યું છે…",
    chat_disclaimer: "AI સહાયક માત્ર માર્ગદર્શન આપે છે, ડૉક્ટરનો વિકલ્પ નથી.",
    emergency_detected: "ઇમરજન્સી લક્ષણો જણાયા છે. કૃપા કરીને તાત્કાલિક સારવાર લો.",
    suggestion_rx: "મારું પ્રિસ્ક્રિપ્શન સરળ ભાષામાં સમજાવો",
    suggestion_remedies: "ખાંસી અને શરદી માટે આયુર્વેદિક ઘરેલું ઉપાય",
    suggestion_exercise: "મારા માટે સલામત સવારના યોગાસનો જણાવો",
    suggestion_diet: "આજે તંદુરસ્ત રહેવા માટે મારે શું ખાવું જોઈએ?",
    no_previous_chats: "કોઈ અગાઉની ચેટ નથી",
    start_first_chat: "તમારા AI સાથી સાથે વાતચીત શરૂ કરો.",
    records_title: "મેડિકલ રેકોર્ડ્સ",
    records_subtitle: "તમારો સંપૂર્ણ આરોગ્ય ઇતિહાસ.",
    add_medical_data: "ડેટા ઉમેરો",
    record_new_history: "નવો ઇતિહાસ નોંધો",
    upload_a_document: "દસ્તાવેજ અપલોડ કરો",
    view_read_rx: "પ્રિસ્ક્રિપ્શન વાંચો",
    download_print_pdf: "PDF ડાઉનલોડ / પ્રિન્ટ",
    official_rx: "અધિકૃત પ્રિસ્ક્રિપ્શન",
    lab_report: "લેબ રિપોર્ટ",
    history_session: "ઇતિહાસ સત્ર",
    prescribed_by: "તબીબ",
    medicines: "દવાઓ",
    advice: "સલાહ",
    yoga_lifestyle: "યોગ / જીવનશૈલી",
    view_document: "દસ્તાવેજ જુઓ →",
    view_full_history: "સંપૂર્ણ ઇતિહાસ →",
    continue_recording: "ચાલુ રાખો →",
    no_records: "કોઈ રેકોર્ડ મળ્યો નથી.",
    save: "સાચવો",
    cancel: "રદ કરો",
    close: "બંધ કરો",
    loading: "લોડ થઈ રહ્યું છે…",
    error: "ભૂલ",
    retry: "ફરી પ્રયાસ કરો",
    back: "પાછા",
    next: "આગળ",
    submit: "સબમિટ કરો",
    start: "શરૂ કરો",
    save_changes: "ફેરફારો સાચવો",
  },

  kn: {
    care: "ಆರೋಗ್ಯ ಸೇವೆ",
    dashboard: "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
    medical_records: "ವೈದ್ಯಕೀಯ ದಾಖಲೆಗಳು",
    ai_health_assistant: "AI ಆರೋಗ್ಯ ಸಹಾಯಕ",
    upload_documents: "ದಾಖಲೆಗಳ ಅಪ್‌ಲೋಡ್",
    book_appointment: "ಅಪಾಯಿಂಟ್‌ಮೆಂಟ್ ಬುಕ್ ಮಾಡಿ",
    daily_routine: "ದೈನಂದಿನ ದಿನಚರಿ",
    health_tracker: "ಆರೋಗ್ಯ ಟ್ರ್ಯಾಕರ್",
    exercise_yoga: "ವ್ಯಾಯಾಮ ಮತ್ತು ಯೋಗ",
    ayurvedic_care: "ಆಯುರ್ವೇದ ಆರೈಕೆ",
    reminders: "ಔಷಧ ಜ್ಞಾಪನೆಗಳು",
    account: "ಖಾತೆ",
    profile: "ಪ್ರೊಫೈಲ್",
    patient_workspace: "ರೋಗಿಯ ಸ್ಥಳ",
    signed_in: "ಸೈನ್ ಇನ್ ಆಗಿದ್ದೀರಿ",
    logout: "ಲಾಗ್ ಔಟ್",
    menu: "ಮೆನು",
    high_contrast: "ಹೆಚ್ಚಿನ ಕಾಂಟ್ರಾಸ್ಟ್",
    standard_view: "ಸಾಮಾನ್ಯ ನೋಟ",
    language: "ಭಾಷೆ",
    select_language: "ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ",
    welcome_back: "ಮರಳಿ ಸ್ವಾಗತ",
    hello: "ನಮಸ್ಕಾರ",
    health_overview: "ನಿಮ್ಮ ಸಂಪೂರ್ಣ ಆರೋಗ್ಯ ಇತಿಹಾಸ — ಸೆಷನ್‌ಗಳು, ವರದಿಗಳು ಮತ್ತು ಪ್ರಿಸ್ಕ್ರಿಪ್ಷನ್‌ಗಳು.",
    quick_actions: "ತ್ವರಿತ ಕ್ರಿಯೆಗಳು",
    talk_to_ai: "AI ಸಹಾಯಕನೊಂದಿಗೆ ಮಾತನಾಡಿ",
    record_history: "ಇತಿಹಾಸ ದಾಖಲಿಸಿ",
    view_records: "ದಾಖಲೆಗಳನ್ನು ನೋಡಿ",
    vitals_summary: "ಪ್ರಮುಖ ಅಂಕಿಅಂಶಗಳು",
    heart_rate: "ಹೃದಯ ಬಡಿತ",
    blood_pressure: "ರಕ್ತದೊತ್ತಡ (BP)",
    blood_glucose: "ರಕ್ತದಲ್ಲಿನ ಸಕ್ಕರೆ",
    bmi_weight: "BMI & ತೂಕ",
    spo2: "ಆಕ್ಸಿಜನ್ (SpO2)",
    recent_prescriptions: "ಇತ್ತೀಚಿನ ಪ್ರಿಸ್ಕ್ರಿಪ್ಷನ್‌ಗಳು",
    upcoming_appointments: "ಮುಂಬರುವ ಅಪಾಯಿಂಟ್‌ಮೆಂಟ್‌ಗಳು",
    no_prescriptions: "ಇನ್ನೂ ಯಾವುದೇ ಪ್ರಿಸ್ಕ್ರಿಪ್ಷನ್‌ಗಳಿಲ್ಲ",
    no_appointments: "ಯಾವುದೇ ಮುಂಬರುವ ಅಪಾಯಿಂಟ್‌ಮೆಂಟ್‌ಗಳಿಲ್ಲ",
    chat_title: "AI ಆರೋಗ್ಯ ಸಹಾಯಕ",
    chat_subtitle: "ನಿಮ್ಮ ಪ್ರಿಸ್ಕ್ರಿಪ್ಷನ್‌ಗಳು, ರೋಗಲಕ್ಷಣಗಳು ಮತ್ತು ಆಯುರ್ವೇದ ಸಲಹೆಗಳ ಬಗ್ಗೆ ಕೇಳಿ.",
    new_chat: "+ ಹೊಸ ಚಾಟ್",
    conversations: "ಸಂಭಾಷಣೆಗಳು",
    type_message: "ನಿಮ್ಮ ಭಾಷೆಯಲ್ಲಿ ಆರೋಗ್ಯ ಪ್ರಶ್ನೆಯನ್ನು ಕೇಳಿ…",
    send: "ಕಳುಹಿಸಿ",
    thinking: "AI ಯೋಚಿಸುತ್ತಿದೆ…",
    chat_disclaimer: "AI ಸಹಾಯಕ ಕೇವಲ ಮಾರ್ಗದರ್ಶನ ನೀಡುತ್ತದೆ, ವೈದ್ಯರ ಬದಲಿಗೆ ಅಲ್ಲ.",
    emergency_detected: "ತುರ್ತು ಲಕ್ಷಣಗಳು ಕಂಡುಬಂದಿವೆ. ದಯವಿಟ್ಟು ತಕ್ಷಣ ವೈದ್ಯರನ್ನು ಸಂಪರ್ಕಿಸಿ.",
    suggestion_rx: "ನನ್ನ ಪ್ರಿಸ್ಕ್ರಿಪ್ಷನ್ ಸರಳವಾಗಿ ವಿವರಿಸಿ",
    suggestion_remedies: "ನೆಗಡಿ ಮತ್ತು ಕೆಮ್ಮಿಗೆ ಆಯುರ್ವೇದ ಮನೆಮದ್ದುಗಳು",
    suggestion_exercise: "ನನಗಾಗಿ ಸುರಕ್ಷಿತ ಯೋಗಾಸನಗಳನ್ನು ಸೂಚಿಸಿ",
    suggestion_diet: "ಆರೋಗ್ಯವಾಗಿರಲು ಇಂದು ನಾನು ಏನು ಸೇವಿಸಬೇಕು?",
    no_previous_chats: "ಹಿಂದಿನ ಸಂಭಾಷಣೆಗಳಿಲ್ಲ",
    start_first_chat: "AI ಸಹಾಯಕನೊಂದಿಗೆ ಮೊದಲ ಸಂಭಾಷಣೆಯನ್ನು ಪ್ರಾರಂಭಿಸಿ.",
    records_title: "ವೈದ್ಯಕೀಯ ದಾಖಲೆಗಳು",
    records_subtitle: "ನಿಮ್ಮ ಸಂಪೂರ್ಣ ಆರೋಗ್ಯ ಇತಿಹಾಸ.",
    add_medical_data: "ಮಾಹಿತಿ ಸೇರಿಸಿ",
    record_new_history: "ಹೊಸ ಇತಿಹಾಸ ದಾಖಲಿಸಿ",
    upload_a_document: "ದಾಖಲೆ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ",
    view_read_rx: "ಪ್ರಿಸ್ಕ್ರಿಪ್ಷನ್ ನೋಡಿ",
    download_print_pdf: "PDF ಡೌನ್‌ಲೋಡ್ / ಪ್ರಿಂಟ್",
    official_rx: "ಅಧಿಕೃತ ಪ್ರಿಸ್ಕ್ರಿಪ್ಷನ್",
    lab_report: "ಲ್ಯಾಬ್ ವರದಿ",
    history_session: "ಸೆಷನ್",
    prescribed_by: "ವೈದ್ಯರು",
    medicines: "ಔಷಧಿಗಳು",
    advice: "ಸಲಹೆ",
    yoga_lifestyle: "ಯೋಗ / ಜೀವನಶೈಲಿ",
    view_document: "ದಾಖಲೆ ನೋಡಿ →",
    view_full_history: "ಸಂಪೂರ್ಣ ಇತಿಹಾಸ →",
    continue_recording: "ಮುಂದುವರಿಸಿ →",
    no_records: "ದಾಖಲೆಗಳು ಲಭ್ಯವಿಲ್ಲ.",
    save: "ಉಳಿಸಿ",
    cancel: "ರದ್ದುಮಾಡಿ",
    close: "ಮುಚ್ಚಿ",
    loading: "ಲೋಡ್ ಆಗುತ್ತಿದೆ…",
    error: "ದೋಷ",
    retry: "ಮರುಪ್ರಯತ್ನಿಸಿ",
    back: "ಹಿಂದೆ",
    next: "ಮುಂದೆ",
    submit: "ಸಲ್ಲಿಸಿ",
    start: "ಪ್ರಾರಂಭಿಸಿ",
    save_changes: "ಬದಲಾವಣೆಗಳನ್ನು ಉಳಿಸಿ",
  },

  ml: {
    care: "ആരോഗ്യ സംരക്ഷണം",
    dashboard: "ഡാഷ്‌ബോർഡ്",
    medical_records: "മെഡിക്കൽ രേഖകൾ",
    ai_health_assistant: "AI ആരോഗ്യ സഹായി",
    upload_documents: "രേഖകൾ അപ്‌ലോഡ് ചെയ്യുക",
    book_appointment: "അപ്പോയിന്റ്മെന്റ് ബുക്ക് ചെയ്യുക",
    daily_routine: "ദിനചര്യ",
    health_tracker: "ഹെൽത്ത് ട്രാക്കർ",
    exercise_yoga: "വ്യായാമവും യോഗയും",
    ayurvedic_care: "ആയുർവേദ പരിചരണം",
    reminders: "മരുന്ന് ഓർമ്മപ്പെടുത്തലുകൾ",
    account: "അക്കൗണ്ട്",
    profile: "പ്രൊഫൈൽ",
    patient_workspace: "രോഗിയുടെ പോർട്ടൽ",
    signed_in: "ലോഗിൻ ചെയ്തു",
    logout: "ലോഗൗട്ട്",
    menu: "മെനു",
    high_contrast: "ഉയർന്ന കോൺട്രാസ്റ്റ്",
    standard_view: "സാധാരണ കാഴ്ച",
    language: "ഭാഷ",
    select_language: "ഭാഷ തിരഞ്ഞെടുക്കുക",
    welcome_back: "സ്വാഗതം",
    hello: "നമസ്കാരം",
    health_overview: "നിങ്ങളുടെ പൂർണ്ണമായ ആരോഗ്യ ചരിത്രം — പരിശോധനകൾ, റിപ്പോർട്ടുകൾ.",
    quick_actions: "ദ്രുത പ്രവർത്തനങ്ങൾ",
    talk_to_ai: "AI സഹായിയോട് സംസാരിക്കുക",
    record_history: "ചരിത്രം രേഖപ്പെടുത്തുക",
    view_records: "രേഖകൾ കാണുക",
    vitals_summary: "പ്രധാന വിവരങ്ങൾ",
    heart_rate: "ഹൃദയമിടിപ്പ്",
    blood_pressure: "രക്തസമ്മർദ്ദം (BP)",
    blood_glucose: "ബ്ലഡ് ഷുഗർ",
    bmi_weight: "ബിഎംഐ & ഭാരം",
    spo2: "ഓക്സിജൻ (SpO2)",
    recent_prescriptions: "സമീപകാല കുറിപ്പടികൾ",
    upcoming_appointments: "വരാനിരിക്കുന്ന അപ്പോയിന്റ്മെന്റുകൾ",
    no_prescriptions: "കുറിപ്പടികൾ ലഭ്യമല്ല",
    no_appointments: "അപ്പോയിന്റ്മെന്റുകൾ ലഭ്യമല്ല",
    chat_title: "AI ആരോഗ്യ സഹായി",
    chat_subtitle: "നിങ്ങളുടെ മരുന്നുകൾ, ലക്ഷണങ്ങൾ, ആയുർവേദ മാർഗ്ഗങ്ങൾ എന്നിവയെക്കുറിച്ച് ചോദിക്കുക.",
    new_chat: "+ പുതിയ സംഭാഷണം",
    conversations: "സംഭാഷണങ്ങൾ",
    type_message: "നിങ്ങളുടെ ഭാഷയിൽ ആരോഗ്യ ചോദ്യം ചോദിക്കുക…",
    send: "അയക്കുക",
    thinking: "AI ചിന്തിക്കുന്നു…",
    chat_disclaimer: "AI സഹായി മാർഗ്ഗനിർദ്ദേശം മാത്രമാണ് നൽകുന്നത്, ഡോക്ടർക്ക് പകരമല്ല.",
    emergency_detected: "അടിയന്തര ലക്ഷണങ്ങൾ കണ്ടെത്തി. ഉടൻ തന്നെ വൈദ്യസഹായം തേടുക.",
    suggestion_rx: "എന്റെ കുറിപ്പടി ലളിതമായി വിശദീകരിക്കുക",
    suggestion_remedies: "ജലദോഷത്തിനും ചുമയ്ക്കും ആയുർവേദ പ്രതിവിധികൾ",
    suggestion_exercise: "എനിക്ക് അനുയോജ്യമായ യോഗാസനങ്ങൾ നിർദ്ദേശിക്കുക",
    suggestion_diet: "ആരോഗ്യവാനായിരിക്കാൻ ഇന്ന് എന്തൊക്കെ കഴിക്കണം?",
    no_previous_chats: "മുമ്പത്തെ സംഭാഷണങ്ങളില്ല",
    start_first_chat: "AI സഹായിയുമായി ആദ്യ സംഭാഷണം ആരംഭിക്കുക.",
    records_title: "മെഡിക്കൽ രേഖകൾ",
    records_subtitle: "നിങ്ങളുടെ പൂർണ്ണമായ ആരോഗ്യ ചരിത്രം.",
    add_medical_data: "വിവരങ്ങൾ ചേർക്കുക",
    record_new_history: "പുതിയ ചരിത്രം രേഖപ്പെടുത്തുക",
    upload_a_document: "രേഖ അപ്‌ലോഡ് ചെയ്യുക",
    view_read_rx: "കുറിപ്പടി കാണുക",
    download_print_pdf: "PDF ഡൗൺലോഡ് / പ്രിന്റ്",
    official_rx: "ഔദ്യോഗിക കുറിപ്പടി",
    lab_report: "ലാബ് റിപ്പോർട്ട്",
    history_session: "സെഷൻ",
    prescribed_by: "ഡോക്ടർ",
    medicines: "മരുന്നുകൾ",
    advice: "ഉപദേശം",
    yoga_lifestyle: "യോഗ / ജീവിതശൈലി",
    view_document: "രേഖ കാണുക →",
    view_full_history: "പൂർണ്ണ ചരിത്രം →",
    continue_recording: "തുടരുക →",
    no_records: "രേഖകൾ ലഭ്യമല്ല.",
    save: "സംരക്ഷിക്കുക",
    cancel: "റദ്ദാക്കുക",
    close: "അടയ്ക്കുക",
    loading: "ലോഡ് ചെയ്യുന്നു…",
    error: "പിശക്",
    retry: "വീണ്ടും ശ്രമിക്കുക",
    back: "പിന്നോട്ട്",
    next: "അടുത്തത്",
    submit: "സമർപ്പിക്കുക",
    start: "ആരംഭിക്കുക",
    save_changes: "മാറ്റങ്ങൾ സംരക്ഷിക്കുക",
  },

  pa: {
    care: "ਸਿਹਤ ਸੰਭਾਲ",
    dashboard: "ਡੈਸ਼ਬੋਰਡ",
    medical_records: "ਮੈਡੀਕਲ ਰਿਕਾਰਡ",
    ai_health_assistant: "AI ਸਿਹਤ ਸਹਾਇਕ",
    upload_documents: "ਦਸਤਾਵੇਜ਼ ਅੱਪਲੋਡ",
    book_appointment: "ਮੁਲਾਕਾਤ ਬੁੱਕ ਕਰੋ",
    daily_routine: "ਰੋਜ਼ਾਨਾ ਨੇਮ",
    health_tracker: "ਸਿਹਤ ਟਰੈਕਰ",
    exercise_yoga: "ਕਸਰਤ ਅਤੇ ਯੋਗਾ",
    ayurvedic_care: "ਆਯੁਰਵੈਦਿਕ ਦੇਖਭਾਲ",
    reminders: "ਦਵਾਈ ਰੀਮਾਈਂਡਰ",
    account: "ਖਾਤਾ",
    profile: "ਪ੍ਰੋਫਾਈਲ",
    patient_workspace: "ਮਰੀਜ਼ ਪੋਰਟਲ",
    signed_in: "ਲੌਗ ਇਨ ਹੋ",
    logout: "ਲੌਗ ਆਉਟ",
    menu: "ਮੀਨੂ",
    high_contrast: "ਉੱਚ ਕੰਟਰਾਸਟ",
    standard_view: "ਸਧਾਰਨ ਦ੍ਰਿਸ਼",
    language: "ਭਾਸ਼ਾ",
    select_language: "ਭਾਸ਼ਾ ਚੁਣੋ",
    welcome_back: "ਜੀ ਆਇਆਂ ਨੂੰ",
    hello: "ਸਤਿ ਸ੍ਰੀ ਅਕਾਲ",
    health_overview: "ਤੁਹਾਡਾ ਪੂਰਾ ਸਿਹਤ ਇਤਿਹਾਸ — ਰਿਪੋਰਟਾਂ ਅਤੇ ਨੁਸਖੇ।",
    quick_actions: "ਤੁਰੰਤ ਕਾਰਵਾਈਆਂ",
    talk_to_ai: "AI ਸਹਾਇਕ ਨਾਲ ਗੱਲ ਕਰੋ",
    record_history: "ਇਤਿਹਾਸ ਦਰਜ ਕਰੋ",
    view_records: "ਰਿਕਾਰਡ ਦੇਖੋ",
    vitals_summary: "ਮਹੱਤਵਪੂਰਨ ਸੂਚਕ",
    heart_rate: "ਦਿਲ ਦੀ ਧੜਕਣ",
    blood_pressure: "ਬਲੱਡ ਪ੍ਰੈਸ਼ਰ (BP)",
    blood_glucose: "ਬਲੱਡ ਸ਼ੂਗਰ",
    bmi_weight: "BMI ਅਤੇ ਭਾਰ",
    spo2: "ਆਕਸੀਜਨ (SpO2)",
    recent_prescriptions: "ਤਾਜ਼ਾ ਨੁਸਖੇ",
    upcoming_appointments: "ਆਗਾਮੀ ਮੁਲਾਕਾਤਾਂ",
    no_prescriptions: "ਕੋਈ ਨੁਸਖਾ ਮੌਜੂਦ ਨਹੀਂ ਹੈ",
    no_appointments: "ਕੋਈ ਮੁਲਾਕਾਤ ਤਹਿ ਨਹੀਂ ਹੈ",
    chat_title: "AI ਸਿਹਤ ਸਹਾਇਕ",
    chat_subtitle: "ਆਪਣੀਆਂ ਦਵਾਈਆਂ, ਲੱਛਣਾਂ ਅਤੇ ਆਯੁਰਵੈਦਿਕ ਨੁਸਖਿਆਂ ਬਾਰੇ ਪੁੱਛੋ।",
    new_chat: "+ ਨਵੀਂ ਗੱਲਬਾਤ",
    conversations: "ਗੱਲਬਾਤ",
    type_message: "ਆਪਣੀ ਭਾਸ਼ਾ ਵਿੱਚ ਸਿਹਤ ਸੰਬੰਧੀ ਸਵਾਲ ਪੁੱਛੋ…",
    send: "ਭੇਜੋ",
    thinking: "AI ਸੋਚ ਰਿਹਾ ਹੈ…",
    chat_disclaimer: "AI ਸਹਾਇਕ ਸਿਰਫ਼ ਮਾਰਗਦਰਸ਼ਨ ਲਈ ਹੈ, ਡਾਕਟਰ ਦਾ ਬਦਲ ਨਹੀਂ।",
    emergency_detected: "ਐਮਰਜੈਂਸੀ ਲੱਛਣ ਮਿਲੇ ਹਨ। ਕਿਰਪਾ ਕਰਕੇ ਤੁਰੰਤ ਡਾਕਟਰੀ ਸਹਾਇਤਾ ਲਓ।",
    suggestion_rx: "ਮੇਰਾ ਨੁਸਖਾ ਸਰਲ ਸ਼ਬਦਾਂ ਵਿੱਚ ਸਮਝਾਓ",
    suggestion_remedies: "ਖੰਘ ਅਤੇ ਜ਼ੁਕਾਮ ਲਈ ਆਯੁਰਵੈਦਿਕ ਘਰੇਲੂ ਨੁਸਖੇ",
    suggestion_exercise: "ਮੇਰੇ ਲਈ ਸੁਰੱਖਿਅਤ ਸਵੇਰ ਦਾ ਯੋਗਾ ਸੁਝਾਓ",
    suggestion_diet: "ਤੰਦਰੁਸਤ ਰਹਿਣ ਲਈ ਮੈਨੂੰ ਅੱਜ ਕੀ ਖਾਣਾ ਚਾਹੀਦਾ ਹੈ?",
    no_previous_chats: "ਕੋਈ ਪਿਛਲੀ ਗੱਲਬਾਤ ਨਹੀਂ",
    start_first_chat: "ਆਪਣੇ AI ਸਹਾਇਕ ਨਾਲ ਗੱਲਬਾਤ ਸ਼ੁਰੂ ਕਰੋ।",
    records_title: "ਮੈਡੀਕਲ ਰਿਕਾਰਡ",
    records_subtitle: "ਤੁਹਾਡਾ ਪੂਰਾ ਸਿਹਤ ਇਤਿਹਾਸ।",
    add_medical_data: "ਡਾਟਾ ਸ਼ਾਮਲ ਕਰੋ",
    record_new_history: "ਨਵਾਂ ਇਤਿਹਾਸ ਦਰਜ ਕਰੋ",
    upload_a_document: "ਦਸਤਾਵੇਜ਼ ਅੱਪਲੋਡ ਕਰੋ",
    view_read_rx: "ਨੁਸਖਾ ਦੇਖੋ ਅਤੇ ਪੜ੍ਹੋ",
    download_print_pdf: "PDF ਡਾਊਨਲੋਡ / ਪ੍ਰਿੰਟ",
    official_rx: "ਅਧਿਕਾਰਤ ਨੁਸਖਾ",
    lab_report: "ਲੈਬ ਰਿਪੋਰਟ",
    history_session: "ਇਤਿਹਾਸ ਸੈਸ਼ਨ",
    prescribed_by: "ਡਾਕਟਰ",
    medicines: "ਦਵਾਈਆਂ",
    advice: "ਸਲਾਹ",
    yoga_lifestyle: "ਯੋਗਾ / ਜੀਵਨ ਸ਼ੈਲੀ",
    view_document: "ਦਸਤਾਵੇਜ਼ ਦੇਖੋ →",
    view_full_history: "ਪੂਰਾ ਇਤਿਹਾਸ →",
    continue_recording: "ਜਾਰੀ ਰੱਖੋ →",
    no_records: "ਕੋਈ ਰਿਕਾਰਡ ਨਹੀਂ ਮਿਲਿਆ।",
    save: "ਸੰਭਾਲੋ",
    cancel: "ਰੱਦ ਕਰੋ",
    close: "ਬੰਦ ਕਰੋ",
    loading: "ਲੋਡ ਹੋ ਰਿਹਾ ਹੈ…",
    error: "ਗ਼ਲਤੀ",
    retry: "ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ",
    back: "ਪਿੱਛੇ",
    next: "ਅੱਗੇ",
    submit: "ਜਮ੍ਹਾਂ ਕਰੋ",
    start: "ਸ਼ੁਰੂ ਕਰੋ",
    save_changes: "ਤਬਦੀਲੀਆਂ ਸੰਭਾਲੋ",
  },
};

const LANG_KEY = "patient_preferred_language";

export function LanguageProvider({ children }) {
  const { patient, isAuthenticated, role } = useAuth();

  const [language, setLanguageState] = useState(() => {
    return localStorage.getItem(LANG_KEY) || patient?.preferredLanguage || "en";
  });

  // Sync if patient profile has a language preference
  useEffect(() => {
    if (patient?.preferredLanguage && patient.preferredLanguage !== language) {
      setLanguageState(patient.preferredLanguage);
      localStorage.setItem(LANG_KEY, patient.preferredLanguage);
    }
  }, [patient?.preferredLanguage]);

  // Set document language
  useEffect(() => {
    document.documentElement.lang = language;
    localStorage.setItem(LANG_KEY, language);
  }, [language]);

  const setLanguage = async (newLang) => {
    setLanguageState(newLang);
    localStorage.setItem(LANG_KEY, newLang);
    document.documentElement.lang = newLang;

    // If logged in as patient, persist to database
    if (isAuthenticated && role === "patient") {
      try {
        await updateCurrentPatient({ preferredLanguage: newLang });
      } catch (err) {
        console.warn("[LanguageProvider] Could not sync language to backend:", err?.message);
      }
    }
  };

  const t = (key, fallback = "") => {
    const bundle = TRANSLATIONS[language] || TRANSLATIONS.en;
    if (bundle && bundle[key] !== undefined) {
      return bundle[key];
    }
    // Fallback to English
    if (TRANSLATIONS.en && TRANSLATIONS.en[key] !== undefined) {
      return TRANSLATIONS.en[key];
    }
    return fallback || key;
  };

  const activeLangMeta = useMemo(() => {
    return SUPPORTED_LANGUAGES.find((l) => l.code === language) || SUPPORTED_LANGUAGES[0];
  }, [language]);

  const value = useMemo(
    () => ({
      language,
      setLanguage,
      t,
      languages: SUPPORTED_LANGUAGES,
      activeLanguage: activeLangMeta,
    }),
    [language, activeLangMeta],
  );

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
